### ISSUE TITLE
Multiple Processors Behavior

### ISSUE THREAD

**Issue by saied89** [google/ksp#1007]
The document is quite thorough on the incremental and multiple round behavior but I couldn't find anything regarding multiple processor behavior. It makes sense to want to break up the logic into multiple processors and the playground sample also has two, Is it considered a bad practice though?
In particular I'm trying to have a 2 step process where a step generates some code based on the source(in finish method) and another generates some more code based on output of the first processor, but second processor doesn't pick any output from first one. Should I merge the processors?

**Comment by saied89** [comment]
Just got it to work! Moving code generation from `finish` method to a visitor fixed the issue.
Seems like the code generated in `finish` wouldn't be picked by second processor (which makes sense)

**Comment by saied89** [comment]
Might be a good idea to briefly mention multi processor behavior in multi round doc.

**Comment by neetopia** [comment]
It's not that code generated in `finish` is not picked up, but rather that `finish` is intended to be only called at the end of whole multiple round processing, therefore the code generated there can't be considered for future processing, not even by the processor itself.

**Comment by saied89** [comment]
yes. makes sense. thanks

**Comment by neetopia** [comment]
closing as resolved. Will note on document later.
