### ISSUE TITLE
Clarification—when can `KSTypeArgument.type` be `null`?

### ISSUE THREAD

**Issue by popematt** [google/ksp#1027]
I was investigating an issue I had while using KotlinPoet + KSP on a recursive type bound with a wildcard projection, and it led me to the [`KSTypeArgument.type`](https://github.com/google/ksp/blob/8b6a79aa518e25d2c27812c51ba8668e959c00f5/api/src/main/kotlin/com/google/devtools/ksp/symbol/KSTypeArgument.kt#L28-L31) property. KotlinPoet, in [this function](https://github.com/square/kotlinpoet/blob/963c2a9025e73a9b115aa2f419af2cc9da7ade46/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/ksTypes.kt#L159-L169), assumes that if `KSTypeArgument.type` is null, that is equivalent to a "star" projection. After diving into the KSP implementation, I think the problem lies in KotlinPoet rather than KSP.

However, I believe that part of the reason there's a problem in KotlinPoet is that the `KSTypeArgument` interface does not provide any contract/meaning for when `KSTypeArgument.type` is or can be `null`. Looking at the implementations of `KSTypeArgument` does not make it particularly clear to me either.

This implementation cannot return `null`.
https://github.com/google/ksp/blob/8b6a79aa518e25d2c27812c51ba8668e959c00f5/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeArgumentDescriptorImpl.kt#L46-L48

Neither can this one.
https://github.com/google/ksp/blob/8b6a79aa518e25d2c27812c51ba8668e959c00f5/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeArgumentLiteImpl.kt#L32

This implementation can return `null`, but says nothing about why it would be `null`.
https://github.com/google/ksp/blob/8b6a79aa518e25d2c27812c51ba8668e959c00f5/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeArgumentImpl.kt#L72-L78

The implementation for Java has a cryptic comment talking about modeling "unbounded" types.
https://github.com/google/ksp/blob/8b6a79aa518e25d2c27812c51ba8668e959c00f5/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeArgumentJavaImpl.kt#L47-L50

My theory is that `KSTypeArgument.type` should be null for a raw type, and it should be non-null when the type parameters are present. (E.g. `List` vs `List<?>`.) Is that correct?

**Comment by popematt** [comment]
So, when `type` is `null`, `variance` should be `STAR`, and vice versa?

The issue I was having with KotlinPoet happened when `type` was not null and `variance` was `STAR`. I can work on providing a minimal reproducible example if you like.

**Comment by popematt** [comment]
Thanks for the clarification.

**Comment by popematt** [comment]
If the `variance` is `STAR` and the `type` is non-null, what value gets used for `type`? Does it end up being a real type that fits the bounds of the type parameter? (E.g. for `List<*>` the `KSTypeArgument.type` is `Any` or for `Enum<*>` the `KSTypeArgument.type` is `Enum<*>`.)

**Comment by neetopia** [comment]
it should be, type might be available for star `projections` if it comes from libraries, and it should respect the restriction from declaration site.

**Comment by neetopia** [comment]
closing as answered.
