### ISSUE TITLE
Question: Is it at all possible to use KSP to get details from a Kotlin DSL lambda?

### ISSUE THREAD

**Issue by v79** [google/ksp#1044]
Hi,
I'm trying to work out of KSP can help me interogate a code block which is something like this:

```kotlin
@Router
fun myRouter() =
  route {
    get("/hello") {
      println("hello")
    }
    get("/bananas") {
      println("bananas")
    }
}
```
I'm trying to get a list of all the calls to `get()`, and the parameters passed to each call (which are, at least, a string and a trailing lambda function or actual function like `get("/function",::myFunction)`. The `@Router` annotation could be attached to a class, a function, a property declaration - I can change my code if it helps make this work.

I'd then use codeGenerator to produce a text file output something like:
```
GET  /hello  com.example.routes.RouterClass::myFunction
```

But I think it is not possible?

If it is not possible, would *kapt* be able to do what I'm hoping for?

With thanks.

**Comment by v79** [comment]
I've been trying to work out how the Kotless project does this - looks like they are doing a full AST analysis of the source code, just as the compiler has to do. Not something I could replicate myself.
I still need to work out how I can get the information I need at compile (not run) time. Ah well.

**Comment by neetopia** [comment]
Closing as answered.
