### ISSUE TITLE
Find the receiver for function types.

### ISSUE THREAD

**Issue by evant** [google/ksp#1048]
I can't find a way to figure out when a function type has a receiver, ex:
```kotlin
val myType: String.() -> Unit
```

seems indistinguishable from:
```kotlin
val myType: (String) -> Unit
```

**Comment by neetopia** [comment]
Can you link a use case in your code for this?

**Comment by evant** [comment]
https://github.com/evant/kotlin-inject/issues/210 shows where I ran into this. I'm simply trying to copy over constructor parameters and receiver functions types don't copy correctly.

**Comment by evant** [comment]
Update: figured out this is possible by checking `KSTypeReference.element is KSCallableReference`, closing.
