### ISSUE TITLE
Memory leak: org.sqlite.JDBC holds classloader of KSP

### ISSUE THREAD

**Issue by ting-yuan** [google/ksp#1063]
This happens when running Room:
1. Kotlin compiler daemon loads compiler plugins (KSP) with a new class loader every time it gets a request from Gradle. 
2. KSP loads processors(Room) with a child classloader.
3. Room uses `org.sqlite.JDBC`, which is also loaded with Room's classloader.
4. `org.sqlite.JDBC`'s static initializer calls `java.sql.DriverManager.registerDriver`, which stores the class `org.sqlite.JDBC` in a static member of `java.sql.DriverManager`.
6. `java.sql.DriverManager` is loaded by the root classloader.
7. Therefore all everything loaded with KSP's classloader can also be reached by the root classloader and never be GC'ed.

Here is [a sample project](https://github.com/BugsBunnyBR/KspMemory) thanks to @BugsBunnyBR.

![Screenshot 2022-08-13 01 37 09](https://user-images.githubusercontent.com/3227560/184476092-9f308d6f-fcc3-4245-8aa2-a54f6a00cdcc.png)

**Comment by BugsBunnyBR** [comment]
@ting-yuan @neetopia 
Thank you for your analysis and mitigation efforts!
It seems that more could be done on Room side of things, so I opened [this issue](https://issuetracker.google.com/issues/242575306) on Room issue tracker. Maybe you folks could contribute with your thoughts there ?

**Comment by BugsBunnyBR** [comment]
Should we try to open an issue on Sqlite too?

**Comment by ting-yuan** [comment]
This is fixed in Room already. It is also mitigated in #1067 in case there are other processors with similar issue.

**Comment by BugsBunnyBR** [comment]
To the people watching this issue...

I ran the benchmark in a [branch with the latest version of room ](https://github.com/BugsBunnyBR/KspMemory/tree/ksp-room-alpha) and these are the results.
![Screenshot 2022-08-25 at 15 49 40](https://user-images.githubusercontent.com/70573/186682916-237cbd86-46b8-4c62-aa7d-fd2e3fa2ff7e.png)

This is way better than before, even though it seems to use lots of memory I was able to run 50 iterations and didn't get an out of memory. 👏 👏 
I will be waiting a version of ksp to verify the final results.

**Comment by BugsBunnyBR** [comment]
So, I updated ksp/kotlin/room to the [latest version](https://github.com/BugsBunnyBR/KspMemory/tree/ksp-room-beta) and ran the benchmark again. The behaviour of the memory consumption improved by a lot! Not only that, but the number of live threads stabilised too. Great work folks! 👏 👏 🍰 
 
![Screenshot 2022-10-16 at 12 36 48](https://user-images.githubusercontent.com/70573/196030733-759ad8db-4b6e-45ec-8960-50dfc2d54bb9.png)
