### ISSUE TITLE
Is ksp.incremental.intermodule enabled by default now?

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1064]
It's enabled by default in my test, but not enabled in the introduction on the authoritative website. I doubt my test method, so I  ask you for a confirmation.

**Comment by ting-yuan** [comment]
Sorry for the late reply. Yes, it is enabled by default:
https://github.com/google/ksp/blob/5c7fab6344939773e6ad9eb480231b5beabc274d/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L505
