### ISSUE TITLE
Add ability to retrieve default values of parameters of function [Feature Req]

### ISSUE THREAD

**Issue by kasem-sm** [google/ksp#1072]
I got a use-case to retrieve the default values added to the params of a function. Is this feature request in the TODO list of the KSP team as I think it would be nice to have it. Currently, we can only check if there exists any default value (Boolean) but we can't retrieve the same.

**Comment by neetopia** [comment]
Currently, this is not supported and unfortunately, we do not have a plan to support such use case.

**Comment by kasem-sm** [comment]
Ah! There are of course some workarounds and I may continue using it till then. Thank You!

Should I proceed to close this issue?

**Comment by neetopia** [comment]
Closing as answered :)

**Comment by byencho** [comment]
@kasem-sm What exactly are the workarounds you referring to?

**Comment by brian-livefront** [comment]
Sounds good, thanks @kasem-sm !
