### ISSUE TITLE
Question: how to make getSymbolsWithAnnotation() method return annotations also from dependency modules (like getDeclarationsFromPackage method) and not only from sourceset?

### ISSUE THREAD

**Issue by Marcoral** [google/ksp#1075]
Hi
I'm working on a Kotlin project whose logic is heavily annotation-driven. KSP is helping me a lot with this.
Unfortunately, I've been facing a problem for quite a while now, which I don't know how to solve on my own - it's in the ticket title.
I noticed that a similar question has been asked before:

#527 

but I feel that the answer contained in it doesn't suit my case.

I have prepared a small example of what I am trying to achieve:
[https://github.com/Marcoral/KSP-resolving-problem](https://github.com/Marcoral/KSP-resolving-problem)

Perhaps the getSymbolsWithAnnotation() method should contain some kind of flag to control whether symbols from sourceset only or also from dependencies should be visible? I noticed that the getDeclarationsFromPackage() method can detect the latter as well, but in my example w I can't use it (the annotation processor can't be changed with the creation of new libraries providing the annotations it should detect).

I would be very grateful for the help provided

**Comment by neetopia** [comment]
It is not supported in KSP, and potential implementation to support this will be very slow as it needs to scan the whole classpath, therefore we do not have a plan to support this use case.

`getDeclarationsFromPackage` is a different story as getting symbols from class path given package name is efficient enough as the path to look up symbols are determined.

**Comment by neetopia** [comment]
Closed as answered.

**Comment by eugene-krivobokov** [comment]
> getDeclarationsFromPackage is a different story as getting symbols from class path given package name is efficient enough as the path to look up symbols are determined.

Does it mean that `getDeclarationsFromPackage` should see classes from the whole classpath?
