### ISSUE TITLE
KsType.innerArguments vs arguments

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1080]
The library: 
val KSType.innerArguments: List<KSTypeArgument>
    get() = arguments.subList(0, declaration.typeParameters.size)

My confusion: what are the arguments except innerArguments if there are any?

**Comment by neetopia** [comment]
`innerArguments` are there due to how compiler models type arguments in case of a nested type, basically compiler will carry the type arguments from its outer classes, therefore we provided this utility to better model type arguments for nested types.

**Comment by WilliamKwokX** [comment]
Here is the clear different I just figured out.
`class A<T: List<*>>{
    inner class AA<V>

    val aa = AA<Any>()
}`
w: [ksp] arguments: [INVARIANT Any, INVARIANT T]
w: [ksp] innerArguments: [INVARIANT Any]
