### ISSUE TITLE
May to Many table query on DAO fails to create methods 

### ISSUE THREAD

**Issue by cp-yfukuda** [google/ksp#1100]
I have this many to may query table where Ksp doesn't generate Impl class that 
creates method. 

TestProxyDao_Impl.java:26: error: TestProxyDao_Impl is not abstract and does not override abstract method getReadGroupIds(Set<Identifier<Test>>,Continuation<? super List<TestWithTest2>>) in TestProxyDao

Here is the simple app that can generate same error. 
https://drive.google.com/file/d/1O1qqDoVA-34A5E7VwJe5eZSz9TsUb4sp/view?usp=sharing

**Comment by neetopia** [comment]
Your issue looks more like a room issue, can you please file an issue with Room for better context?

**Comment by cp-yfukuda** [comment]
Done. Thank you for the suggestion!

**Comment by neetopia** [comment]
closed for now as you have a separate tracking issue for this. Feel free to reopen if investigation from Room points to any bug on KSP.
