### ISSUE TITLE
Bug: new files with declarations oriented to old generated declarations are always invalid.

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1109]
For example, assuming there is a built file containing class A, now I add a new file with a declaration
```
import A

val a: A = A()
```
There is no warning at present. However, in the subsequent ksp building with incremental mode, the resolved type of this property is an error. There is no package problem in this test.

**Comment by ting-yuan** [comment]
Ideally, we want the outputs to be stable and consistent with the inputs only. References from files (whether newly added or pre-existing) to generated files should not be resolvable **in the first round**. Maybe multiple round processing could be helpful in this use case?

This is similar to #1141.

**Comment by WilliamKwokX** [comment]
Well, suppose this class is generated by some other `KspSymbolProcessorProvider`.
```
class X
```

And annotation `Interesting` is from my ksp library.
```
@Interesting
val x = X()
```
Now I can't process this property.
