### ISSUE TITLE
No messages displayed when I use KSPLogger.logging and info.

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1111]
Those messages used by the two functions are not displayed in my terminal console.
<img width="803" alt="Screen Shot 2022-09-15 at 16 57 34" src="https://user-images.githubusercontent.com/57835556/190361944-dbaaace7-ac22-4f65-9095-b0fdf9e16ab5.png">

**Comment by neetopia** [comment]
you need to specify `--info` in your gradle command to see the info level logging.

**Comment by JailedBird** [comment]
> 

I run into the same question, eager for answers

**Comment by neetopia** [comment]
when running KSP with Gradle, KSP will use the gradle logger for logging purpose, and if you are logging with `logging` and `info` with KSPLogger, under the hood it will be logging to `info` level logs in Gradle logger, and therefore you need to specify the Gradle logger to logging level `info` to see the logs.

**Comment by WilliamKwokX** [comment]
I mean I haven't found that gradle command.

**Comment by neetopia** [comment]
you just need to add `--info` to your gradle arguments, it is not a command.

**Comment by WilliamKwokX** [comment]
Thanks a lot!

**Comment by WilliamKwokX** [comment]
--info works but --debug not. Which argument corresponds to 'logging'?

**Comment by neetopia** [comment]
`--debug` should be reporting `logging` level logs. 
https://github.com/JetBrains/kotlin/blob/d9ddcd991bf9c6122041f0276af644be0432fa38/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/logging/GradlePrintingMessageCollector.kt#L54

**Comment by WilliamKwokX** [comment]
I finally found out the reason. When --info is enabled, the logs would be taken out in the left console window. When --debug is enabled, the logs would be mixed in all logs. This feature can be improved. 
[
<img width="1187" alt="Screen Shot 2022-10-07 at 02 09 13" src="https://user-images.githubusercontent.com/57835556/194387417-2d534f9a-5c99-4a98-85df-0e5a99b1e3fc.png">
](url)
