### ISSUE TITLE
Accessing properties, functions and typealiases by their fully qualified name

### ISSUE THREAD

**Issue by IVIanuu** [google/ksp#112]
It should be possible get properties, functions and typealiases by their fully qualified name.

Api could look similar like `Resolver.getClassDeclarationByName`

**Comment by ting-yuan** [comment]
Yes it is possible. Can you give an example why this is necessary or convenient?

**Comment by IVIanuu** [comment]
For example I tried to rewrite my DI plugin to use KSP. I generate top-level functions and typealiases but I can never reference them again because I can only get classes by their name.

Btw there should be also a way to get all declarations in a package. E.g. getDeclarationsInPackage(fqName: String).

**Comment by evant** [comment]
You can do `resolver.getAllFiles()` and search them yourself, but I agree it would be convenient to get a top-level function etc directly if you already know the name.

**Comment by IVIanuu** [comment]
I don't need to get the declarations in the current compilation unit but from others. So I cannot search for them in the files of the current compilation

**Comment by IVIanuu** [comment]
See Dagger Hilt or Anvil from Square both of them wouldn't be possible to implement with KSP because they aggregate information across compilations. They store the information as classes and properties in a single package. And read the information by getting all declarations in that specific package.

**Comment by ting-yuan** [comment]
Thanks, this is an interesting use case that we didn't thought of. Will add the API.

BTW, it should be possible by accessing FileKt where top level functions and properties are stored. That is platform and implementation specific, though.

**Comment by neetopia** [comment]
#387
