### ISSUE TITLE
Kotlin compilation tasks eagerly realised when KSP Gradle plugin applied

### ISSUE THREAD

**Issue by 3flex** [google/ksp#1124]
Kotlin compilation tasks are eagerly realised during Gradle's configuration phase when the KSP plugin is applied. This means the techniques described [here ](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) are not being followed properly.

The `get()` call here looks like the culprit though there might be other places where tasks are eagerly realised:

https://github.com/google/ksp/blob/cfdf696f16f98fbeda32ea8f863dbdccf4e159e8/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L247

Refactoring around this looks possible but not completely trivial - I'm not familiar with the plugin's behaviour so not working on a PR yet.

The eager realisation of tasks can be seen in `examples/playground`. Run `./gradlew help --scan`, go to Performance > Configuration and see the tasks that are created ("Created during configuration" at the bottom of the screenshot):

![image](https://user-images.githubusercontent.com/170028/192130131-2ac14b1a-542c-46f4-bebf-3133149f40fb.png)

Commenting out `id("com.google.devtools.ksp")` in `examples/playground/workload/build.gradle.kts`, and the use of the `ksp` configuration & extension, will reduce that to zero.

**Comment by runningcode** [comment]
Still an issue on the latest `main`: https://github.com/google/ksp/blob/fc22e8f947fb533e3f728252882c9dbe3f4d810d/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L229
