### ISSUE TITLE
Regression: cannot resolve annotation in common code

### ISSUE THREAD

**Issue by manosbatsis** [google/ksp#1125]
Used to work with 1.6.21, doesn't in 1.7.10. Maybe a regression of https://github.com/google/ksp/issues/632 or similar

- `kmm-annotation-module` (annotation in commonMain)
- ` jvm-ksp-processor-module` (non-kmm, proc etc. in main)
- `kmm-ksp-client-module` with:

```kotlin
dependencies {
    // Doesn't help
    // add("kspCommonMainMetadata", project(":kmm-annotation-module"))
    add("kspCommonMainMetadata", project(":jvm-ksp-processor-module"))
}
```
Issues:

1. Annotations cannot be found using strongly-typed APIs e.g. with `getAnnotationsByType`.  However they can be found when iterating `KSAnnotated.annotations` and e.g. checking the item's `shortName.asString()`.
2. Trying to resolve a  `KSAnnotation.annotationType` returns `<error>` type.
3. Reading annotations of an annotation doesn't seem feasible.

**Comment by neetopia** [comment]
getByType requires the annotation being on classpath, note that there is a change in KMP project structure configurations that if you only have one target platform, tasks might be different. see https://github.com/google/ksp/issues/980#issuecomment-1245928734 for more detail on a similar issue. At this moment I can't determine what is the cause for your project, it would be great if you can provide a reproduce.

**Comment by manosbatsis** [comment]
Thank you @neetopia, see repro [here](https://github.com/manosbatsis/google-ksp-1125).

**Comment by manosbatsis** [comment]
Also please let me know if i can make it easier for you to go over the reproduce or otherwise help in any way; happy to answer any questions join a call etc.

**Comment by dimsuz** [comment]
I've run into this issue too.

If this is indeed caused by the regression similar https://github.com/google/ksp/issues/980#issuecomment-1245928734, and is to be considered an issue with the KMP plugin, what kind of bug should be reported there? 

As a user of KSP with the only wish of having a working `getSymbolsWithAnnotation` I'm a bit at a loss of how to proceed :)  

Requiring all my library users to add a `js { browser() }` target or some other to fix things is not a good workaround...

**Comment by neetopia** [comment]
as per https://github.com/google/ksp/issues/980#issuecomment-1245928734 , it is more like a limitation with new hmpp model for KMP projects, where KSP is not involved, therefore there is nothing KSP can do to fix it, I would suggest adding another target for your annotation module for now and maybe report to Jetbrains on youtrack regarding no metadata is generated for single target multiple platform projects.
