### ISSUE TITLE
Add a way to check if a KSFunctionDeclaration is a constructor

### ISSUE THREAD

**Issue by IVIanuu** [google/ksp#113]
The only way i found was to check if the simpleName == \<init\>
There's already a `FunctionKind` enum which could include `CONSTRUCTOR`

**Comment by ting-yuan** [comment]
Elements in `FunctionKind` are disjoint. `CONSTRUCTOR` would overlap with `MEMBER`. Does an extension like `KSFunctionDeclaration.isConstructor` in utils make sense?

**Comment by IVIanuu** [comment]
Yes i think the extension is a good idea.
