### ISSUE TITLE
How does KSClassDeclaration determine the type of a class

### ISSUE THREAD

**Issue by 1678672609** [google/ksp#1140]
150/5000 
I now have a requirement that when I get a KSClassDeclaration object, I want to be able to get the type of the class, such as: This class is either 'interface' or 'data class' or 'Abstract class' or 'annotation class', but the current API method 'classKind' only gets partial information

**Comment by neetopia** [comment]
a data class is still considered a class, for your purpose, you can combine `ClassKind` property with other properties such as modifiers to determine the class type you are referring to.
