### ISSUE TITLE
Elements.getTypeElement can load types generated in previous incremental runs but KSP's APIs can't

### ISSUE THREAD

**Issue by amandeepg** [google/ksp#1141]
In Java annotation processing or Kapt, `Elements.getTypeElement` can load types that have been generated in the previous runs of the incremental compiler, while KSP's `Resolver` does not make this resolvable. My workaround is using `ResolverImpl.incrementalContext.symbolsMap.keys` since I only need to need the existence of a given generated file.

**Comment by ting-yuan** [comment]
While designing incremental processing in KSP, one of our goals is to make processing a pure function. I.e., users shouldn't be aware of whether they are doing a clean build or incremental build except for build time. Ideally, outputs should be stable and consistent.

I'm not sure whether Java annotation processing or KAPT's behavior is intended or a bug. Do you have a use case that this behavior is really needed?

On the other hand, I'm wondering if that is a side-effect of adding the generated sources to the current source set. Currently KSP explicitly excludes generated sources from its inputs. This might be why you observed different behaviors between KSP and KAPT.
