### ISSUE TITLE
How does ksp get generic types in classes?

### ISSUE THREAD

**Issue by catchpig** [google/ksp#1142]
class ArticleAdapter : RecyclerAdapter<Article, ItemArticleBinding>() {
}

**Comment by brookmg** [comment]
@catchpig Did you find a way for it or?

**Comment by catchpig** [comment]
> @catchpig Did you find a way for it or?

I don't find a way

**Comment by neetopia** [comment]
what's wanted here? Can you describe in details?

**Comment by brookmg** [comment]
I was able to achieve this.
```kt
class A : Store<B, C> { }
```

So to get the type of B and C
```kt
val B = it.superTypes.first().resolve().arguments.first().type?.resolve()?.declaration
print(B?.qualifiedName?.asString())

val C = it.superTypes.first().resolve().arguments.elementAtOrNull(1)?.type?.resolve()?.declaration
print(C?.qualifiedName?.asString())
```

**Comment by neetopia** [comment]
Yes, that's what I would expect for getting type arguments, glad you figured it out!
