### ISSUE TITLE
When would KSTypeArgument.name be null?

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1151]
In my test, java annotation arguments would be cleared, and all kotlin annotation arguments have their names. It doesn't matter whether the input kotlin argument name is specified.

**Comment by neetopia** [comment]
not sure about your question, KSTypeArgument does not have a name property. https://github.com/google/ksp/blob/main/api/src/main/kotlin/com/google/devtools/ksp/symbol/KSTypeArgument.kt
