### ISSUE TITLE
No way to access expressions at all?

### ISSUE THREAD

**Issue by toddobryan** [google/ksp#1152]
I'm using a `data class` to generate a companion class and I need to know if and how the data class's properties are initialized.

To be concrete,
```
data class MyClass(val a: Int, val b: String = "xyz")
```
generates something like
```
class MyClassHelper {
    val a by property(IntType)
    val b by property(StringType, "xyz")
}
```

Unfortunately, I think I've decided that I can't do the second one at all because there's no way with KSP to get access to the `= expression` part of the [property declaration](https://kotlinlang.org/docs/reference/grammar.html#propertyDeclaration).

These seem like really useful cases for code generation, and it doesn't seem like KSP can handle them at the moment. Any plans for providing some way to do it? Something as simple as having a way to access the source code would let me get in there and try to find the value myself, although that's obviously not ideal.

I think this is probably similar to the problem with local variables and initializer blocks that has been marked as P3, but I'm wondering if there's some sort of easy workaround that could make this sort of thing _possible_ for now, even if it's not pretty.

Without this, my use case for KSP just can't be done at all.

**Comment by neetopia** [comment]
unfortunately KSP does not support such use case, an alternative solution is to put the default value in an annotation argument, which KSP is capable of resolving.

**Comment by toddobryan** [comment]
Yeah. That becomes an unfortunate violation of DRY, since the annotation value and the default would have to stay in sync, but there's nothing to guarantee that they would. Is the source code not available at all when KSP runs or does KSP just choose to ignore it?

**Comment by neetopia** [comment]
source code is available, but evaluating expression itself can be complex and KSP choose not to support expression evaluation, with only exception to annotation arguments.
