### ISSUE TITLE
When would KSTypeArgument type be null?

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1161]
The authoritative KSTypeArgument is 
'''
interface KSTypeArgument : KSAnnotated {
    val variance: Variance
    val type: KSTypeReference?
}
'''
But I haven't found its corresponding code, which makes me not know how to handle its null circumstance.

**Comment by neetopia** [comment]
for a star projected type, the type in the argument is considered null, as the actual type need to be checked from the declaration site.

**Comment by WilliamKwokX** [comment]
It's not null in my test. I guess it was modified in some version and that programmer forgot to comment.

**Comment by neetopia** [comment]
currently in KSP, if a type argument comes from a symbol in a library, then yes, even star projected type arguments will have a type, if you check star projected type arguments in source, it should be `null`

**Comment by WilliamKwokX** [comment]
Here is my test code. Wherever I put it, the type reference in the first type argument is never null. Even if there is no class B,  it is not null,  merely the resolved type is error. Could you please test and share your code?
```
lateinit var a: A<*>

class A<T: B>
open class B
```

**Comment by WilliamKwokX** [comment]
I finally find out the reason. In source code, star projected type reference is null from the parent type reference, but is the upper bound from a resolved parent type. I suggest you comment for this situation.
