### ISSUE TITLE
Bug: KSClassDeclaration.isAbstract() returns true when processing Java @interface.

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1178]

**Comment by WilliamKwokX** [comment]
I don't know if this problem is fixed in version 1.8.0, since my android studio and idea always run into endless compilation with kotlin of version 1.7.20.

**Comment by neetopia** [comment]
annotations are interfaces, therefore is abstract.

**Comment by WilliamKwokX** [comment]
But it can't be implemented and is final when processed by kotlin reflection.

**Comment by neetopia** [comment]
This might be a bug with kotlin reflection.

Here is a java interface snippet I compiled locally
```
$ cat A.java
@interface A {
}
```

and here is the corresponding javap result

```
$ javap -v A.class
Classfile /Users/jiaxiang/code/tmp/A.class
  Last modified Nov 8, 2022; size 122 bytes
  MD5 checksum 2cb46f672de7af0800f3180817079aef
  Compiled from "A.java"
interface A extends java.lang.annotation.Annotation
  minor version: 0
  major version: 55
  flags: (0x2600) ACC_INTERFACE, ACC_ABSTRACT, ACC_ANNOTATION
  this_class: #1                          // A
  super_class: #2                         // java/lang/Object
  interfaces: 1, fields: 0, methods: 0, attributes: 1
Constant pool:
  #1 = Class              #6              // A
  #2 = Class              #7              // java/lang/Object
  #3 = Class              #8              // java/lang/annotation/Annotation
  #4 = Utf8               SourceFile
  #5 = Utf8               A.java
  #6 = Utf8               A
  #7 = Utf8               java/lang/Object
  #8 = Utf8               java/lang/annotation/Annotation
{
}
SourceFile: "A.java"
```

as you can see this is mark as abstract and is an interface, therefore the result from KSP matches the class file.

**Comment by WilliamKwokX** [comment]
Here is another problem. Kotlin annotation class is abstract in Java reflection, but final in Kotlin and Ksp(neither open nor abstract).

Besides, Java @interface is both interface and annotation in Java reflection, whereas INTERFACE and ANNOTAION_CLASS are mutually exclusive in Ksp ClassKind. 

I tend to approve Kotlin criteria since setting Java @interface as 'an abstract interface' makes little sense.
