### ISSUE TITLE
Endless compilation

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1181]
One time my Android studio ran into endless compilation, and from then on every project with that version of kotlin jvm plugin is always with endless compilation in both Android studio and Intellij idea. Just now, that bug appeared again with another version of kotlin jvm plugin. Now three versions are invalid and there must be more and more. 

I tried deleting file folders '.android', '.gradle' and '.m2' which didn't help. I doubt this problem is caused by Ksp building since I haven't encountered this problem before I make ksp projects recently. Has someone who is making ksp projects encountered this problem?

**Comment by neetopia** [comment]
it would be great if you can share your project for reproducing the issue.

**Comment by WilliamKwokX** [comment]
https://github.com/WilliamKwokX/Tracer
