### ISSUE TITLE
Change property name from 'type' to 'typeRef' in many Ksp classes

### ISSUE THREAD

**Issue by ApolloKwok** [google/ksp#1191]
In my ksp project code, 'typeRef' refers to KSTypeReference, and 'type' refers to the resolved KSType. It's easily distinguished but disturbed by ```prop.type``` and ```arg.type``` at the first sight. (prop is KSPropertyDeclaration, and  arg is KSTypeArgument)  Therefore, I suggest renaming those properties of type KSTypeReference from ```type``` to ```typeRef```. Function ```getSuperTypes``` can be also renamed ```getSuperTypeRefs```.

**Comment by neetopia** [comment]
Such a name change will be a big breaking change for almost everyone, till we have a more strong reason, I would hold off it.
