### ISSUE TITLE
Let Kotlin plugin disable 'build' button if there is any insolvable problem.

### ISSUE THREAD

**Issue by ApolloKwok** [google/ksp#1193]
For example, 
```
public class A : SuperA()
```
In some other file
```
public class SueprA
```
If 'SuperA' is suddenly not public, 'A' is still valid in Ksp and there may generate some unexpected wrong declarations which would be also hinted at the console, making it hard to find the root cause.  There are also many other examples like 'annotation arguments of wrong types' and 'unknown and not imported references'.

I don't suggest improving KSP checking because they are complicated and time-consuming. Since Kotlin plugin checks problems before 'building', why not let it disable 'build' button directly if there are some unsolvable problems? (Solvable problems are those caused by unknown but imported references)

**Comment by ting-yuan** [comment]
Now that *IDE not indexing generated source* #37 is fixed, is this still an issue?

OTOH, sources are inherently incomplete / not build-able in projects that rely on code generation. In general, KSP won't be able to know whether a reference is valid or not before processors run.

**Comment by ApolloKwok** [comment]
I mean calling help from IDE manufacturers like `JetBrains` to add this feature. Besides, they could also let IDE tell `ksp` the specfic invalid files, or invalid symbols further before processing, making the validation process much less.
