### ISSUE TITLE
Bug: annotated types can't be got by Resolver.getSymbolsWithAnnotation()

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1194]
KSAnnotated.isAnnotationPresent works for that type reference.

**Comment by WilliamKwokX** [comment]
I also suggest adding a property ```val sourceDecl: KSDeclartion``` in KSTypeReference. 'sourceDecl' can be KSClassDeclaration, KSPropertyDeclaration, KSFunctionDeclaration, or KSTypeAlias.

For this proeprty, ```val map: Map<String, Int>```. Those three typeRefs share a 'sourceDecl'(map).

**Comment by manosbatsis** [comment]
Thank you! Same as with https://github.com/google/ksp/issues/1125 for which the repro submitted  [clearly shows](https://github.com/manosbatsis/google-ksp-1125/blob/061a2cb135e76d91efc7ac8163593e2cf94e41da/jvm-ksp-processor-module/src/main/kotlin/jvm/ksp/processor/KspAnnotationProcessor.kt#L23) `resolver.getSymbolsWithAnnotation` (erroneously) returns no results.

**Comment by neetopia** [comment]
as per https://github.com/google/ksp/issues/980#issuecomment-1245928734 , it is more like a limitation with new hmpp model for KMP projects, where KSP is not involved, therefore there is nothing KSP can do to fix it, I would suggest adding another target for your annotation module for now and maybe report to Jetbrains on youtrack regarding no metadata is generated for single target multiple platform projects.
