### ISSUE TITLE
Let KSPLogger.error return Nothing which could be caught background.

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1208]
Type 'Nothing' can help type inference and stop the current Ksp project, which can be caught background and allow other Ksp projects to complete processing in the current round.

**Comment by neetopia** [comment]
`logger.error()` does not necessary mean program will terminate therefore return `Nothing` is not appropriate.

**Comment by WilliamKwokX** [comment]
How about adding an argument `stop: Boolean` in `logger.error()`

**Comment by neetopia** [comment]
If this becomes a more frequent request, we can do that, otherwise, it should be OK for you to add an extension function on your side.
