### ISSUE TITLE
KSPLogger.error does not fail compilation

### ISSUE THREAD

**Issue by yigit** [google/ksp#122]
Calling KSPLogger should fail compilation after processing is done, otherwise, processors don't have a way to gracefully fail compilation.

**Comment by ZacSweers** [comment]
To work around this, I wrap the logger in my own logger that throws a `CompilationErrorException` (which kotlinc looks for and is what Kapt uses)

```kotlin
// TODO temporary until KSP's logger makes errors fail the build
private class FailOnErrorKSPLogger(private val delegate: KSPLogger) : KSPLogger by delegate {
  private val hasErrors = AtomicBoolean(false)
  override fun error(message: String, symbol: KSNode?) {
    delegate.error(message, symbol)
    hasErrors.set(true)
  }

  fun reportErrors() {
    if (hasErrors.get()) {
      throw CompilationErrorException()
    }
  }
}

// Later in my processor
override fun init(
  options: Map<String, String>,
  kotlinVersion: KotlinVersion,
  codeGenerator: CodeGenerator,
  logger: KSPLogger,
) {
  this.logger = FailOnErrorKSPLogger(logger)
}

override fun finish() {
  logger.reportErrors()
}
```

**Comment by yigit** [comment]
I think you should not need this anymore.
At least since we've separated the ksp task from the main compilation.
I even have a test for this in some random branch; https://github.com/yigit/ksp/blob/plugin-tests/gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt#L38

**Comment by ting-yuan** [comment]
Still need a way to allow processors to fail and this seems a reasonable approach?

**Comment by neetopia** [comment]
Actually this start to work now.. Not sure how, potentially upstream fixed some logic around message collector.
