### ISSUE TITLE
incremental building backups generated class file failed

### ISSUE THREAD

**Issue by nanamitouko** [google/ksp#1222]
Using ksp to generate a class，which has a map to collect all the classes with my annotation. And when I built project again without adding/deleting/modifying any classes with my annotation, I encountered a compile error because of the generated class file was deleted but it still exist in the kspCaches dir. And after I set property `ksp.incremental=false`,  everything goes well. So I guess that maybe something goes wrong with the backup logic?

ksp version: 1.5.30-1.0.0

**Comment by WilliamKwokX** [comment]
Why not try another ksp version

**Comment by neetopia** [comment]
agree, 1.0.0 is quite old version, there has been quite a lot fixes into release since then, you should probably try our latest version.

**Comment by nanamitouko** [comment]
> agree, 1.0.0 is quite old version, there has been quite a lot fixes into release since then, you should probably try our latest version.

cuz my ktl version is still 1.5.32, and I've try to upgrade ksp version to 1.6.10-1.0.3, it changes nothing.

**Comment by neetopia** [comment]
can you provide a simple reproduce project so I can try to see if I can upgrade the kotlin language version to latest and see if this problem still exist?

**Comment by ting-yuan** [comment]
Duplicate of #1231
