### ISSUE TITLE
Different alias types may equal

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1226]
```
typealias L<X, Y> = Map<X, Y>
typealias K<A, B> = List<L<A, B>>
```
In this example above, types ```Map<X, Y>``` and ```L<A, B>``` equal, confusing my cache.

**Comment by WilliamKwokX** [comment]
They are converted to different info cached in my ```Map<KSType, Info>```, and share the key.  Though I solved this problem by using another key type, I suggest you make ```KSType.equals``` compare inner elements and provide another function ```equalsWithActualType```.

**Comment by neetopia** [comment]
In type world an alias is fully expanded for equal comparison, even annotations are ignored to some extent, that's how type works.
