### ISSUE TITLE
baseMethod.overrides(childMethod) returns true

### ISSUE THREAD

**Issue by yigit** [google/ksp#123]
Given:
```
interface MyInterface {
  fun foo():Unit
}

class MyClass : MyInterface {
   override fun foo():Unit {}
}
```

calling `resolver.overrides(myInterface.foo, myClass.foo)` returns `true` instead of `false`

This started failing after I moved room from old package name to the new one, I'm guessing it might be related to this change:
https://github.com/google/ksp/commit/a7085afddc82cb83af6ceea99923af13f30a7870

repo case: https://github.com/yigit/ksp/commit/aa08209a18e2e2ee4cb2b8687e9ce5791a36161d

**Comment by neetopia** [comment]
a temporary workaround can be manually checking class hierarchy before calling `overrides`
