### ISSUE TITLE
Expose simple names on a missing types's synthetic declaration

### ISSUE THREAD

**Issue by danysantiago** [google/ksp#1232]
In javac, an `ErrorType` is a `DeclaredType` and one can get an `Element` out of it. Its `simpleName` will be the name as it was defined in the sources.

But in KSP, the `KSDeclaration` of a an error `KSType` is a synthetic declaration (specifically that `KSErrorTypeClassDeclaration` singleton) and its simple name is always `<Error>`.

This would be very helpful for reporting to the user nice traces to the missing type:
```
package test

import bar.MissingType;

class TestClass {
  fun foo(missing: MissingType) = TODO()
}
```
```
Validation trace:
    => element (CLASS): test.TestClass
    => element (METHOD): foo(MissingType)
    => type (EXECUTABLE method): (MissingType)void
    => type (ERROR parameter type): MissingType
```
Note that if the type is qualified in the source, it will be similarly be reported as its 'simple name' in javac:
```
 fun foo(missing: bar.MissingType) = TODO()
```
```
    => type (ERROR parameter type): bar.MissingType
```

**Comment by kuanyingchou** [comment]
Just to add that javac/kapt keeps the original referenced names and not just simple names, for example, with:

```
class Foo {
    fun barQualified(missing: bar.MissingType) = TODO()
}
```
We can get "bar.MissingType" in javac/kapt.
