### ISSUE TITLE
How could I judge a FunctionDeclaration contains static modifier whatever it is Java/Kotlin?

### ISSUE THREAD

**Issue by NightXlt** [google/ksp#1241]
I have tried to write code like this:

```kotlin
    private fun isStaticFunction(funtionDeclation: KSFunctionDeclaration) =
        (funtionDeclation.functionKind == FunctionKind.STATIC
                || funtionDeclation.modifiers.contains(Modifier.JAVA_STATIC)
                || funtionDeclation.annotations.any { JvmStatic::class.java.simpleName == it.shortName.getShortName() })

```
I'm not sure is it correct way to think it is static function, because I hope to cover all condition of static modifier.

Thank you very much for your prompt response.

**Comment by neetopia** [comment]
you don't need the last one, last one is to indicate the static function will have an additional function generated so that it can be invoked in Java without name mangling as if it is a normal java static function. By removing the last condition check this function lgtm.
