### ISSUE TITLE
How to debug with break point and coverage in android studio?

### ISSUE THREAD

**Issue by ApolloKwok** [google/ksp#1244]
These middle 3 buttons 
<img width="182" alt="image" src="https://user-images.githubusercontent.com/57835556/207906214-4d2da96b-6635-4323-9c46-d00527e185d0.png">
and code coverage setting in `edit configuration` window are invalid when building ksp projects.
<img width="1040" alt="ADC6FCE8-6BB3-47BF-A311-374D78683EE1" src="https://user-images.githubusercontent.com/57835556/207906554-d646c0fb-ffa3-4063-89de-ab593fa0ac90.png">

**Comment by ting-yuan** [comment]
Debugging processors needs a bit more effort, as they are part of the compilation. Please find the following links for more info.

Duplicated of #31. Related to #1207
