### ISSUE TITLE
How get property Delegate

### ISSUE THREAD

**Issue by yizems** [google/ksp#1249]
```kotlin
    var a: Int? by SavedDelegates.nullable { 10 }

    var b: String? by SavedDelegates.nullable { "hahha" }

    var c: Boolean? by SavedDelegates.nullable { false }
```

![image](https://user-images.githubusercontent.com/16949474/208872414-a27901bd-f454-4775-859e-3745898b290e.png)

I cant use that
![image](https://user-images.githubusercontent.com/16949474/208872315-fb063a8c-3e83-4c3d-a7db-5224f1fb095a.png)

**Comment by neetopia** [comment]
can you clarify what information you are looking from delegation? from the code snippet you are printing the property and if the property is a delegation. If you are looking for the actual delegation content, then unfortunately KSP does not support this.

**Comment by yizems** [comment]
@neetopia If I want to find an agent class, can I do it?

**Comment by neetopia** [comment]
unfortunately, it is not possible within KSP.

**Comment by yizems** [comment]
alright, thx

**Comment by hsavaliya** [comment]
Is this still not possible to get actual delegation content?

**Comment by hsavaliya** [comment]
@neetopia  any alternate solution to get delegation content?
