### ISSUE TITLE
KSType assignability between java string and kotlin string returns false

### ISSUE THREAD

**Issue by yigit** [google/ksp#125]
```
val javaString = resolver.getClassDeclarationByName("java.lang.String")!!.asStarProjectedType()
val kotlinString = resolver.getClassDeclarationByName("kotlin.String")!!.asStarProjectedType()
println(javaString.isAssignableFrom(kotlinString).toString())
println(kotlinString.isAssignableFrom(javaString).toString())
```
this prints `false` `false` instead of `true` `true`.

I'm not yet sure why [this test](https://github.com/google/ksp/blob/master/compiler-plugin/testData/api/javaTypes.kt) does not catch it though :/. Maybe `getClassDeclarationByName` has a different resolution path ?

**Comment by ting-yuan** [comment]
This is intended. `java.lang.String` is [mapped](https://kotlinlang.org/docs/reference/java-interop.html#mapped-types) to `kotlin.String!` when written in Kotlin source. We didn't perform the mapping in `getClassDeclarationByName`, so that it's possible to get the original class.

**Comment by neetopia** [comment]
Close this issue for now as we have a discussion thread going on in #126
