### ISSUE TITLE
Releasing a processor - which KSP version

### ISSUE THREAD

**Issue by Dutch-0** [google/ksp#1260]
If I would like to release a processor through mavenrepository, which KSP-Version should I target. Or better, how can I make sure that my processor would work for almost everyone? How should my `build.gradle.kts` for my processor look like, and how the `build.gradle.kts` for the consumer?

**Comment by WilliamKwokX** [comment]
There are some ksp projcet samples you can refer to on Github.

**Comment by Dutch-0** [comment]
Bummer, that is what I feared. Thank you

**Comment by WilliamKwokX** [comment]
`Kotlin Symbol Processing API` seems always compatible with lower versions. And I plan to release my `ksp library` of only 1 version with 'ksp 1.8.0-1.0.8`.

**Comment by Dutch-0** [comment]
Thank you for the update 👍 
Planning to the same, but for multiple Kotlin version: `KotlinVersion-MyLibraryVersion`. 
Probably only for the latest 5 Kotlin versions
