### ISSUE TITLE
Incremental update problem

### ISSUE THREAD

**Issue by wumeixinjiazu** [google/ksp#1295]
When I modified the code in Android Studio, the code was not regenerated due to the increment of KSP. At present, I can only turn off the increment update of KSP to run the code properly

ksp.incremental=false

**Comment by wumeixinjiazu** [comment]
I changed the build file code to look like this so I didn't seem to set incremental=false. Why
     val generator =   FileSpec.builder(packageName, className)
                .addType(classBuilder.build())
                .build()     
 val file = codeGenerator.createNewFile(
                dependencies = Dependencies.ALL_FILES,
                packageName = packageName,
                fileName = className
            )
            file.write(generateFile.toString().toByteArray())
            file.close()
The previous error code
            generateFile.writeTo(codeGenerator, false)

**Comment by neetopia** [comment]
looks like the cause is you did not specify dependencies for your generated file therefore incremental fails, your new code looks right to me.
