### ISSUE TITLE
`T & Any ` can't be checked out in resovled arguments or library code in version 1.8.0-1.0.9

### ISSUE THREAD

**Issue by ApolloKwok** [google/ksp#1307]
It is never checked out in library code.

For these source code: 
```
class DefNotNull<T> {
    val d: DefNotNull<T & Any> = TODO()
}
```
Test 
```
val typeRef = klass.getDeclaredProperties().first().type

// right before being resolved
typeRef.element!!.typeArguments.first().type!!.element!!.javaClass 
// log:  class com.google.devtools.ksp.symbol.impl.kotlin.KSDefNonNullReferenceImpl

// wrong
typeRef.resolve().arguments.first().type!!.element!!.javaClass 
// log: class com.google.devtools.ksp.symbol.impl.binary.KSClassifierReferenceDescriptorImpl
```

**Comment by ApolloKwok** [comment]
The element's `javaclass` is `class com.google.devtools.ksp.symbol.impl.binary.KSClassifierReferenceDescriptorImpl`

**Comment by ApolloKwok** [comment]
Besides, I suggest testing both `library code` and `src code` every time.

**Comment by neetopia** [comment]
The information is not retrievable from library, when compiled, definitely non null type gets converted into normal type with `NonNull` annotation, there is no way to tell whether it was definitely non null types prior to compilation. We might support it if the information gets added into metadata in future.

**Comment by ApolloKwok** [comment]
The info `NonNull` annotation could be used, telling that `KSReferenceElement` should be created with `KSDefNonNullReferenceImpl`.

**Comment by neetopia** [comment]
There is no way to distinguish between a normal type with explicit `NonNull` annotation and a definitely non null type after being compiled

**Comment by ApolloKwok** [comment]
Well, the process of resolving types like `List<T & Any>` in source code still needs fixed.

**Comment by ApolloKwok** [comment]
And I suggest you comment for this problem on `KSDefNotNullReference`.

**Comment by ApolloKwok** [comment]
For `typeRef` `List<T & Any>` in source code, whether it's implicit or not, `typeRef.resolve().arguments.first().type!!.element` is `KSClassifierReference` even in version `1.8.0-1.0.9`. Could you open this issue?
