### ISSUE TITLE
cannot read annotatations in classes that are coming from dependencies

### ISSUE THREAD

**Issue by yigit** [google/ksp#131]
Some annotations in classes that are coming from dependencies are not visible.

I have a project setup where there is a base module and a main module (which depends on baseModule)
Both of these declare a dependency on `androidx.room:room-common` which has an annotation.

There is an identical class in each module. When ksp is run on the main module, it cannot read the annotation from Room on the `baseModule`'s class.
Interestingly though, if i create another common module which has the annotation, then it works fine.

I'm attaching a project that reproduces the problem.

[ksp-dependency-annotation-repro.zip](https://github.com/google/ksp/files/5448724/ksp-dependency-annotation-repro.zip)

**Comment by yigit** [comment]
actually, it is not related to coming from a prebuilt dependency nor java.
It breaks if the annotation has a target. 

So if I have an annotation like:
```
@Target(AnnotationTarget.FIELD)
annotation class TestAnnotation
```

it is not visible when put on my dependencies.

**Comment by yigit** [comment]
a bit more debug information.
When this property is parsed from a jar, it goes through deserialization and finally resolved in this code:

https://github.com/JetBrains/kotlin/blob/master/core/descriptors.jvm/src/org/jetbrains/kotlin/load/kotlin/AbstractBinaryClassAnnotationAndConstantLoader.kt#L117

There it tries to get the signature for the property, which returns null hence it quits w/o reading.

If I debug KSDeclarationDescriptorImpl and put a break point into [this line](https://github.com/google/ksp/blob/master/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSDeclarationDescriptorImpl.kt#L39), the debug information for the descriptor does actually show the annotations with proper targets:
```
descriptor.toString()
@field:TestAnnotation @field:JavaTestAnnotation public final val target: kotlin.Int defined in ClassFromDependency[DeserializedPropertyDescriptor@4d77c2c5]
```

So we can probably write a visitor to get this information but might also be a kotlinc bug (unless i'm missing something and it works fine in kapt by mistake) :/.

**Comment by yigit** [comment]
here is a hacky solution that fixes the problem:
https://github.com/yigit/ksp/commit/c2755bc483733f382be83d9bd580100ecb69ead2

i think we need a solution similar to this. We cannot trust the annotations field in desrialized property (`DeclarationDescriptor`) because it means just the annotations on the property, ignores or targeted annotations. As we don't check setters/getters/backing fields; we'll miss them.

Lmk what you think. Also, I couldn't figure out how to create a test for this :(

**Comment by yigit** [comment]
Some more information here.
Another discrepancy I noticed is that, if a kotlin class comes from a dependency, KSP reports slightly different structures for them.
For instance, for the following class:

```
class KotlinClass {
    @NoTargetAnnotation("onProp")
    @FieldTarget("onProp")
    @PropertyTarget("onProp")
    @set:PropertySetterTarget("onProp-setter")
    @get:PropertyGetterTarget("onProp-getter")
    var prop : String = ""
}
```

If I traverse and print the same class coming from a library dependency vs source code here is what it prints:

annotation definitions:
```
package annotations;
annotation class NoTargetAnnotation(val value:String)
@Target(AnnotationTarget.FIELD)
annotation class FieldTarget(val value:String)
@Target(AnnotationTarget.PROPERTY)
annotation class PropertyTarget(val value:String)
@Target(AnnotationTarget.PROPERTY_SETTER)
annotation class PropertySetterTarget(val value:String)
@Target(AnnotationTarget.PROPERTY_GETTER)
annotation class PropertyGetterTarget(val value:String)
@Target(AnnotationTarget.CLASS)
annotation class ClassTarget(val value:String)
```

dependency (.class file from compiled kt file):
```
lib.KotlinClass :com.google.devtools.ksp.symbol.impl.binary.KSClassDeclarationDescriptorImpl
-> annotations.NoTargetAnnotation{[value = onClass]}
getprop :com.google.devtools.ksp.symbol.impl.binary.KSPropertyDeclarationDescriptorImpl :com.google.devtools.ksp.symbol.impl.binary.KSPropertyGetterDescriptorImpl
-> annotations.PropertyGetterTarget{[value = onProp-getter]}
setprop :com.google.devtools.ksp.symbol.impl.binary.KSPropertyDeclarationDescriptorImpl :com.google.devtools.ksp.symbol.impl.binary.KSPropertySetterDescriptorImpl
-> annotations.PropertySetterTarget{[value = onProp-setter]}
prop :com.google.devtools.ksp.symbol.impl.binary.KSPropertyDeclarationDescriptorImpl
-> annotations.NoTargetAnnotation{[value = onProp]}
-> annotations.PropertyTarget{[value = onProp]}
```
source: (kt file in current compilation)
```
main.KotlinClass :com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl
-> annotations.NoTargetAnnotation{[value = onClass]}
prop :com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl
-> annotations.NoTargetAnnotation{[value = onProp]}
-> annotations.FieldTarget{[value = onProp]}
-> annotations.PropertyTarget{[value = onProp]}
-> annotations.PropertySetterTarget{[value = onProp-setter]}
-> annotations.PropertyGetterTarget{[value = onProp-getter]}
```

Notice that, when the property comes from a pre-compiled code, we generate the setter and getter (`KSPropertySetterDescriptorImpl, KSPropertyGetterDescriptorImpl`) with annotation but not when it is in source (the setter/getter generated when code is in source does not have any annotations).

Now clearly the `FieldTarget` annotation is missing and could probably be rolled into the property to fix this particlar issue.

On the other hand though, should KSP stop returning annotations in Getter/Setter descriptors and roll them back into the property? Or alternatively, should we move the annotations in the property to the setter/getter?
In either case, it would be much better if it was consistent whether the target code comes from a kotlin source file or kotlin .class file.

For reference, here is the visitor:

```
class AnnotationVisitor : KSTopDownVisitor<MutableMap<KSAnnotated, List<KSAnnotation>>, Unit>() {
        override fun defaultHandler(node: KSNode, data: MutableMap<KSAnnotated, List<KSAnnotation>>) {

        }

        override fun visitAnnotated(annotated: KSAnnotated, data: MutableMap<KSAnnotated, List<KSAnnotation>>) {
            if (annotated.annotations.isNotEmpty()) {
                data[annotated] = annotated.annotations
            }
            super.visitAnnotated(annotated, data)
        }

        override fun visitTypeReference(typeReference: KSTypeReference, data: MutableMap<KSAnnotated, List<KSAnnotation>>) {
            // don't traverse type references
        }
    }
```

**Comment by ting-yuan** [comment]
Closing as the behavior now is aligned to class files / descriptors. Please reopen if there's any case missing.
