### ISSUE TITLE
BuildConfig.VALUE in Annotation parameter String concatenation can't be readed in symbol processor

### ISSUE THREAD

**Issue by richard-hgs** [google/ksp#1323]
If i try to use an annotation like below:

interface DaoInterface {
@ Query("SELECT * FROM my_table WHERE name = '${BuildConfig.NAME}' ")
func myFunc()
}

The KSFunctionDeclaration annotation parameters become empty.

So we can't read the annotation string parameter because the annotation parameters become empty in this situation.

**Comment by neetopia** [comment]
Is this a room processor use case? If so can you try to reach out to Room's issue tracker for better visibility?

**Comment by richard-hgs** [comment]
Thanks, i fixed the issue. The thing is that the build config variables should be used programmatically because at build time they aren't generated yet.

@ Query("SELECT * FROM my_table WHERE name = ':name' ")
func myFunc(name: String)

myFunc(BuildConfig.NAME)

That is it!
