### ISSUE TITLE
Model hidden `KSReferenceElement`

### ISSUE THREAD

**Issue by ApolloKwok** [google/ksp#1327]
For property `val x = listOf(1)` with the hidden type in source code, its `type reference` is logged out `List<Int>` whereas the behind `element` is `null`. Since the `type reference` is logged out correctly, I think its `element` is not difficult to model from `KtType`.

**Comment by neetopia** [comment]
`ReferenceElement` in general is the source representation of the referenced type part of a type reference, this is by design to have `null` for implicit types (i.e. types obtained from type inference).
