### ISSUE TITLE
Default (array) annotation members values are not readable

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#134]
Given this annotation:

```kotlin
@Target(CLASS)
@Retention(RUNTIME)
public annotation class TypeLabel(val label: String, val alternateLabels: Array<String> = [])
```

if I use it like so:

```kotlin
@TypeLabel("a")
class Test
```

The value for `alternateLabels` is null rather than the empty array when reading

![image](https://user-images.githubusercontent.com/1361086/97646464-24002200-1a26-11eb-99d2-cc5c1221e845.png)

**Comment by neetopia** [comment]
This is a known issue #53 , for now a workaround is to bundle your kotlin annotation with the processor in same module.

**Comment by ZacSweers** [comment]
Ahh oops I missed that one
