### ISSUE TITLE
Request: sample of room using Gradle (Groovy) and KSP for Room dependency

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ksp#1343]
I have this:

```
    def room_version = '2.5.0'

    kapt "androidx.room:room-compiler:$room_version"
```

There is a document explaining how to migrate to KSP from this:

https://developer.android.com/studio/build/migrate-to-ksp#groovy

I tried it but it didn't work (shows that some generated functions don't exist properly). Perhaps I'm putting things in the wrong place, such as this one:

```
plugins {
    id 'com.google.devtools.ksp' version '1.8.10-1.0.9' apply false
}
```

Can you please provide a tiny sample to show how to do it?

Also, I have this, but I don't see a mention of what to replace it with:

```
    defaultConfig {
...
        kapt {
            arguments {
                arg("room.schemaLocation", "$projectDir/schemas")
            }
        }
...
    }
```

**Comment by neetopia** [comment]
For `Room` related questions, it's better to file bugs in Room's issue tracker.

**Comment by AndroidDeveloperLB** [comment]
@neetopia Such a thing exists? 
And yet for Play policy issues there is nobody to talk to...
:(

**Comment by AndroidDeveloperLB** [comment]
@neetopia Anyway here:
https://issuetracker.google.com/issues/272576538
