### ISSUE TITLE
Resolver.getSymbolsWithAnnotation() skips local Java classes

### ISSUE THREAD

**Issue by bubenheimer** [google/ksp#1345]
`Resolver.getSymbolsWithAnnotation(..., inDepth = true)` skips local Java classes. It only finds local Kotlin classes. To demonstrate I've added the following at the bottom of [annotatedUtil.kt](../blob/main/test-utils/testData/api/annotatedUtil.kt). In the diff of the failing test you will see that the local Kotlin class was processed, but not the local Java class:

```
// FILE: KotlinClass.kt
import com.google.devtools.ksp.processor.Test

@Test
class KotlinClass {
    fun kotlinfun() {
        @Test
        class LocalKotlinClass
    }
}

// FILE: JavaClass.java
import com.google.devtools.ksp.processor.Test

@Test
class JavaClass {
    void javafun() {
        @Test
        class LocalJavaClass {}
    }
}
```

I tried making all the Java symbols public, but it makes no difference.

**Comment by neetopia** [comment]
This probably will not be supported, in Java annotation processing, local declarations are already ignored, and KSP offering Java support for compatibility, we should not be doing more than what Java AP is already doing.

**Comment by bubenheimer** [comment]
Shouldn't this go in documentation somewhere? Right now I would have to know all about Java annotation processing to take an informed guess that possibly KSP treats local Java classes the same way that Java annnotation processors do.

**Comment by neetopia** [comment]
It's a good suggestion, historically the area of Java interop has been very subtle, I will try to make specifying Java interop behaviors as one of our next mid term goal.
