### ISSUE TITLE
Should annotation Array members use Array in KSP?

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#135]
Right now, annotation members with `Array` members are represented by a `List` in the KSP API when reading them from a `KSAnnotation`. Should these be represented as `Array` in the API too? I ran into confusion around this because while casting the untyped `value` of the member I expected it to be an `Array` like the underlying type.

**Comment by neetopia** [comment]
With #142 merged it should be parsed as Array now.

**Comment by neetopia** [comment]
Actually still need some work to support array member for kotlin source. Will address it in next release.

**Comment by neetopia** [comment]
I take previous comment back, it was fixed with last release.
