### ISSUE TITLE
Generated classes are incomplete in Android Studio

### ISSUE THREAD

**Issue by javierpe** [google/ksp#1354]
Hi, Im working with KSP to generate Hilt modules to avoid boilerplate code but when I run the app from toolbar this generated classes are incomplete and when I run from command line this works fine. Im new in KSP!

**Comment by hunglvv** [comment]
Hilt is not yet supported from the [KSP Docs](https://kotlinlang.org/docs/ksp-overview.html#supported-libraries)

**Comment by javierpe** [comment]
Works fine with incremental flag
