### ISSUE TITLE
Android configuration

### ISSUE THREAD

**Issue by ApolloKwok** [google/ksp#1357]
To make IDE aware of generated ksp code before 1.8.0-1.0.9 on Android, several websites gave the configuration below.
Application module:
```
applicationVariants.all { variant ->
    kotlin.sourceSets {
        def name = variant.name
        getByName(name) {
            kotlin.srcDir("$buildDir/generated/ksp/$name/kotlin")
        }
    }
}
```
Library module:
```
libraryVariants.all { variant ->
    kotlin.sourceSets {
        def name = variant.name
        getByName(name) {
            kotlin.srcDir("$buildDir/generated/ksp/$name/kotlin")
        }
    }
}
```

However, that is different from the official website, and may cause `conflicting declarations`.
```
kotlin {
    sourceSets.main {
        kotlin.srcDir("build/generated/ksp/main/kotlin")
    }
    sourceSets.test {
        kotlin.srcDir("build/generated/ksp/test/kotlin")
    }
```

Which should I choose?

**Comment by neetopia** [comment]
Android is different from general projects due to variants, you should be fine with whatever works for you.

**Comment by ApolloKwok** [comment]
I found this is applicable in both my Android and general projects. 
```
kotlin.sourceSets.configureEach {
    kotlin.srcDir("$buildDir/generated/ksp/$name/kotlin/")
}
```
However, is there any hidden problem?  I am writing tutorials and want that works for everybody.

**Comment by neetopia** [comment]
Looks good to me. Also please note that in latest KSP it should no longer be needed to do so in order for IDE to index.
