### ISSUE TITLE
How can I access class property assignment node?

### ISSUE THREAD

**Issue by IlyaGulya** [google/ksp#136]
Hi!
I have such source code:
```
object A: BaseClass() {
  val field = customFieldValue()
}
```

Is it possible to access something like `KSFieldAssignment` so I can see what is being assigned to field and how exactly value is constructed?

**Comment by neetopia** [comment]
We do not plan to support such level of access in KSP. The best you can get is the type of `field` which is inferred from the expression.

**Comment by IlyaGulya** [comment]
That's pity :)
Ok, thanks for response!
