### ISSUE TITLE
The workaround apparently is outdated. The metadata task and configuration apparently has a new name. This is currently solution that I found for Kotlin 1.8.10 + (maybe is the same for older versions)

### ISSUE THREAD

**Issue by bob1199** [google/ksp#1365]
The workaround apparently is outdated. The metadata task and configuration apparently has a new name. This is currently solution that I found for Kotlin 1.8.10 + (maybe is the same for older versions)

```
dependencies  {
  add("kspCommonMainMetadata", your-ksp-dependency)
}

tasks.withType<org.jetbrains.kotlin.gradle.dsl.KotlinCompile<*>>().all {
    if(name != "kspCommonMainKotlinMetadata") {
        dependsOn("kspCommonMainKotlinMetadata")
    }
}

kotlin.sourceSets.commonMain {
    kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")
}
```

_Originally posted by @DevSrSouza in https://github.com/google/ksp/issues/567#issuecomment-1510477456_

**Comment by neetopia** [comment]
Looks like this has been [fixed](https://github.com/JetBrains/kotlin-web-site/commit/b787fd6da5522fb8c576d82c3e805766dc4fb72d) in the official document and we can close this issue as completed.
