### ISSUE TITLE
The Kotlin/Native unit tests fail to build: An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.jvm']

### ISSUE THREAD

**Issue by qiaoyuang** [google/ksp#1377]
HI, I try to upgrade version  of Kotlin (1.7.20 -> 1.8.20) and version of KSP (1.7.20-1.0.8 -> 1.8.20-1.0.11) on my Kotlin Multiplatform project, and when I execute the unit tests of `macosX64` I get a build error:

```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.jvm']
> Failed to apply plugin 'org.jetbrains.kotlin.jvm'.
   > Gradle#projectsEvaluated(Action) on build 'SQLlin' cannot be executed in the current context.
```
The detail is here: https://github.com/qiaoyuang/SQLlin/actions/runs/4902155422/jobs/8753830437

The way that I execute the unit tests:

```
./gradlew :sqllin-dsl:cleanMacosX64Test
./gradlew :sqllin-dsl:macosX64Test --stacktrace
```

You can get the upgraded code here: https://github.com/qiaoyuang/SQLlin
And you can get the code that haven't upgraded here: https://github.com/ctripcorp/SQLlin

Can you tell me how can I fix this problem, Please.

**Comment by neetopia** [comment]
Can you try remove KSP to see if this issue is related to KSP? From the error message itself it looks to be unrelated to KSP.

**Comment by qiaoyuang** [comment]
Yes, If I remove KSP, the problem will disappear. I tried to debug the build process, I found the exception was thrown when KSP  resolve the `processorClasspath`.

The exception is thrown at here:

![11684395585_ pic](https://github.com/google/ksp/assets/20186724/bbf65c1c-5751-4667-bef1-73a2166bcd1d)

And, It looks like found the plugin, but can't apply:

![21684395595_ pic](https://github.com/google/ksp/assets/20186724/43ded955-00f3-4af0-9cae-6cb73daac3a5)



> Can you try remove KSP to see if this issue is related to KSP? From the error message itself it looks to be unrelated to KSP.

**Comment by qiaoyuang** [comment]
I remove the `org.gradle.configureondemand=true` from `gradle.properties`, everything would be OK. It's working now.
