### ISSUE TITLE
1.9.0-Beta does not respect KGP's new project-level compiler options

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#1387]
KGP in kotlin 1.9.0-Beta adds a new project extension option for compilerOptions, but KSP's kotlin tasks do not use these as a convention for its KspTaskJvm inputs.

See: https://youtrack.jetbrains.com/issue/KT-57159

**Comment by neetopia** [comment]
Can you give me an example where this is not working? I am unsure if the issue is related to project-level compiler options or existing issue exposed by trying out project-level options.

**Comment by ZacSweers** [comment]
In the issue I linked above, they added a new project-level DSL for compiler options and these should be used as the `convention`s for KotlinCompile inputs. It's easy to reproduce in any project using Kotlin 1.9.0-Beta and KSP if you set a compilerOption in the project extension and confirm the `KspTaskJvm` input doesn't use it

**Comment by ZacSweers** [comment]
You can reproduce it in [this branch](https://github.com/slackhq/slack-gradle-plugin/pull/364) by commenting [this line](https://github.com/slackhq/slack-gradle-plugin/blob/6735fe8f6779afc3ef0920d6aa06bd8e65e24b4c/build.gradle.kts#L215) and running `./gradlew compileKotlin`

**Comment by ZacSweers** [comment]
Here's a simpler repro: https://github.com/slackhq/EitherNet/pull/61

**Comment by hfhbd** [comment]
AFAIK you also need to use Gradle 8 and not the default jvm target, but for example 11:
`compileJava task (current target is 11) and kspKotlin (current target is 1.8, the Kotlin default one) jvm target compatibility should be set to the same version`. This warning was promoted to an error starting with Gradle 8.

**Comment by ZacSweers** [comment]
@hfhbd the crux of the issue is that KSP should reuse the project extension values as conventions like the other tasks. Gradle's correctly pointing out the discrepancy in this case, albeit in a tangential way.

**Comment by hfhbd** [comment]
Absolutely. I just wanted to mention it for a proper test setup.

**Comment by javichaques** [comment]
Hi, I have the same issue. @ZacSweers could you solve it?

**Comment by neetopia** [comment]
The issue is not a 1.9.0-Beta issue, but rather an existing issue where KSP Gradle plugin does not carry over certain properties from the corresponding kotlin compile task. A quick fix on our side would be to manually copy the properties.

**Comment by neetopia** [comment]
Another interesting finding is that I can't reproduce this issue on our main branch where the compiler version has been upgraded to 1.9.20-dev.* version, it appears that the issue is only reproducible on 1.9.0-Beta.
