### ISSUE TITLE
number of loaded files in snapshot differs transforms-3

### ISSUE THREAD

**Issue by instancer-kirik** [google/ksp#1405]
number of loaded files in snapshot differs kapt and ksp... caches\transforms-3\c516e80ab6aa3829b9b4a8a24dd46bd8\transformed\output.bin at org.jetbrains.kotlin.gradle.internal.kapt.incremental.ClasspathSnapshot.diff(ClasspathSnapshot.kt:81) at com.google.devtools.ksp.gradle.KspSubpluginKt.findClasspathChanges(KspSubplugin.kt:688) at com.google.devtools.ksp.gradle.KspSubpluginKt$createIncrementalChangesTransformer$1.invoke(KspSubplugin.kt:748) at com.google.devtools.ksp.gradle.KspSubpluginKt$createIncrementalChangesTransformer$1.invoke(KspSubplugin.kt:740) at com.google.devtools.ksp.gradle.KspTaskJvm.callCompilerAsync$kotlin_gradle_plugin_common(KotlinFactories.kt:185) at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin_common(Tasks.kt:530) at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.executeImpl(Tasks.kt:449) at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:412)

I cleaned, invalidated caches, deleted caches/transforms-3, but it got stuck at 5 sec remaining 0bytes left.. clicked x, deleted folder. error on startup and build

`
plugins{
id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.gms.google-services'
    id 'dagger.hilt.android.plugin'
    id 'kotlinx-serialization'
 id 'com.google.devtools.ksp' version '1.8.20-1.0.10'//'1.7.0-1.0.6'
id 'kotlin-parcelize'
}
kotlin{

    sourceSets{
        debug{
            kotlin.srcDir("build/generated/ksp/debug/kotlin")

        }
        release{
            kotlin.srcDir("build/generated/ksp/release/kotlin")
        }
    }
    sourceSets.debug {
        kotlin.srcDirs += 'build/generated/ksp/debug/kotlin'
    }
    sourceSets.release {
        kotlin.srcDirs += 'build/generated/ksp/release/kotlin'
    }
}
composeOptions {
        kotlinCompilerExtensionVersion = "1.4.5"
    }
kapt {
        correctErrorTypes true
        //incremental.apt = false
    }
applicationVariants.all {
        kotlin.sourceSets {
            getByName(name) {
                kotlin.srcDir("build/generated/ksp/$name/kotlin")
            }
        }
    }
}
dependencies {
    implementation platform('androidx.compose:compose-bom:2023.05.01')
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation "androidx.compose.ui:ui"
    implementation ("androidx.compose.material:material"){
        version{
            strictly '1.3.1' // this is done to fix the dumb internal sheetstate values refactor
        }
    }
    implementation 'net.openid:appauth:0.11.1'
    //implementation project(":ksp")
    //implementation 'com.google.android.gms:auth-api-impl:11.6.0'
    //ksp project(":ksp")
    implementation "androidx.compose.ui:ui-tooling-preview"
    implementation "androidx.compose.foundation:foundation"
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.4.3'
//HTTP
    implementation 'com.squareup.okhttp3:okhttp:5.0.0-alpha.11'
    debugImplementation "androidx.compose.ui:ui-tooling"
    implementation 'androidx.activity:activity-compose:1.7.2'

    implementation "androidx.compose.material:material-icons-extended"
  
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.9.42-beta'
    implementation 'io.github.raamcosta.compose-destinations:core:1.9.42-beta'
// Paging 3.0
    implementation 'androidx.paging:paging-compose:1.0.0-alpha20'
    implementation 'androidx.room:room-paging:2.5.1'
    //hilt
    implementation 'androidx.hilt:hilt-navigation-compose:1.0.0'
    implementation 'com.google.dagger:hilt-android:2.46.1'
    kapt 'com.google.dagger:hilt-compiler:2.46.1'

    implementation 'androidx.fragment:fragment-ktx:1.5.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:$coroutines_version"

  
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
   

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'com.github.bumptech.glide:glide:4.15.1'
    ksp 'com.github.bumptech.glide:compiler:4.15.1'

    implementation "androidx.room:room-ktx:$room_version"

    ksp "androidx.room:room-compiler:$room_version"

    //Pager
    implementation 'com.google.accompanist:accompanist-pager:0.30.0'
    implementation 'com.google.accompanist:accompanist-pager-indicators:0.30.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    implementation 'com.google.accompanist:accompanist-systemuicontroller:0.30.0'
    testImplementation "androidx.room:room-testing:$room_version"

    implementation 'androidx.navigation:navigation-fragment-ktx:2.5.3'
    implementation 'androidx.navigation:navigation-ui-ktx:2.5.3'

//coil
    implementation "io.coil-kt:coil:$coil_version"
    implementation "io.coil-kt:coil-gif:$coil_version"
    implementation "io.coil-kt:coil-video:$coil_version"
    implementation "io.coil-kt:coil-compose:$coil_version"

//ROOM
    implementation 'androidx.room:room-runtime:2.5.1'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1'

    implementation('com.squareup.moshi:moshi:1.15.0')
    ksp('com.squareup.moshi:moshi-kotlin-codegen:1.15.0')
    implementation('com.squareup.moshi:moshi-kotlin:1.15.0')
    implementation('com.google.devtools.ksp:symbol-processing-api:1.9.0-Beta-1.0.11')//1.7.21-1.0.8'
    implementation 'com.github.SmartToolFactory:Compose-Color-Picker-Bundle:1.0.1'

    implementation "com.surrealdb:surrealdb-driver:${surrealdbVersion}"
    implementation 'org.java-websocket:Java-WebSocket:1.5.3'
    implementation "io.ktor:ktor-client-auth:$ktor_version"
    implementation "io.ktor:ktor-client-core:$ktor_version"
    implementation "io.ktor:ktor-client-logging:$ktor_version"
    implementation "io.ktor:ktor-client-android:$ktor_version"
    implementation("io.ktor:ktor-client-serialization:$ktor_version")
    implementation("io.ktor:ktor-client-cio:$ktor_version")
    implementation("io.ktor:ktor-client-content-negotiation:$ktor_version")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktor_version")

`

now it built if I clean first, while making this post q.q

**Comment by neetopia** [comment]
This should have been fixed by #1437
