### ISSUE TITLE
Kotlin 1.8.22 has been released, please support

### ISSUE THREAD

**Issue by ianbrandt** [google/ksp#1406]
[Kotlin 1.8.22](https://github.com/JetBrains/kotlin/releases/tag/v1.8.22) seems to resolve autonomousapps/dependency-analysis-android-gradle-plugin#884. A KSP release for 1.8.22 would be greatly appreciated.

**Comment by ianbrandt** [comment]
ksp-1.8.21-1.0.11 does seem to work okay with Kotlin 1.8.22 in my project, albeit with repeated warnings:

```text
ksp-1.8.21-1.0.11 is too old for kotlin-1.8.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.21.
```

**Comment by neetopia** [comment]
It should work, I will do a release today for 1.8.22, in the meantime, using 1.8.21-1.0.11 should not be a big issue.

**Comment by neetopia** [comment]
Done

**Comment by ianbrandt** [comment]
Thanks!
