### ISSUE TITLE
Default class value is incorrectly parsed as PsiImmediateClassType

### ISSUE THREAD

**Issue by wanyingd1996** [google/ksp#1408]
Hi all, I ran in to a problem where the default annotation value is supposed to be serialized as KsType, but it is returning a value as PsiImmediateClassType.

I'm processing the following annotation.
```
public @interface TestAnnotation {
  Class<?> value() default Object.class;
}
```
When I access the annotation's annotation value via KSAnnotation. arguments[0].value and trying to cast it as KSType, I'm getting a class cast error. This only happens when I'm directly using annotation like @TestAnnotation. But If I specify @TestAnnotation(Object::class), then I can get the value as KsType. 

Is this intended behavior or a bug?

**Comment by neetopia** [comment]
Default value might be tricky to handle as they work in different pipelines, looks lie a bug to me.
