### ISSUE TITLE
KSP cannot be compiled

### ISSUE THREAD

**Issue by tomKitty888888** [google/ksp#1411]
1.
plugins {
id 'com.android.application' version '7.4.2' apply false
id 'com.android.library' version '7.4.2' apply false
id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
id 'com.google.devtools.ksp' version '1.8.0-1.0.9' apply false
}
2.module
plugins {
id 'com.android.application'
id 'org.jetbrains.kotlin.android'
id 'com.google.devtools.ksp'
}

//

Task :app:kspDebugKotlin FAILED
e: [ksp] No providers found in processor classpath.
e: Error occurred in KSP, check log for detail

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:kspDebugKotlin'.
A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
Compilation error. See log for more details

Try:
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

**Comment by AndreyMedal** [comment]
Have the same error but in 1.8.21-1.0.11 version. Any ideas hot to fix?

**Comment by neetopia** [comment]
See my response in #1333
