### ISSUE TITLE
KSP 1.9.0-RC-1.0.11 and Java version via toolchain failure

### ISSUE THREAD

**Issue by SteinerOk** [google/ksp#1422]
After upgrade project from
```
kotlin = "1.8.22"
kspPlugin = "1.8.22-1.0.11"
```
to
```
kotlin = "1.9.0-RC"
kspPlugin = "1.9.0-RC-1.0.11"
```

Build completed with failure:
```
Execution failed for task ':backend:model-jvm:kspKotlin'.
> 'compileJava' task (current target is 17) and 'kspKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

My Build file:
```
plugins {
    id("org.jetbrains.kotlin.jvm")
    id("java-library")
    alias(libs.plugins.ksp)
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    implementation(libs.moshi.client)
    implementation(libs.moshi.adapters)
    ksp(libs.moshi.kotlin.codegen)
    implementation(libs.moshix.adapters)
    implementation(libs.moshix.sealed.runtime)
    ksp(libs.moshix.sealed.codegen)
}
```

**Comment by neetopia** [comment]
You can disable jvm target validation for now with gradle property `kotlin.jvm.target.validation.mode=warning`, a fix will be shipped with 1.9.0 formal release.

**Comment by tokazio** [comment]
Have the same problem (and message) and found that my JAVA_HOME was not in sync with the version asked in the build.gradle file.
Even with using the 'toolchain' config.
Using SDKMan i can get it working by setting the same version (17)

**Comment by neetopia** [comment]
KSP 1.9.0-1.0.11 has been released, can you check it out to see if it resolves your issue?

**Comment by vdshb** [comment]
I've just faced similar issue. Updating to 1.9.0-1.0.11 worked for me.

**Comment by neetopia** [comment]
Closing this issue as 1.9.0-1.0.11 has fixed this issue.
