### ISSUE TITLE
method implementation in generated class - blocker that prevents to migrate to ksp

### ISSUE THREAD

**Issue by vladeekkk** [google/ksp#1429]
Could you please see an issue that I created https://issuetracker.google.com/issues/281665731?
Is it a problem with room or ksp? There is a sample project to recreate the issue

As I understand it, ksp does not see a method implementation in generated class

**Comment by neetopia** [comment]
It looks to me to be a room issue at first glance, pleas keep me update if you get any update from Room

**Comment by danysantiago** [comment]
This is definitely an issue with Room, feel free to close.
