### ISSUE TITLE
Support for hibernate-jpamodelgen

### ISSUE THREAD

**Issue by linde9821** [google/ksp#1432]
Are there any plans to support the Hibernate JPA Modelgen library? Currently the only way to use it with Kotlin is through KAPT. Also, KAPT does not support all use cases. For example, if you try to use a JPA Modelgen generated class inside an `enum class'.

**Comment by neetopia** [comment]
Hi, please bring this up to the Hibernate JPA Modelgen developers as this repository is for KSP itself.
