### ISSUE TITLE
Support creating a simple `KSTypeArgument` from an existing type or declaration

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#1448]
Revisiting #1094 as it was closed without comment by the author but I'm not sure what the solution is. My use case is that `KSClassDeclaration.asType()` is more or less sort of useless as it's not possible to easily create a `KSTypeArgument` instance to pass to it, and in turn this becomes problematic when trying to use `KSType.isAssignableFrom()` on a generic supertype.

**Comment by neetopia** [comment]
We do have `Resolver.getTypeArgument(typeRef: KSTypeReference, variance: Variance)` and `Resolver.createKSTypeReferenceFromKSType(type: KSType)`, do these 2 apis combined help with your use case?

**Comment by ZacSweers** [comment]
Apologies for the delay! That looks perfect for my needs, though I somewhat wish that wasn't tied to the `Resolver` if it could be avoided. These extensions are hard to discover sometimes 😅
