### ISSUE TITLE
@field:MyNestedAnnotation incorrectly resolves to <ERROR TYPE>

### ISSUE THREAD

**Issue by bcorso** [google/ksp#1451]
I have a case where `@field:MyNestedAnnotation` incorrectly resolves to `<ERROR TYPE>`.

Take the example below:

```kotlin
class MyClass {
  @field:MyNestedAnnotation val field: String = TODO()

  annotation class MyNestedAnnotation
}
```

The following prints `@MyNestedAnnotation: <ERROR TYPE>`:

```kotlin
val myClass = resolver.getClassDeclarationByName(KSNameImpl.getCached("MyClass"))
val property = myClass.getAllProperties().single()
property.annotations.forEach { annotation ->
    // @MyNestedAnnotation: <ERROR TYPE>
    println("${annotation}: ${annotation.annotationType.resolve()}")
}
``` 

Note that we get a properly resolved type with any of the following changes:

1. Removing `field:`
    ```kotlin
    // This works!
    @MyNestedAnnotation val field: String = TODO()
    ```
2. Qualifying the annotation with the outer class:
    ```kotlin
    // This also works!
    @field:MyClass.MyNestedAnnotation val field: String = TODO()
    ```

Note: These symptoms sound similar to an already fixed issue: https://github.com/google/ksp/issues/1412

**Comment by neetopia** [comment]
fixed by #1454
