### ISSUE TITLE
getSymbolsWithAnnotation does not return functions declared in anonymous objects

### ISSUE THREAD

**Issue by fan87** [google/ksp#1453]
Calling `Resolver.getSymbolsWithAnnotation` does not return functions annotated with that annotation in anonymous objects (e.g. `object : Something`)

Source Code:
```kt
open class Something

annotation class ExampleAnnotation

fun main() {
    println(object : Something() {
        @ExampleAnnotation fun testFunction() {}
    })
}
```

Annotation Processor:
```kt
resolver.getSymbolsWithAnnotation("ExampleAnnotation") // nothing is found
resolver.getSymbolsWithAnnotation("ExampleAnnotation", true) // as well as this one - if it even helps
```

If it works as intended, how am I supposed to do annotation processing on anonymous objects?

**Comment by neetopia** [comment]
This is beyond the scope of KSP. The anonymous object you are checking here is inside a lambda which is part of an expression and KSP does not look into expressions.
