### ISSUE TITLE
Unable to load class 'org.jetbrains.kotlin.gradle.plugin.mpp.pm20.KotlinCompilationData'. 

### ISSUE THREAD

**Issue by MoatazBadawy** [google/ksp#1481]
This happens when migrating from kept to ksp.
kotlin JVM version "1.8.21". trying to upgrade to "1.9.0". and also failed.

**Comment by neetopia** [comment]
make sure the KSP version used in your project matches the compiler version by checking the ksp version number before the `-`

**Comment by MoatazBadawy** [comment]
I made some search here in Issues and I found a solution that says I need to use the "1.8.21-1.0.11" version. Thanks for your help :)

**Comment by DanteAndroid** [comment]
> 1.8.21-1.0.11

How to check if my ksp/ComposeCompiler versions are right? Thanks!

**Comment by msinghal34** [comment]
Need to use 1.8.21-1.0.11 for ksp version.
https://youtrack.jetbrains.com/issue/KTIJ-26251

**Comment by viroth-ty** [comment]
@DanteAndroid If you're using kotlin version 1.9.0, use ksp 1.9.0-1.0.11.

**Comment by huagnzhiqiang** [comment]
改成 id("com.google.devtools.ksp") version "1.8.21-1.0.11" apply false

**Comment by kid1412621** [comment]
guess this site might be helpful:
https://repo.maven.apache.org/maven2/com/google/devtools/ksp/symbol-processing-gradle-plugin/
