### ISSUE TITLE
KspTaskNative is not configuration cacheable

### ISSUE THREAD

**Issue by yigit** [google/ksp#1522]
KspTaskNative is not configuration cacheable due to a problem in KonanTarget. (https://youtrack.jetbrains.com/issue/KT-61657/KonanTarget-should-implement-equals-or-custom-serialization)

This especially becomes a problem due to the [onlyIf](https://github.com/google/ksp/blob/bdf4d3c75c207d3d0a12cfd4a04c1be58935a28b/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt#L157) check, which always fails after a KSP task is configuration cached.

I think KSP should update its onlyIf check to find the target again from `HostManager` using its name until the Kotlin plugin issue is fixed (to be able to keep the task cacheable).

**Comment by PaulWoitaschek** [comment]
I submitted a hotfix as it will probably take a while until this gets fixed upstream.

We have a build logic where we conditionally disable native targets based on gradle properties.

This leads to the situation that the ksp tasks are skipped even though they should not.
For more context, see:
https://kotlinlang.slack.com/archives/C013BA8EQSE/p1692613954005859

**Comment by ting-yuan** [comment]
I've merged @PaulWoitaschek's patch and it'll be available in the [1.9.10-1.0.14-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/google/devtools/ksp/symbol-processing-api/1.9.10-1.0.14-SNAPSHOT/) tomorrow. The formal release will take a bit longer. I'm wondering if it's possible to override the Task.onlyIf check in your Gradle build scripts?

**Comment by yigit** [comment]
I tried that but the timing is very tricky.
When I register a configure block with task type filter, gradle calls my block before KSP 😔

**Comment by PaulWoitaschek** [comment]
You can not override it. You can only add additional statements. Gradle will then run all onlyIf blocks. It will only run the task if all evaluate to true.

**Comment by ting-yuan** [comment]
@yigit Would wrapping that around with `afterEvaluate` feasible?

**Comment by ting-yuan** [comment]
I'm going to include the patch into 1.9.20-Beta-1.0.13 and later releases so that you won't need to work it around in build scripts.

**Comment by PaulWoitaschek** [comment]
Thanks! Is it safe to use the 1.9.20-Beta ksp version on 1.9.10? 

It warns at configuration time:
> ksp-1.9.20-Beta-1.0.13 is too new for kotlin-1.9.10. Please upgrade kotlin-gradle-plugin to 1.9.20-Beta.

**Comment by ting-yuan** [comment]
Unfortunately, no. It is built for Kotlin 1.9.20-Beta and there may be some incompatibilities to 1.9.10.

**Comment by PaulWoitaschek** [comment]
@ting-yuan 
Can we get a release for 1.9.10? I'd really make use of config cache for our project.

**Comment by ting-yuan** [comment]
Do you really need Kotlin 1.9.10, or will Kotlin 1.9.20 be OK? IIUC 1.9.20 will be out very soon and KSP 1.9.20-1.0.14 will follow very closely after that.

**Comment by PaulWoitaschek** [comment]
As compose often times takes a bit longer we'd love a .10 version.
