### ISSUE TITLE
Possibility to access the (existing) comments/documentation for classes, functions

### ISSUE THREAD

**Issue by jschneider** [google/ksp#1531]
I want to generate typescript definition files for existing Kotlin classes. 
I am implementing my own SymbolProcessor. But I can't find a way to access the KotlinDoc for the existing classes.

Is there any way to access these? I assumen they are not parsed/processed due to performance reasons?

**Comment by neetopia** [comment]
we have `KSDeclaration.docString()` function in our [api](https://github.com/google/ksp/blob/main/api/src/main/kotlin/com/google/devtools/ksp/symbol/KSDeclaration.kt#L57), does that help?

**Comment by jschneider** [comment]
Yes, of course! How could I miss that.
