### ISSUE TITLE
getSymbolsWithAnnotation: No such method exception on version 20201110

### ISSUE THREAD

**Issue by goa** [google/ksp#155]
After updating to version **20201110**, and rebuilding my processors multiple times, I get a `e: java.lang.NoSuchMethodError: com.google.devtools.ksp.processing.Resolver.getSymbolsWithAnnotation(Ljava/lang/String;Z)Ljava/util/List;`.

Everything works fine if I go back to **20201009**.

**Comment by neetopia** [comment]
We added a new parameter for `getSymbolsWithAnnotation` therefore the signature has changed.

What is the project that throws such exception? Is that a processor or a workload project that uses your processors?

**Comment by goa** [comment]
This occurs in the workload project that uses my processor. I just noticed the `inDepth` parameter in the master branch, however it is not available in my local version of ksp (installed via Gradle).

**Comment by ting-yuan** [comment]
The 20201110 version includes the inDepth change. It looks like that your processor (or some of its depending processor) is built with some older version while the workload is built with 20201110. Can you try cleaning gradle cache manually?

**Comment by goa** [comment]
Cleaning the gradle cache manually for both projects fixed this! Thanks very much :)
