### ISSUE TITLE
KSP Incremental Processing: Removing a file does not remove transitively generated files 

### ISSUE THREAD

**Issue by bcorso** [google/ksp#1554]
This issue came up in Dagger (https://github.com/google/dagger/issues/4060). Say we have a class like this:

```kotlin
@HiltViewModel
class ProfileScreenViewModel @Inject constructor()
```

On the first build, we get the following source-to-output map:

```
  src/main/java/com/example/testhiltviewmodel/ProfileScreenViewModel.kt:
    build/.../ProfileScreenViewModel_Factory.java
    build/.../ProfileScreenViewModel_HiltModules.java
  <This is a virtual key for removed outputs; DO NOT USE>:
  build/.../ProfileScreenViewModel_HiltModules.java:
    build/.../_..._ProfileScreenViewModel_HiltModules_KeyModule.java
    build/.../_..._ProfileScreenViewModel_HiltModules_BindsModule.java
    build/.../ProfileScreenViewModel_HiltModules_KeyModule_ProvideFactory.java
```

Next, if we remove the `ProfileScreenViewModel.kt` and rebuild we get this:

```
  <This is a virtual key for removed outputs; DO NOT USE>:
  build/.../ProfileScreenViewModel_HiltModules.java:
    build/.../_..._ProfileScreenViewModel_HiltModules_KeyModule.java
    build/.../_..._ProfileScreenViewModel_HiltModules_BindsModule.java
    build/.../ProfileScreenViewModel_HiltModules_KeyModule_ProvideFactory.java
```

In particular, the generated sources from `ProfileScreenViewModel.kt` are removed, but the transitively generated sources, e.g. `ProfileScreenViewModel_HiltModules`, are not removed.

You can find a repro of this project in https://github.com/google/dagger/issues/4060.

**Comment by ansman** [comment]
@ting-yuan Do you have an ETA for a new release? This is causing some annoying issues for us as cleaning the project isn't enough due to the build cache

**Comment by ting-yuan** [comment]
1.0.14 will be available no later than next week.

**Comment by ansman** [comment]
Thank you, I appreciate that 🙌
