### ISSUE TITLE
:gradle-plugin:compileKotlin task failure caused by a refactoring in kotlin IC internals 

### ISSUE THREAD

**Issue by ksiarhey** [google/ksp#1588]
Steps to reproduce: 
1. Specify LanguageVersion = 1.9 for all KotlinCompile tasks in the KSP project 
2. Build KSP gradle plugin from the main branch using one of the recently published kotlin builds (for example, 2.0.0-dev-5387)

Actual Results: task :gradle-plugin:compileKotlin fails with the following errors :

`e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:39:49 Unresolved reference: AppendableBasicMap
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:40:49 Unresolved reference: AppendableDataExternalizer
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:54:24 Unresolved reference: AppendableDataExternalizer
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:56:5 Unresolved reference: AppendableBasicMap
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:71:5 'dumpKey' overrides nothing
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:73:5 'dumpValue' overrides nothing
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:76:9 Unresolved reference: storage
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:79:71 Unresolved reference: storage
e: file:///UsersDocuments/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:82:9 Unresolved reference: storage
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:86:9 Unresolved reference: storage
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:90:17 Unresolved reference: storage
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:134:63 Unresolved reference: storage
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:137:9 Unresolved reference: storage
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:140:5 'dumpKey' overrides nothing
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:142:5 'dumpValue' overrides nothing
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:146:9 Unresolved reference: storage
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:150:17 Unresolved reference: storage
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:455:28 Unresolved reference: flush
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:518:24 Unresolved reference: clean
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:521:23 Unresolved reference: clean
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:524:20 Unresolved reference: flush
e: file:///Users/Documents/k2-samples/ksp-int-playground/ksp/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt:525:20 Unresolved reference: close`

The [commit](https://github.com/JetBrains/kotlin/commit/4e89dcf031c75c538dcff9f4b52e5823a9ea8759) on the kotlin team's side causing the issue

**Comment by ting-yuan** [comment]
@neetopia the upcoming compiler bump will be bumpy.

**Comment by hungvietnguyen** [comment]
FYI, Kotlin build team confirmed that KSP no longer compiles with KGP @ HEAD.

**Comment by ting-yuan** [comment]
https://github.com/google/ksp/issues/1608

**Comment by ting-yuan** [comment]
@hungvietnguyen most of the uses of persistent maps in compiler is replaced in this PR: https://github.com/google/ksp/pull/1609

The only one left is `org.jetbrains.kotlin.incremental.LookupStorage`, which requires more efforts to re-implement. If it is not blocking you, I'll do it next quarter.

**Comment by ting-yuan** [comment]
Verified working with Kotlin HEAD. A couple of minor changes for analysis api, which has nothing to do with KGP, are needed though.

**Comment by hungvietnguyen** [comment]
@ting-yuan That all sounds good to me, thanks!
