### ISSUE TITLE
Feature request: expose an API in Resolver to retrieve the module name for handling mangling of internal members

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#1621]
`internal` members will have mangled names when seen from Java. In an existing non-KSP compiler plugin (Anvil) we use this logic to compute the mangled suffix that these functions would have like so

```kotlin
private fun ModuleDescriptor.mangledNameSuffix(): String {
  // We replace - with _ to maintain interoperability with Dagger's expected generated identifiers
  val name = name.asString().replace('-', '_')
  return if (name.startsWith('<') && name.endsWith('>')) {
    name.substring(1, name.length - 1)
  } else {
    name
  }
}
```

Could KSP expose an API to access `ModuleDescriptor.name`? This would allow ensuring generation of jvm-compatible sources when migrating to KSP in our case.

**Comment by ZacSweers** [comment]
I could send a PR for this too if you're open to it

**Comment by ting-yuan** [comment]
Thanks, the API sounds good and patches are welcome.

btw, in case I'm on vacation, please ping @neetopia for review after Dec. 10.

**Comment by ZacSweers** [comment]
Done #1649
