### ISSUE TITLE
build fail when use kotlin 1.9.22 

### ISSUE THREAD

**Issue by weijunfeng** [google/ksp#1666]
When I use kotlin 1.9.22 version, the build fails：

A problem was found with the configuration of task ':test:kspKotlinIosX64' (type 'KspTaskNative').
  - In plugin 'com.google.devtools.ksp' type 'com.google.devtools.ksp.gradle.KspTaskNative' property 'produceUnpackedKlib$kotlin_gradle_plugin_common' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'produceUnpackedKlib$kotlin_gradle_plugin_common'.
      2. Mark property 'produceUnpackedKlib$kotlin_gradle_plugin_common' as optional.
    
    Please refer to https://docs.gradle.org/7.6.1/userguide/validation_problems.html#value_not_set for more details about this problem.

**Comment by neetopia** [comment]
There is a breaking change in Kotlin native task in Kotlin gradle plugin, I am working with JB to sort it out but it is holiday season now it might be delayed, I will let you know if any updates.

**Comment by neetopia** [comment]
Please try out latest KSP release for this issue.

**Comment by TheArchitect123** [comment]
Hi,
I love KSP. And thank you for your work on this library. It's awesome.

I've recently upgraded to the latest via MvnCentral.
https://mvnrepository.com/artifact/com.google.devtools.ksp/symbol-processing-api/2.0.0-Beta2-1.0.16

And the issue is still there.
Thank you for your help.

@neetopia

**Comment by neetopia** [comment]
The offending commit is not part of 2.0.0-Beta2 release, if you are experiencing this issue, please check if you are running kotlin 
 gradle plugin 1.9.22, if so, please use KSP 1.9.22-1.0.16

**Comment by TheArchitect123** [comment]
I did @neetopia.
I tried both. And the error persists

**Comment by TheArchitect123** [comment]
Ok I found the issue. All good. Thanks
