### ISSUE TITLE
Annotations missing on `KSTypeArgument` of `typealias`

### ISSUE THREAD

**Issue by bcorso** [google/ksp#1679]
We ran into a case in Dagger where the `@JvmSuppressWildcards` is missing in the following case:

```kotlin
interface MyType
typealias MyAlias = MyType
typealias MyListAlias = List<@JvmSuppressWildcards MyAlias>
fun method(): MyListAlias
```

In particular, if we try to resolve `MyListAlias` the `@JvmSuppressWildcards` annotation is now missing (I'm just printing the `toString()` here since it's easier, but actually getting the annotations from the type arguments gives the same result):

```kotlin
// Prints: List<MyType> instead of List<[@JvmSuppressWildcards] MyType>
println("${(method.returnType().declaration as KSTypeAlias).type.resolve()}") 
```

I've also checked that all annotations get dropped, not just `@JvmSuppressWildcards`.

I'm guessing this is related to the nested `typealias`, because the following cases with a single `typealias` seem to work fine:

```kotlin
interface MyType
typealias MyListAlias = List<@JvmSuppressWildcards MyType>
fun method(): MyListAlias

// This works!
// Prints: List<[@JvmSuppressWildcards] MyType>
println("${(method.returnType().declaration as KSTypeAlias).type.resolve()}") 
```

```kotlin
interface MyType
typealias MyAlias = MyType
fun method(): List<@JvmSuppressWildcards MyAlias>

// This works!
// Prints: List<[@JvmSuppressWildcards] MyType>
println("${(method.returnType().declaration as KSTypeAlias).type.resolve()}") 
```

**Comment by neetopia** [comment]
Offending line might be [here](https://github.com/google/ksp/blob/92d5905a863a8c796e55714d0f9da5e1f125f027/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt#L689) 
KSP expanded type alias too eagerly to the end.
