### ISSUE TITLE
upgrade to kotlin 1.4.20

### ISSUE THREAD

**Issue by yigit** [google/ksp#168]
Just filing this as a tracking ticket.
Looks like KSP is not compatible w/ 1.4.20 (as expected).

I hit this when trying to use KSP in room as AndroidX already uses 1.4.20. 

```
e: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.descriptors.CallableDescriptor org.jetbrains.kotlin.resolve.calls.inference.InferenceUtilsKt.substitute(org.jetbrains.kotlin.descriptors.CallableDescriptor, org.jetbrains.kotlin.resolve.calls.inference.components.NewTypeSubstitutor)'
        at com.google.devtools.ksp.processing.impl.ResolverImpl.asMemberOf(ResolverImpl.kt:542)
        at androidx.room.compiler.processing.ksp.KSAsMemberOfKt.typeAsMemberOf(KSAsMemberOf.kt:34)
```

I took a quick look to see if ksp's own source compiles.  It seems to be affected by this CL:
https://github.com/JetBrains/kotlin/commit/a05d6da43b0b6fd3bb0f31d3603b5fd192b597b1#diff-9dce699a83c65328e3f52c6669cabb8f0e5115835ddd41e83cfeb2441c29db99

I got it to compile (https://github.com/yigit/ksp/tree/update-kotlin-1.4.20) but haven't run tests yet as it requires copying test utils but i don't have a kotlin checkout to easily try it.

**Comment by yigit** [comment]
so i tried pulling in the tests but it was failing w/ missing class exceptions, looks like there were some changes around mutes.
I pulled in tests-mutes just to try as well but then it failed with the following exception.

```
'void com.intellij.core.CoreApplicationEnvironment.registerExtensionPointAndExtensions(java.nio.file.Path, java.lang.String, com.intellij.openapi.extensions.ExtensionsArea)'
java.lang.NoSuchMethodError: 'void com.intellij.core.CoreApplicationEnvironment.registerExtensionPointAndExtensions(java.nio.file.Path, java.lang.String, com.intellij.openapi.extensions.ExtensionsArea)'
	at org.jetbrains.kotlin.cli.jvm.compiler.CoreApplicationEnvironmentCompatKt.registerExtensionPointAndExtensionsEx(coreApplicationEnvironmentCompat.kt:17)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerApplicationExtensionPointsAndExtensionsFrom(KotlinCoreEnvironment.kt:537)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createApplicationEnvironment(KotlinCoreEnvironment.kt:508)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForTests(KotlinCoreEnvironment.kt:451)
	at com.google.devtools.ksp.test.AbstractKotlinKSPTest.compileModule(AbstractKotlinKSPTest.kt:113)
	a
```
I'm probably doing something wrong so will stop here :)

**Comment by ting-yuan** [comment]
@neetopia would you mind to do a rebase? Since https://github.com/google/ksp/tree/multi-round was rebased to master, the efforts to 1.4.20 should be a subset?

**Comment by ting-yuan** [comment]
The tests might need to be updated: https://github.com/google/ksp/blob/master/third_party/prebuilt/README.md

**Comment by neetopia** [comment]
intellij sdk version isn't an issue yet, still a good idea to upgrade it though.

The main issue with `test-mutes` module is the same issue I encountered in multiple round branch. It has something to do with the prebuilt binary of test framwork. It only affects tests so if you are not interested in tests you can simply publish it to local without testing, I'll look into the test package issue later.

**Comment by yigit** [comment]
updating IJ base version was the key (i've also updated the plugin version but do not have to i think, at least it didn't help by itself)

good news, all tests pass now :)

**Comment by yigit** [comment]
I sent a PR but feel free to ignore it.
FYI for prebuilts, i've checked out kotlin v1.4.20 tag.

**Comment by ting-yuan** [comment]
@neetopia it would be great to upgrade Gradle to 6.6.1 as well, so as to be consistent with the compiler. Let's do it in another PR.
