### ISSUE TITLE
CI test failures causing artifacts.zip to no longer get attached to releases

### ISSUE THREAD

**Issue by Bencodes** [google/ksp#1690]
The releases tests are failing causing the artifacts to no longer get attached to the releases.

Ex: https://github.com/google/ksp/actions/runs/7589865550/job/20675350497

**Comment by Bencodes** [comment]
Both https://github.com/google/ksp/releases/tag/1.9.22-1.0.17 and https://github.com/google/ksp/releases/tag/2.0.0-Beta3-1.0.17 are missing the artifacts.

**Comment by neetopia** [comment]
Fixed.
