### ISSUE TITLE
getJvmName throws exception for static java methods

### ISSUE THREAD

**Issue by yigit** [google/ksp#170]
For the given source:

```
class Foo { 
    static void staticMethod() {}
}
```
calling getJvmName on `staticMethod` throws:
```
Cannot find descriptor for staticMethod
java.lang.IllegalStateException: Cannot find descriptor for staticMethod
	at com.google.devtools.ksp.processing.impl.ResolverImpl.getJvmName(ResolverImpl.kt:520)
```

**Comment by yigit** [comment]
Here is some more debugging information:

in `resolveJavaDeclaration`, when we resolve the class as:
`moduleClassResolver.resolveClass(JavaMethodImpl(psi).containingClass)`
the static methods / fields disappear.

I can see `JavaMethodImpl(psi).containingClass.methods` has the method.
Further debugging shows it is actually in `staticScope` instead of `unsubstitutedMemberScope`.

I don't fully understand what these scopes are but should we searching all scopes instead?

**Comment by neetopia** [comment]
Yeah we should do that. That hasn't been an issue for kotlin since static stuff are treated as an inner class.
