### ISSUE TITLE
[KSP2] The order of symbols returned from Resolver.getSymbolsWithAnnotation() is different

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1719]
Not sure if it's intended or a known issue but I couldn't find any doc explaining this.

Using `Resolver.getSymbolsWithAnnotation()` to get symbols annotated with `TopLevelAnnotation` on this code:

```
class Baz constructor(
    @param:TopLevelAnnotation val ctorProperty: String,
    @TopLevelAnnotation ctorParam: String
) {
    @setparam:TopLevelAnnotation
    var property: String = ""
    fun method(@TopLevelAnnotation methodParam: String) {}
}
```

returns `[p0, methodParam, ctorProperty, ctorParam]` in KSP 2 but was
`[ctorProperty, ctorParam, p0, methodParam]` in KSP 1

This can also be reproduced with `testGetSymbolsFromAnnotation()` in the KSP project, which is disabled in `KSPAATest.kt`.

Tested with 42217b8cbf11609d42eee71a607e4011904c6cd8 and `2.0.0-Beta3-1.0.18-20240207.110119-15`.

**Comment by neetopia** [comment]
Ordering is not a goal for consistency between KSP1 and KSP2, we do try out best to preserve same ordering between 2 implementations, if this ordering inconsistency is an issue for your implementation, we can try to fix it.

**Comment by kuanyingchou** [comment]
Ah, thanks! I reported this because one of XProcessing's tests is failing, but while trying to find out whether the ordering is important I found that our function that wraps `getSymbolsWithAnnotation` is returning a `Set` already so the ordering shouldn't matter. Let me fix our test. Sorry for the noise. 🙏
