### ISSUE TITLE
Should KSPropertyDeclarationImpl.findOverridee use singleOrNull?

### ISSUE THREAD

**Issue by mvdbos** [google/ksp#174]
https://github.com/google/ksp/blob/638d9a19a9880056c8c95a5a2f5775045cb026ae/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt#L107

This now fails for me on an overridden val. The way this code is written now, looks like the last '?' in this part of the statement `.single { it.overriddenDescriptors.isEmpty() }?` is never going to happen, since `single` never returns null.

**Comment by mvdbos** [comment]
After changing this to `singleOrNull` I no longer get the `NoSuchElementException` and looks like all properties are correctly found.

**Comment by yigit** [comment]
i think we need to move it to be similar to how functions are implemented:
https://github.com/google/ksp/pull/151
I totally missed properties while implementing that :/
