### ISSUE TITLE
[KSP2] Could not find annotation declaration when origin is JAVA or JAVA_LIB

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1750]
For an annotation declaration in Java like this:

```
public @interface MyAnnotation {}
```

Calling `resolver.getClassDeclarationByName("MyAnnotation")` returns `null` in KSP2. It's also `null` when `MyAnnotation` is from `JAVA_LIB`.

Tested with https://github.com/google/ksp/commit/a0cd7774a7f65cec45a50ecc8960ef5e4d47fc21.

**Comment by neetopia** [comment]
tried in our test suite everything seems working fine, do you have a reproduce link?

https://github.com/neetopia/ksp/commit/1ac14e26693c094f9fad3c4118eaf608d77cf3f2

**Comment by kuanyingchou** [comment]
@neetopia Argh, that's strange! I must have done something wrong in my tests. Here's a repro: https://github.com/google/ksp/commit/f22b22d717e04d54d764251e008c5fdca43560ec. I got `NullPointerException` in `KSPAATest`, but it works fine in `KSPCompilerPluginTest`.

**Comment by neetopia** [comment]
Oh 🤦 it turned out this is because `KSPAATest.testAnnotationValue_java()` uses `kotlin-analysis-api/testData/annotationValue/java.kt` file... 
` @TestMetadata("annotationValue_java.kt")` was not updated correspondently.
