### ISSUE TITLE
[KSP2] Supertype of enums changed from Any to Enum

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1761]
This is more of a documentation issue. The super type of an enum declaration is `Any` when the origin is `KOTLIN` in KSP1 but is `Enum` in KSP2.
 
Repro: https://github.com/kuanyingchou/ksp/commit/9b37ab7d3fec1f0fba381c9378f77cd3baff0177

**Comment by neetopia** [comment]
It is a behavior change but the new behavior is more correctly reflecting the true type hierarchy of an enum class, is this workaroundable on your side?

**Comment by kuanyingchou** [comment]
@neetopia Yes, thanks for confirming! I haven't found any issues in XProcessing from this change. Actually this makes the behavior consistent with KAPT and the KOTLIN_LIB origin and could mean less work for us. Just thought that maybe it could be included in docs like https://android-developers.googleblog.com/2023/12/ksp2-preview-kotlin-k2-standalone.html. Feel free to close this one.

**Comment by neetopia** [comment]
Got it, I've added documentation label to this issue to be addressed in future
