### ISSUE TITLE
Update plugin com.google.devtools.ksp to v1.9.22-1.0.18 BUILD FAILED

### ISSUE THREAD

**Issue by fbu11** [google/ksp#1772]
Checking the license for package Android SDK Platform-Tools in /usr/local/lib/android/sdk/licenses
License for package Android SDK Platform-Tools accepted.
Preparing "Install Android SDK Platform-Tools v.35.0.0".
"Install Android SDK Platform-Tools v.35.0.0" ready.
Installing Android SDK Platform-Tools in /usr/local/lib/android/sdk/platform-tools
"Install Android SDK Platform-Tools v.35.0.0" complete.
"Install Android SDK Platform-Tools v.35.0.0" finished.

FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:app:kaptDebugKotlin
\--- :app:kaptGenerateStubsDebugKotlin
     \--- :app:kspDebugKotlin
          \--- :app:kaptDebugKotlin (*)

(*) - details omitted (listed previously)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m [34](https://github.com/fbu11/DemoApp/actions/runs/8091137653/job/22109741038#step:5:35)s

**Comment by ZacSweers** [comment]
Another repro: https://github.com/slackhq/circuit/pull/1243

**Comment by ZacSweers** [comment]
Wat

**Comment by steffandroid** [comment]
@fbu11 this is not a viable solution for projects which use KSP alongside KAPT. Please could you reopen, so we don't have to duplicate the issue?

**Comment by steffandroid** [comment]
Fixed by #1782, can now be closed @fbu11.

**Comment by neetopia** [comment]
Should be fixed in next release, closing for now.
