### ISSUE TITLE
KSP2 in 1.0.18 results in significant memory pressure

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#1776]
Continuing from https://github.com/ZacSweers/kotlin-compile-testing/pull/196#discussion_r1508457693. I'm running simple tests in that case with 8GB of memory allocated to gradle daemon, which should be more than enough I'd think?

**Comment by ting-yuan** [comment]
May I know how you adjusted the heap? `org.gradle.jvmargs=-Xmx????m` didn't work for me, but the following does:
```
tasks.withType<Test> {
  minHeapSize = "1024m"
  maxHeapSize = "1024m"
}
```

**Comment by ZacSweers** [comment]
Oh good point, I was just setting it via the gradle daemon memory but forgot tests have their own VMs. Will try that

**Comment by ZacSweers** [comment]
Looks like that works, thanks!
