### ISSUE TITLE
[KSP2] The package name of FunctionN is different between KSP1 and KSP2

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1830]
For example, in KSP2 the qualified name of the no-arg function type is `kotlin.Function0` but the package name is `kotlin.jvm.functions` instead of `kotlin`.

Repro: https://github.com/kuanyingchou/ksp/commit/ab47eacdfc681ea4f5070b7581a54fe42e1595f1

**Comment by ting-yuan** [comment]
Duplication of #1845

**Comment by neetopia** [comment]
fixed as of #1845
