### ISSUE TITLE
[KSP2] Annotation value is missing in nested annotations

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1833]
This is similar to https://github.com/google/ksp/issues/1798

The value of nested annotation is `null` when the origin is KOTLIN_LIB.

Repro: https://github.com/kuanyingchou/ksp/commit/f7c01d693910b8d26de53e9dd0acf4171482f5b5

**Comment by neetopia** [comment]
The value of the annotation is parsed to be `KtUnsupportedAnnotationValue`, it requires an upstream fix to allow the parsing of such annotation value.

**Comment by stevenzeck** [comment]
@neetopia where upstream is the fix required?

**Comment by neetopia** [comment]
pending https://youtrack.jetbrains.com/issue/KT-68981

**Comment by ting-yuan** [comment]
This should be fixed in Analysis API in a few hours ago: https://youtrack.jetbrains.com/issue/KT-69761.
