### ISSUE TITLE
[KSP2] Type annotation value is missing in nested annotations

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1836]
This is similar to https://github.com/google/ksp/issues/1833

Nested annotation values are null in type annotations when the origin is JAVA or JAVA_LIB.

Repro: https://github.com/kuanyingchou/ksp/commit/372a234a17b8e018886f405984ac4eed14252149

**Comment by abirhasan132** [comment]
#1836

**Comment by ting-yuan** [comment]
Analysis API doesn't handle type annotation in Java. It works well for Kotlin. We likely need to work it around in KSP.

**Comment by ting-yuan** [comment]
This just got fixed in the upstream: https://youtrack.jetbrains.com/issue/KT-69761.

**Comment by ting-yuan** [comment]
Verified with latest KSP.
