### ISSUE TITLE
[KSP2] Couldn't find enum values in annotation args

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1838]
Getting annotation arg values for enum args returns null when the origin is JAVA_LIB.

Also found that when the origin is JAVA, the value type for the enum arg is `KSTypeImpl` instead of `KSClassDeclarationEnumEntryImpl`.

Repro: https://github.com/kuanyingchou/ksp/commit/d8fa1e7ff33e960c2c2493ac243c508b3923f981

**Comment by neetopia** [comment]
this should be fixed in #1881
