### ISSUE TITLE
[KSP2] Couldn't find type values in annotation args

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1840]
Getting annotation argument values of Class/KClass types returns error type when the origin is KOTLIN_LIB.

Also got error type when it's a type annotation and the origin is JAVA_SRC.

Repro: https://github.com/kuanyingchou/ksp/commit/379e0425219367de80357324368aa3608e769bfb

**Comment by ting-yuan** [comment]
duplication of #1646

**Comment by neetopia** [comment]
closing this issue as the duplicate is resolved.
