### ISSUE TITLE
[KSP2] Property setter parameter name becomes `value`

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1865]
In KSP2 the parameter name of property setters is `value` when the origin is `KOTLIN_LIB` but is `<set-?>` when the origin is `KOTLIN`, while it was always `<set-?>` in KSP1.

Repro: https://github.com/kuanyingchou/ksp/commit/49600e0fd5933bee4338eaee9b7b7dfe86636fa8

**Comment by neetopia** [comment]
does this impact any of your use cases? I think the name itself is not well defined in spec, therefore this is an either way works case, let me know if you have code that directly depends on the name of this setter parameter.

**Comment by kuanyingchou** [comment]
Ah, in XProcessing we keep the parameter name user defined and change it to "p0" if we see "<set-?>" as it's not valid in source.  With this change this logic doesn't work anymore. Or is there a way we can tell if the setter is user-defined or not?

**Comment by neetopia** [comment]
Yes, if the parameter is not user defined, you should see `origin == Origin.SYNTHETIC` in the `KSValueParameter`

**Comment by neetopia** [comment]
you can check on the origin of the `KSValueParameter` of the property setter, I got the following output from your repro, does this help?
```
SYNTHETIC
KOTLIN_LIB
```

**Comment by ting-yuan** [comment]
Per discussion offline, let's
1. check whether there's anything in the language spec, and
2. align the naming for source and libs.

**Comment by kuanyingchou** [comment]
Yes, checking the origin as well as consistent names both work for us. Thanks!
