### ISSUE TITLE
released POM files do not list dependencies

### ISSUE THREAD

**Issue by yigit** [google/ksp#187]
I noticed this after hitting some class not found exceptions after an upgrade.
turns out, the pom files are missing dependencies and it was pulling kotlin compiler embeddable 1.4.10 instead of 1.4.20 for tests. (1.4.10 comes from kotlin compile testing's dependencies)

Is this intentional?
https://dl.google.com/android/maven2/com/google/devtools/ksp/symbol-processing/1.4.20-dev-experimental-20201204/symbol-processing-1.4.20-dev-experimental-20201204.pom

**Comment by ting-yuan** [comment]
Fixed in #233
