### ISSUE TITLE
[KSP2] Annotations got use-site target when there are none specified

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1882]
KSP2 sees annotations applied on properties without use-site target having a non-null `useSiteTarget` when the origin is KOTLIN_LIB, but `useSiteTarget` is null when the origin is KOTLIN or in KSP1.

Repro: https://github.com/kuanyingchou/ksp/commit/e70793030f539616f6bb62d65f79d8492720efba

**Comment by neetopia** [comment]
This does seems to be more correct, is this behavior change a blocking issue for you?

**Comment by kuanyingchou** [comment]
Yes, we do additional filtering in XProcessing and this leads to missing annotations. Also the behavior is different between when the origin is KOTLIN_LIB and other origins.
