### ISSUE TITLE
[KSP2] Annotations on extension receivers are missing

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1899]
Couldn't find the annotations when the origin is KOTLIN or KOTLIN_LIB with KSP2, while it was working with KSP1.

Repro: https://github.com/kuanyingchou/ksp/commit/dc348820ad307533c3ed3bbdd3fa3a83055eefdf

**Comment by neetopia** [comment]
It seems that annotations are lost during the transforming from psi to `KtType`.
