### ISSUE TITLE
getting null pointer exception 

### ISSUE THREAD

**Issue by rohitkasanwal2708** [google/ksp#1929]
* What went wrong:
Execution failed for task ':pitaraShared:kspKotlinIosSimulatorArm64'.
> A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction
   > null cannot be cast to non-null type org.jetbrains.kotlin.load.java.structure.impl.JavaClassImpl

**Comment by ting-yuan** [comment]
Duplication of #1753
