### ISSUE TITLE
[KSP2] KSPropertyDeclaration.hasBackingField returns inconsistent results

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1939]
We have 6 tests in XProcessing that hit this. `hasBackingField` returns different results when running the test individually vs running all tests in the test class.

Repro: https://github.com/kuanyingchou/ksp/commit/b7122a91afc4b24230c8c256b4e332c98452a34c

**Comment by abirhasan132** [comment]
6CA761AB6CA7
