### ISSUE TITLE
[KSP2] A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction

### ISSUE THREAD

**Issue by GuilhE** [google/ksp#1941]
In [this](https://github.com/GuilhE/WhosNext) and [this](https://github.com/GuilhE/Expressus) KMP projects, when I turn on `KSP2` it will fail `kspKotlinIosSimulatorArm64` with:

```
e: [ksp] java.lang.NullPointerException: null cannot be cast to non-null type org.jetbrains.kotlin.load.java.structure.impl.JavaClassImpl

* What went wrong:
Execution failed for task 'shared:kspKotlinIosSimulatorArm64'.
> A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction
   > null cannot be cast to non-null type org.jetbrains.kotlin.load.java.structure.impl.JavaClassImpl
```
using:
```
kotlin = "2.0.0"
ksp = "2.0.0-1.0.21"
ksp.useKSP2=true
```
possible duplicate of #1929

**Comment by GuilhE** [comment]
Still failing:

```
kotlin = "2.0.20-Beta1"
ksp = "2.0.20-Beta1-1.0.22"
ksp.useKSP2=true
```

**Comment by ting-yuan** [comment]
Duplication of #1753

**Comment by GuilhE** [comment]
Still failing:
```

kotlin = "2.0.20"
ksp = "2.0.20-1.0.24"
ksp.useKSP2=true
```

**Comment by GuilhE** [comment]
@ting-yuan `1.0.25` release notes states that this is fixed but I'm still getting:


```
* What went wrong:
Execution failed for task ':shared:kspKotlinIosSimulatorArm64'.
> A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction
   > null cannot be cast to non-null type org.jetbrains.kotlin.load.java.structure.impl.JavaClassImpl
```

Use [this](https://github.com/GuilhE/WhosNext) to reproduce.

**Comment by Nirav186** [comment]
```
kotlin = "2.0.20-RC"
room = "2.7.0-alpha01"
ksp = "2.0.20-RC-1.0.24"
```
and add `ksp.useKSP2=true` to your `gradle.properties` (if you are using `kotlin 2.x.x`)
this will fix your problem and if you still getting the same error then try to remove `@TypeConverters(<converter class name>::class)`

**Comment by GuilhE** [comment]
> ```
> kotlin = "2.0.20-RC"
> room = "2.7.0-alpha01"
> ksp = "2.0.20-RC-1.0.24"
> ```
> 
> and add `ksp.useKSP2=true` to your `gradle.properties` (if you are using `kotlin 2.x.x`) this will fix your problem and if you still getting the same error then try to remove `@TypeConverters(<converter class name>::class)`

check [this](https://github.com/google/ksp/issues/1896#issuecomment-2329218683)

**Comment by GuilhE** [comment]
@ting-yuan :
```
kotlin = "2.1.0-Beta2"
ksp = "2.1.0-Beta2-1.0.26"
ksp.useKSP2=true
```
Works! 🎊
