### ISSUE TITLE
KSP2 default annotation KClass values for built-in types use java.lang.* versions

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#1948]
Consider this example:

```kotlin
annotation class ExampleAnnotation(val value: KClass<*> = String::class)

@ExampleAnnotation(String::class)
class Example
```

In KSP2, the default value of `value` is a `KSTypeImpl` that points at `java/lang/String` while the `KSAnnotation` argument from the annotated `Example` class points at `kotlin/String`. This results in the types not being considered equal.

<img width="689" alt="image" src="https://github.com/google/ksp/assets/1361086/89dd9ff9-c0f6-4de7-b65e-8f66b2844225">

<img width="641" alt="image" src="https://github.com/google/ksp/assets/1361086/e52ee79b-4843-49b5-8667-90c5c316cca1">

**Comment by ZacSweers** [comment]
This was tested on `2.0.0-1.0.22-SNAPSHOT` today

**Comment by neetopia** [comment]
can you share how you configure to run on snapshot? I tried to run your test locally with a local build and I got this error

```
e: file:///var/folders/l7/39bc4svn2g3b08k7jx3rsf1c00m1r6/T/junit6026606767842928735/ksp/sources/kotlin/test/TestSmokeTestClass.kt:20:29 Unresolved reference 'kotlin'.
```

**Comment by ZacSweers** [comment]
Just pushed a branch with it to the mentioned PR above: https://github.com/square/kotlinpoet/pull/1885

The test is `TestProcessorTest.removeDefaultValues`

You can breakpoint `Annotations.kt` at line 59 or the `isDefaultValue` function on line 83 to see what I linked in the screenshots
