### ISSUE TITLE
resolving a class from KSType.declaration vs getClassDeclarationByName gives different results

### ISSUE THREAD

**Issue by yigit** [google/ksp#195]
repro CL: https://github.com/yigit/ksp/tree/class-declaration-inconsistency-repro

for some reason, i get two different KSClassDeclaration's for the same class when it is resolved from a KSType vs getClassDeclarationByName

**Comment by ting-yuan** [comment]
When applicable, builtins on jvm has a special `mockSerializableType` super type, which is hard-coded to have an empty scope:
https://github.com/JetBrains/kotlin/blob/master/core/descriptors.jvm/src/org/jetbrains/kotlin/builtins/jvm/JvmBuiltInsSettings.kt#L79

Besides fixing in upstream, there is no good way to workaround unfortunately.

**Comment by ting-yuan** [comment]
Worked around in #196.
