### ISSUE TITLE
A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction

### ISSUE THREAD

**Issue by fbu11** [google/ksp#1997]
version:2.0.0-1.0.23

* What went wrong:
Execution failed for task ':lib_captcha:kspReleaseKotlin'.
> A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction
   > Collection contains no element matching the predicate.

**Comment by hantsy** [comment]
The same error here when upgrading to 2.0.20-Beta2-1.0.23

**Comment by hantsy** [comment]
Is there a workaround for this issue?

**Comment by ting-yuan** [comment]
Can anyone share some stack trace or a reproduce project?

**Comment by kasem-sm** [comment]
I'm using Kotlin 2.0.20-Beta2 and KSP 2.0.20-Beta2-1.0.23 for [kotlin-inject](https://github.com/evant/kotlin-inject). 

and the error is - `Execution failed for task ':androidApp:kspDebugKotlin'.
> A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction
   > KSP failed with exit code: PROCESSING_ERROR`

CC - @evant

**Comment by OdisBy** [comment]
I'm using Kotlin 2.0.0. When I bump KSP from version 2.0.0-1.0.22 to 2.0.0-1.0.23, I get the following error:
```
A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction
Collection contains no element matching the predicate.
```
Downgrading to KSP 2.0.0-1.0.22 resolves the issue.

**Comment by seljabali** [comment]
Upgrading to Kotlin `2.0.20-RC` & KSP to `2.0.20-RC-1.0.24` solved the problem.

**Comment by Nirav186** [comment]
```
kotlin = "2.0.20-RC"
room = "2.7.0-alpha01"
ksp = "2.0.20-RC-1.0.24"
```
and add `ksp.useKSP2=true` to your `gradle.properties` (if you are using `kotlin 2.x.x`)
this will fix your problem and if you still getting the same error then try to remove `@TypeConverters(<converter class name>::class)`
