### ISSUE TITLE
Configuration with name 'kspJvm' not found.

### ISSUE THREAD

**Issue by malik-hasan** [google/ksp#2028]
Compose Multiplatform project which supports Android, iOS and JVM

It builds for all targets except JVM: `Configuration with name 'kspJvm' not found.`

Dependencies

```
dependencies {
    listOf(
        "kspAndroid",
        "kspIosArm64",
        "kspIosX64",
        "kspIosSimulatorArm64",
        "kspJvm"
    ).forEach {
        add(it, libs.room.compiler)
    }
}
```

Versions

```
[versions]
kotlin = "2.0.10"
ksp = "2.0.10-1.0.24"
room = "2.7.0-alpha06"
```

**Comment by danysantiago** [comment]
Is your project targeting JVM? You should see it targets JVM / Desktop in the build file DSL:
```
kotlin {
  // ...
  jvm("desktop")
  // ...
}
```

**Comment by malik-hasan** [comment]
Ah thank you! Yes, I did use the wizard. Changing it to kspDesktop fixed it.
