### ISSUE TITLE
kspCaches don't work together with Gradle build cache

### ISSUE THREAD

**Issue by oehme** [google/ksp#2042]
The ksp task has a `kspCaches` directory which contains backups of generated classes. The following sequence of events will lead to stale outputs files and compile errors:

1. Run an initial build
2. Add an annotated class and run another build - Code is generated for that new class
3. Remove the class again and run another build- This results in a Gradle cache hit for ksp, restoring the output of step 1., but the kspCaches directory is unchanged and still contains the backup of that class
4. Make any incremental change in the source code and run another build - ksp now restores the class from step 2, even though its source file no longer exists - This class likely does not compile any more

The only fix at that point is to do a clean build to get rid of the caches.

Workaround: I've marked the kspCaches directory for each ksp task as localState in our build, so Gradle deletes it on a cache hit.

Tested with [1.9.25-1.0.20](https://github.com/google/ksp/releases/tag/1.9.25-1.0.20)

**Comment by ansman** [comment]
I am able to reproduce this in a test case. I will attempt a fix. 

@ting-yuan Would it be OK to mark the kspCaches as local state as a fix?

**Comment by ansman** [comment]
I can confirm that marking the directory as local state does indeed work.

@oehme Have you noticed any issues with marking it as local state?

**Comment by oehme** [comment]
I assume that deleting them would make the next build non-incremental? That would be the main downside.

The alternative would be mark the caches as an output, so they get restored together with the classes they belong to. Then the next build could work incrementally again. For that to work, the caches need to be portable across machines (no absolute paths etc.). I didn't try it, because I didn't know what those caches contain exactly.

**Comment by ansman** [comment]
@oehme Thanks for the repro, I implemented a fix in #2055

**Comment by oehme** [comment]
Thanks!
