### ISSUE TITLE
Room integration with Kotlin Multiplatform is not working. Ksp error is showing here. 

### ISSUE THREAD

**Issue by abdulhamidrpn** [google/ksp#2045]
KSP apoption does not match \S+=\S+: room.internal.schemaInput= C:\composeApp\schemas

**Comment by danysantiago** [comment]
Can you please provide a more detailed explanation of the issue?

**Comment by abdulhamidrpn** [comment]
I resolved the issue by discovering that there was a space in the folder path in my root directory, which was causing the error.

**Comment by dauni6** [comment]
I think this issue only occurs when there's a space in the folder name where the project is cloned.
