### ISSUE TITLE
Kotlin 2.0.20 support

### ISSUE THREAD

**Issue by Jarvvski** [google/ksp#2047]
Kotlin 2.0.20 has been [released today](https://github.com/JetBrains/kotlin/releases/tag/v2.0.20)

No rush, but making this ticket for tracking

Can we get a version of ksp to support this, so I don't have the gradle spam 🙏🏻 

```
ksp-2.0.20-RC2-1.0.24 is too old for kotlin-2.0.20. Please upgrade ksp or downgrade kotlin-gradle-plugin to 2.0.20-RC2.
```

**Comment by danysantiago** [comment]
KSP `2.0.20-1.0.24` was just released: https://github.com/google/ksp/releases/tag/2.0.20-1.0.24

**Comment by Jarvvski** [comment]
Thanks!
