### ISSUE TITLE
Some confusion about the code implemented in the compiler-plugin

### ISSUE THREAD

**Issue by RinOrz** [google/ksp#209]
Hi, I am making extensions to the KSP source code, but in the meantime I have some doubts about the implementation of the compiler plugin:

1. I found that the acquisition of the setter and getter of the property is not accurate, even if I did not define a property with a `setter/getter`, the return result of `KSPropertyDeclaration.setter/getter` is still not null.[KSPropertyGetterSyntheticImpl.getCached(this)](https://github.com/google/ksp/blob/9e607cdc77445360ad748b4fcaa8049b9770f667/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt#L71), Is this implemented on purpose? But I’m very curious about the result returned in the implementation, because they are completely unimportant without `setter/getter`, should they always return null?

2. I found some methods that can be converted to `lazy property` in the declaration, like [KSPropertyDeclaration. isDelegated](https://github.com/google/ksp/blob/9e607cdc77445360ad748b4fcaa8049b9770f667/api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt#L58), do you agree to turn it into a `by lazy` property? Direct access to property may take less time than calling method, and the impact of parentheses on cleanliness is less written. (although this is not important)

3. There are elements of `List` in many models, but these Lists have been operated many times in the implementation. Would it be better if they were changed to `Sequence` and returned?

4. I have seen `KSName` in many models, but in some scenes, like [KSValueArgumentLiteImpl](https://github.com/google/ksp/blob/17778fcfaf4975b0bb81805c4dd9a4043e5424eb/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt#L96), [KSDeclarationImpl](https://github.com/google/ksp/blob/6ee0964f6f5620c7fbc0c579611bee6a8b6d4ace/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSDeclarationImpl.kt#L35), would it be better to change the type of `KSName` to `String`? Because we know that these names are just a simple string, no other information about `KSName` is needed at all, so not boxing the String can avoid making the api more complicated. `KSName` may also be renamed to `KSTypeName` to store information related to the type name. What do you think?

**Comment by ting-yuan** [comment]
Thanks for digging into the code! @neetopia can you comment on 1. and 4.?

2. Yes, it is possible. We'll revisit this in next quarter and decide how to trade off based on benchmark results.

3. Likewise, this is in our backlog and will be revisited in next quarter.

**Comment by neetopia** [comment]
for 1. It is intentional. The main reason for that is although an explicit accessor is not declared, kotlin compiler will still generate accessors for these properties when feasible, therefore you see there are some logic around this  `shouldCreateSyntheticAccessor` tp determine if it is needed to generate such implicit processors.
 for 4. This has been under some discussion, changing to `String` is feasible, but this is not top priority right now.
