### ISSUE TITLE
Add class initializer declaration

### ISSUE THREAD

**Issue by RinOrz** [google/ksp#211]
At present, I want to get the expression of the `init { .. }` block, but I found that there seems to be no declaration of the ClassDeclaration `Initializer` in the current version of KSP. Maybe add it?

https://github.com/google/ksp/blob/adc2efd1f6ce8165dea59e1bc556439183dde388/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt#L193-L202

**Comment by neetopia** [comment]
See #51
