### ISSUE TITLE
Release at `2.1.0-Beta1-1.0.24`

### ISSUE THREAD

**Issue by sgammon** [google/ksp#2124]
Hello esteemed KSP authors,

We really want to upgrade to Kotlin `2.1.0-Beta1`, because it has some fixes for blockers in our codebase. However, we can't upgrade, because of #2110.

The `1.0.25` release track begins at `2.1.0-Beta1`, so there is no `1.0.24` release of KSP. Could one be added?

**Comment by ting-yuan** [comment]
Let's try to fix #2110. I'd really appreciate if you could give the nightly builds a try, and/or provide a test case for #2110.
