### ISSUE TITLE
getSymbolsWithAnnotation does not return symbols from main when run in kspTest

### ISSUE THREAD

**Issue by timvahlbrock** [google/ksp#2144]
I'm trying to generate a special form of test data builders with ksp, but I have run into a problem with making both test and main scoped symbols available to ksp. As the builders are only needed during test, it would be sufficient if they are generated on kspTest. However, if I try to do that, `getSymbolsWithAnnotation` does not return any symbols from the main source set. I've read some things that ksp's scope is limited on each run to keep it fast, but I found this still quite irritating, as the other resolver methods seem to be able to resolve main classes when run during test.

**Comment by ting-yuan** [comment]
This is inherited from Kotlin's compilation model in Gradle, where the main and test source set and compiled separately. The main source set is processed and compiled first, and then the compiled binaries present in the compile classpath when the test source set is compiled. This is by design.
