### ISSUE TITLE
Fail to apply ksp before android

### ISSUE THREAD

**Issue by ting-yuan** [google/ksp#2174]
Discussion on Slack: https://kotlinlang.slack.com/archives/C013BA8EQSE/p1729789842772099

People reporting that after updating to ksp 1.0.26 they got the following error in all the modules that have the ksp line before the android one. Was not the case for as far as this project existed and the first versions of ksp.

```
> Failed to apply plugin class 'org.jetbrains.kotlin.gradle.plugin.KotlinBaseApiPlugin'.
   > Extension with name 'android' does not exist. Currently registered extension names: [ext, sonar, sonarqube, libs, versionCatalogs, projects, ksp, base, defaultArtifacts, spotless, reporting, detekt]
```

**Comment by scott-pollom** [comment]
This is caused by [this Gradle bug](https://github.com/gradle/gradle/issues/31092).

There is a workaround that should work, so I'll work on a implementing that.
