### ISSUE TITLE
Provide getSealedSubclasses

### ISSUE THREAD

**Issue by ting-yuan** [google/ksp#218]
It is fairly popular and can be optimized a little bit. May also worth integration into the whole text scan, originally for getClassDeclarationByName, when [KEEP 225](https://github.com/Kotlin/KEEP/pull/225) rolls out.

**Comment by ZacSweers** [comment]
Added food for thought - Kotlin 1.5's upcoming sealed interfaces support uses the same `sealedSubclasses` APIs for exposing information. Would be good to make sure this API supports that too
