### ISSUE TITLE
Incremental processing for classpath changes

### ISSUE THREAD

**Issue by ting-yuan** [google/ksp#223]
Currently, incremental processing is applicable when changes are limited to Kotlin and Java sources. That is the most common case in a typical change-compile-test cycle. However, it is not uncommon that large projects may organize their code into separate modules. When changes happen in other modules, KSP has to re-process current module entirely and misses incrementality.

The major tasks to make incremental processing work for classpath changes are
1. track dynamic dereferences in libraries
2. propagate the dependencies into sources

**Comment by BenSchwab** [comment]
Here is some grade-build-profiler data for some real world data on the impact of this:

We have ~1000 module project, where ~500 modules use ksp, and the rest use kapt (we avoid mixing ksp and kapt in a single module, so if any processors in a module doesn't support ksp, we use kapt).

Turning on ksp improved total clean builds by about ~6 percent, 853 seconds to 802 seconds.

However, our incremental builds when making a change in a base module (which is on almost every module's class path) is significantly worse, increasing from 51 seconds to 110 seconds

**Comment by ting-yuan** [comment]
The implementation #525 just landed, although it is disabled by default. Please try with the gradle property `ksp.incremental.intermodule=true` in the next release.
