### ISSUE TITLE
JAVA_STATIC / INNER modifiers are lost in descriptors

### ISSUE THREAD

**Issue by yigit** [google/ksp#231]
When a nested java class compiled, its JAVA_STATIC modifier is lost.

```java
public class DependencyOuterJavaClass {
    public class InnerJavaClass {}
    public static class NestedJavaClass {}
}
```

When `DependencyOuterJavaClass.NestedJavaClass` is in sources, its modifiers set includes JAVA_STATIC,
When it is coming from pre-compiled code, it does not have the JAVA_STATIC modifier.

Similarly for kotlin code, its `inner` modifier is lost:

```kotlin
open class DependencyOuterKotlinClass {
    inner class InnerKotlinClass
    class NestedKotlinClass
}
```
When `DependencyOuterKotlinClass.InnerKotlinClass` is in sources it reports INNER modifier but when it is coming from a dependency, it does not report inner.

I'm not fully sure what the solution could be because descriptors are a bit of uncharted territory.
As far as I can see, descriptor API does not have a way to read modifiers and right now KSP computes from properties of descriptors. One possible (easy) solution is to basically report INNER (based on descriptor.isInner). That does not fix the JAVA_STATIC case but at least fixes the kotlin case. It will also add `inner` to the java case which helps developer infer it.
 To fix the java case, we need to understand whether descriptor is backed by a kotlin or java :/.

https://github.com/JetBrains/kotlin/blob/master/compiler/frontend/src/org/jetbrains/kotlin/resolve/lazy/descriptors/LazyClassDescriptor.java#L155

repro test:
https://github.com/yigit/ksp/commit/f0d7e47b8c17e8b214b9339096e1a9352cd0be3d#diff-7f6e27a055a80b208a559583497b0da885a7b7601c4fbd3bf8e14a2e17692427

**Comment by ting-yuan** [comment]
Let's keep this open but lower the priority since it looks fine from Kotlin's point of view.
