### ISSUE TITLE
Support default values function metadata

### ISSUE THREAD

**Issue by Virelion** [google/ksp#268]
Currently the only info about function parameters default value is `KSValueParameter.hasDefault`.

Having information about actual function that is acting as a default value provider would be very useful.

**Comment by ting-yuan** [comment]
Can you give a concrete example on what function / information you are looking for?

IIRC compiler generates two functions for `foo(x: Int = 0)`:
1. a bridge: `foo$default(x: Int?, mask: Int)`
2. `foo(x: Int)` that expects all parameters being specified

Since processors only examine signature / skeleton of functions, what information from these implementation can be useful?

**Comment by Virelion** [comment]
Let's consider simple function
`foo(x: Int = 0)`
or
`foo(x: Int = someIntFunction())`
Right now I am able to get information that `x` parameter has default, but I am unable to see how it is initialized.
I would like to get info about the `0` constant there, or about `someIntFunction()` that is used to initialize default.

As I was reading your explenation of IIRC I realized that this might be not possible to do.

**Comment by ting-yuan** [comment]
Generally, it is not possible. In this case, `someIntFunction()` (or any arbitrary expressions) is evaluated at runtime and not available at compile / processing time.

Values in annotations are guaranteed to be compile time constant so they are available to processors. Unfortunately it is not the case for function default arguments.

**Comment by ting-yuan** [comment]
Thanks, I'm closing this for now. Please feel free to let us know if you have any ideas about the API.

**Comment by GuilhE** [comment]
> I proposed this issue, because of thing i needed in my own library, but I already found good enough workaround for that. If that is impossible to do, I guess issue can be closed.

Can you share the workaround?

**Comment by FunkyMuse** [comment]
> I proposed this issue, because of thing i needed in my own library, but I already found good enough workaround for that. If that is impossible to do, I guess issue can be closed.

Can you share what is the workaround?

**Comment by Virelion** [comment]
My general need for knowing what default argument is, was to generate `build` function for data class.

Let's say there is definition of class:
```kotlin
data class Item(
	val name: String,
	val nonDefaultArgument: String,
	val description: String? = null,
	val secondPropWithDefault: Int = 2
)
```

For this constructor hasDefault will be false for `name`, `nonDefaultArgument` and true for `description` and `secondPropWithDefault`.

Wanting to generate code for creating `Item` I did not have to know actual default.

I could generate code using copy constructor like that:

```kotlin
// function generated using KSP
fun build(): Item {
	// here all non-default parameters are passed as initial step
	var result = 
		Item(
			name = "SomeName",
			nonDefaultArgument = "nonDefaultArgument"
		) 
	
	if(/** I don't want to use default description **/)
		result = result.copy(description = "SomeNonDefaultDescription")
	
	if(/** I don't want to use default secondPropWithDefault **/)
		result = result.copy(secondPropWithDefault = 42)
	
	return result;
}
```

This technique is wasteful in terms of performance, since data class object is copied multiple times.
Also it can be only used for constructors of data classes, since `copy` function is necessary for this to work.
