### ISSUE TITLE
resolve alias type has error

### ISSUE THREAD

**Issue by iamanewofkotlin** [google/ksp#303]
```
data class Foo(

    val arrayListAlias: ArrayList<String>, // expected kotlin.collections.ArrayList 

    val arrayList: java.util.ArrayList<String> // expected java.util.ArrayList

)

```

Expect the **arrayListAlias** property `` propertyDeclaration.type.resolve().declaration.qualifiedName?.asString()  `` value is `` kotlin.collections.ArrayList   ``. 

But actual is `` kotlin.collections.ArrayList ``.

Expect the **arrayList** property `` propertyDeclaration.type.resolve().declaration.qualifiedName?.asString()  `` value is `` java.util.ArrayList   ``. 

But actual is `` kotlin.collections.ArrayList ``.

**Comment by yigit** [comment]
I think this is working as intended, though there is a similar issue where if you ask for that Java class directly,  you'll get it. https://github.com/google/ksp/issues/126.

**Comment by iamanewofkotlin** [comment]
> I think this is working as intended, though there is a similar issue where if you ask for that Java class directly, you'll get it. #126.

Thank you very much for your reply and your help.
