### ISSUE TITLE
provide a way to resolve jvm names for abstract properties

### ISSUE THREAD

**Issue by yigit** [google/ksp#337]
Right now, KSP only provides a way to get JVM names for methods (or property accessors).

Room hit a bug where people use `abstract internal val` for Room to generate its getter and Room generates it wrong because it doesn't have an accessor (hence we cannot get the JVM name).

Surprisingly, it works if kotlin code is coming from a `.class` file because there we return an accessor whereas when it is in source, KSP does not return an accessor.

Adding this bug for tracking purposes, I'll try to create a proposal, not sure if it is possible OR if will look like a reasonable API.

This might also be considered as an inconsistency bug between compiled kotlin code vs source kotlin code.

room bug: https://issuetracker.google.com/issues/181600170

**Comment by yigit** [comment]
Looks like we intentionally prevented these getters/setter:
https://github.com/google/ksp/commit/334d3180959e4e135b624b45f94a10b486e09822

Though, if we want to keep it working that way, we should probably consider removing those accessors from descriptor impl as well.

Alternatively, change `KSPropertyDeclarationImpl` to still return accessors for abstracts.

**Comment by yigit** [comment]
also, ktProperty does not have a getter setter in this case so we cannot get it w/o resolving the descriptor.

**Comment by yigit** [comment]
I tried prototyping adding getters/setter but the implementation of abstract, from that CL, seems like a big blocker not to do that.

On the other hand, if we decide not to add getter/setters to abstract properties (which i think makes sense), we should also change KSPropertyDescriptorImpl to also not return getters/setters for those properties.

I'm quite torn on the right solution at this point :shrug:

**Comment by ting-yuan** [comment]
Synthesizing abstract accessor sounds like some unnecessary performance overhead to me but I'm fine with it, since we already have a handful of similar synthetic stuffs like constructor.

@neetopia do you remember any of the background why we didn't synthesize abstract accessors?

**Comment by yigit** [comment]
btw, looks like Room relied on the `isAbstract()`  to check if a method has a default implementation:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/compiler-processing/src/main/java/androidx/room/compiler/processing/ksp/KspMethodElement.kt;l=70?q=KspMethodElement&ss=androidx

And we just returned false for synthetic getters we create for properties: (Room creates them even when KSP doesn't)
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/compiler-processing/src/main/java/androidx/room/compiler/processing/ksp/synthetic/KspSyntheticPropertyMethodElement.kt;l=64?q=KspSyntheticPropertyMethodElement

This is when we create those synthetics:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/compiler-processing/src/main/java/androidx/room/compiler/processing/ksp/KspTypeElement.kt;l=208?q=KspTypeElement
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/compiler-processing/src/main/java/androidx/room/compiler/processing/ksp/KspTypeElement.kt;l=177?q=KspTypeElement

**Comment by neetopia** [comment]
If synthetic accessors are generated for abstract class by compiler I think it's better to add it for source based symbols as well.

**Comment by yigit** [comment]
i implemented a prototype to show how it looks:
https://github.com/google/ksp/pull/338

there is still some concerns i listed in the PR (and maybe more i missed).

btw i delegated to the descriptor instead of using synthetics, could've been implemented using the synthetics as well (though i kind of like delegating to descriptors because it makes it more consistent w/ the compiled code)

**Comment by yigit** [comment]
since 338 is merged, we can close this now.
I've locally verified the repro tests in Room pass.
