### ISSUE TITLE
Support indirect referencing to resolve dependency classes

### ISSUE THREAD

**Issue by gfreivasc** [google/ksp#344]
I have a use case for annotation processing where I split it into two steps:
- Generate metadata for code that should be referenced from a single place.
- Fetch generated metadata and finally generate the class(es) that should reference the aforementioned code.

This has been proven useful for multi-module scenarios where I might want to:
- Reference code from dependency classes on the code generated on the later step.
- The later step should only run in a small subset of the modules (or only one of them).

The way I've achieved that with KAPT has been through generating that metadata on a specific package, with a dedicated annotation. Once I hit the last step, I'll fetch the generated metadata with `Elements.getPackageElement()` API. For example:

```kotlin
val metadata = processingEnv.elementUtils
      .getPackageElement("my.metadata")
      ?.enclosedElements
      ?.filter { it.getAnnotation(GeneratedMetadata::class.java) != null }
      .orEmpty()
```

The key is that this API allows me to reach dependency code *that I don't have a direct reference to*. The processor doesn't know if there are even any metadata to work with until it tries to get it. The generated metadata will have mangled names to prevent them from clashing once multiple of them are generated and simultaneously visible from a single module. The only thing I need to make sure in this case is that they're all in the same `my.metadata` package, annotated with `@GeneratedMetadata`.

What I'm asking for is a similar API. Given a common characteristic (in KAPT example, the package), allow a processor to reach code as long as it is visible to the module being compiled.

**Comment by ting-yuan** [comment]
We've been discussing ideas of `getPackageElement` but haven't have a conclusion yet. We have some concerns with regard to how to implement it efficiently. It can be slow especially when needing to include elements from dependencies.

On the other hand, could [getClassDeclarationByName](https://github.com/google/ksp/blob/master/api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt#L57) work for you?

**Comment by gfreivasc** [comment]
In my current design, this is a bit complicated since I'm mangling the names of my generated metadata classes. This means the names are randomized to avoid naming collision between different compilations. Maybe an API that returns `Collection<KSFile>` for a given package name or directory would be more cohesive. Without knowing the implementation details, `KSFile` sounds like a cheaper way to operate rather than going for `KSDeclaration`.

**Comment by neetopia** [comment]
This should be resolved with the `getDeclarationsFromPackage()` API.
