### ISSUE TITLE
Provide the ability to check if a nullable lambda parameter type has the SUSPEND modifier

### ISSUE THREAD

**Issue by AlessandroOddone** [google/ksp#354]
Given a nullable lambda parameter `KSTypeReference`, it's not currently possible to check whether the SUSPEND modifier is present or not.

In the example below, `KSTypeReference.modifiers` is empty for the "block" parameter (reflecting the `modifierList` of the underlying `KtTypeReference`). In the PSI tree, the SUSPEND modifier is attached to the `KtNullableType` `typeElement` of the `KtTypeReference` and this information seems to be lost in the KSP models.

```
fun example(
  block: (suspend () -> Unit)?
) {
}
```

**Comment by ting-yuan** [comment]
Kotlin doesn't allow modifiers (or annotations) to appear in and out of the parenthesize at the same time. A fix is on the way in #572.
