### ISSUE TITLE
Can't resolve property type when type is implicit in assignment

### ISSUE THREAD

**Issue by fondesa** [google/ksp#368]
**KSP version**: 1.4.31-1.0.0-alpha06

Using `KSValidateVisitor` (the one used by default by `KSNode.validate`), the following class can't be validated because the type of the variable `x` inside `baz()` can't be resolved.
Making `x` immutable, doesn't fix the issue.

```kotlin
@DummyAnnotation
class Foo {
  val bar: Int = 0

  fun baz(): Int {
    var x = bar
    return x
  }
}
```

Instead, specifying the type of `x` explicitly, fixes the issue:

```kotlin
@DummyAnnotation
class Foo {
  val bar: Int = 0

  fun baz(): Int {
    var x: Int = bar
    return x
  }
}
```

**Comment by gdude2002** [comment]
This is still a problem in `1.5.10-1.0.0-beta02`. Is there any way to work around this in particular? I don't need to care what functions are in the class I have annotated.

**Comment by fondesa** [comment]
@gdude2002 I've workaround it specifying the type explicitly (the last code block I posted above).

**Comment by gdude2002** [comment]
I should've been more specific - a workaround that doesn't require me to do that, haha

It'll do for now, but the beta state of KSP means an issue like this may be hanging around for some time.

**Comment by fondesa** [comment]
@gdude2002 If you don't need to look at the functions' body, I think you could use another `Visitor` which doesn't visit the functions.

**Comment by neetopia** [comment]
A workaround is posted, you can also replace the custom `predicate` in your code with the one in #479 if you don't need to validate local functions/class declared in a function body.

There is still a need to fix the implicit type resolution.
