### ISSUE TITLE
Support accessing KSP generated code in other modules

### ISSUE THREAD

**Issue by elihart** [google/ksp#372]
The use case is a multi-module project where each module generates code, and then a single root aggregates the generated results of the other modules.

Here’s an example in Showkase which generates a gallery of @Composable UI views. Data about each composable is written to a file in a hardcoded package:
https://github.com/airbnb/Showkase/blob/master/showkase-processor/src/main/java/co[…]roid/showkase/processor/writer/ShowkaseCodegenMetadataWriter.kt

Then a single module can read the generated files from all other modules to gather them together into the gallery it displays:
https://github.com/airbnb/Showkase/blob/master/showkase-processor/src/main/java/com/airbnb/android/showkase/processor/ShowkaseProcessor.kt#L235

This allows us to write composables in many modules, and then have our single application module that depends on all library modules aggregate files together and further process all of them.

With Java annotation processing we accomplished this via `Elements.getPackageElement(CharSequence)`, but since KSP does not provide an API for explore packages there is currently no equivalent in KSP.

There could be multiple ways to accomplish this in KSP, and while mirroring the Java package API would make migrating to KSP simpler it isn't necessary to use that same approach as long as KSP provides some general mechanism for accessing generated files between modules.

This is similar to https://github.com/google/ksp/issues/344

**Comment by neetopia** [comment]
Added in #377
