### ISSUE TITLE
Split Orign.CLASS into Origin.CLASS_KOTLIN and Origin.CLASS_OTHER

### ISSUE THREAD

**Issue by ting-yuan** [google/ksp#375]
So as to distinguish Kotlin and Java classes.

**Comment by neetopia** [comment]
A problem is that only parts of the descriptors have Java-specific implementations, so for the rest of descriptors, it is non-trivia to tell its library origin based on the type of descriptor.

**Comment by ting-yuan** [comment]
Fixed in #417
