### ISSUE TITLE
Where's the SymbolProcessorProvider?

### ISSUE THREAD

**Issue by wowselim** [google/ksp#391]
I wanted to migrate my annotation processing libraries to KSP but I'm having difficulties with the guides here.

The quickstart guide states the following:
> The processor you're writing needs to implement `com.google.devtools.ksp.processing.SymbolProcessorProvider`…

So I added a dependency on the library as described in the guide but I can't find the `SymbolProcessorProvider` class. I've even downloaded the jar file myself from [maven central](https://mvnrepository.com/artifact/com.google.devtools.ksp/symbol-processing/1.4.32-1.0.0-alpha07) and checked its contents and it doesn't seem to be there either.
I also downloaded a 1.4.10 version of the jar to check if it might have been there in a previous version but I didn't find it there either.

The example processor also has no references to this class. Since the quickstart guide references version 1.4.32, I had assumed it must be up to date.

How can I get hold of this class and is there an up-to-date example somewhere that I can use as a starting point?

**Comment by wowselim** [comment]
Here's the jar contents for the `processing` package that I have:
<img width="551" alt="grafik" src="https://user-images.githubusercontent.com/5699586/115146367-8261a100-a056-11eb-81c6-e76b8f84ff4b.png">

**Comment by ting-yuan** [comment]
Sorry the doc is a little bit ahead of the latest release. `SymbolProcessorProvider` was introduced a few days ago and will be available in `1.4.32-1.0.0-alpha08` this week.

To try out with `1.4.32-1.0.0-alpha07`, don't use `SymbolProcessorProvider`; The same goal is achieved by `SymbolProcessor.init()`. The doc for current release can be found [here](https://github.com/google/ksp/blob/1.4.32-1.0.0-alpha07/docs/quickstart.md).

**Comment by ting-yuan** [comment]
Closing as the newer release were out to match the docs. Please feel free to reopen or create new issues if there's any questions.
