### ISSUE TITLE
KSDeclaration.packageName returns "<root>" as the value if a class resides in the default package

### ISSUE THREAD

**Issue by mars885** [google/ksp#432]
I've stumbled upon the issue, where if a class (or any other declaration for that matter) resides in a default package (meaning no `package` statement provided), then the `KSDeclaration.packageName` returns a value of `<root>`. I expected it to provide an empty string, just like the Javac annotation processing does. Is this a bug?

**Comment by ting-yuan** [comment]
It is intended so as to prevent silent failures. The name `<root>` is chosen arbitrary though. Is there a use case where an empty string is preferred?

**Comment by mars885** [comment]
I just don't know how useful `<root>` value is. Most of the KSP use cases, I think, is code generation, which means using libraries like KotlinPoet to generate code. Obviously, KotlinPoet does not recognize `<root>` value as the default package name, which leads me to using something like this every time I need to access the package name:
```kotlin
val KSDeclaration.validPackageName: String
  get() = packageName.asString().let { 
      if(it == "<root>") "" else it
  }
```

**Comment by ting-yuan** [comment]
That makes sense. Will update.
