### ISSUE TITLE
Get annotation marked with another annotation

### ISSUE THREAD

**Issue by mars885** [google/ksp#435]
I'm having problems trying to retrieve an annotation that is marked with another annotation.

For example:
`Qualifier.java`
```java
package javax.inject;

@Target(ANNOTATION_TYPE)
@Retention(RUNTIME)
@Documented
public @interface Qualifier {}
```

`Named.java`
```java
package javax.inject;

@Qualifier
@Documented
@Retention(RUNTIME)
public @interface Named {
    String value() default "";
}
```

`Test.kt`
```kotlin
@Named("test")
class Test
```

Now i need to retrieve the annotation of the `Test` class that is itself marked with the `Qualifier` annotation (in the example, it is the `Named` annotation that I need to retrieve). This is the best I could do:
```kotlin
fun getNamedAnnotation(testClassSymbol: KSAnnotated): KSAnnotation? {
    val qualifierType = resolver.getClassDeclarationByName("javax.inject.Qualifier")!!.asType(emptyList())

    return testClassSymbol.annotations.firstOrNull { testClassAnno ->
        testClassAnno.annotationType
            .annotations  // This always returns an empty sequence
            .any { innerAnno -> it.annotationType.resolve() == qualifierType }
    }
}
```
As you can see from the comment above, whenever I try to access inner annotations of another annotation (annotations of the `@Named` annotation, in the example), I always get an empty sequence. As far as example goes, the `Named` class is present in the classpath during compilation. Why can't I retrieve its annotations then though? Does the KSP currently not support retrieving annotations from a Java class or something? Or am I doing something wrong? Thanks.

**Comment by ting-yuan** [comment]
`testClassAnno.annotationType` is a type reference / `KSTypeReference`. The annotations on `Qualifier` in this example are attached to the declaration. Therefore it (the reference) needs to be resolved (`KSType`) and the annotations can be obtained from the corresponding declaration:
```
testClassAnno.annotationType.resolve().declaration // in contrast to testClassAnno.annotationType
.annotations
.any {...}
```

**Comment by mars885** [comment]
Thanks. It seems to be working now.
