### ISSUE TITLE
Not compatible with gradle configuration cache

### ISSUE THREAD

**Issue by ursusursus** [google/ksp#448]
I ran into this

```
* What went wrong:
Configuration cache problems found in this build.

60 problems were found storing the configuration cache.
- Task `:auth:contract:kspKotlin` of type `com.google.devtools.ksp.gradle.KspTask`: cannot serialize object of type 'org.jetbrains.kotlin.gradle.tasks.KotlinCompileWithWorkers', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/6.8.2/userguide/configuration_cache.html#config_cache:requirements:task_access
```

as 4.2.1
agp 4.2.1
gradle 6.8.2
ksp com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10

**Comment by pvegh** [comment]
Same with Arctic Fox
AGP 7.0.0.beta02
Gradle 7.0

**Comment by chrisjenx** [comment]
Still seeing this on KSP 15.31-1.0.1

>kspDebugKotlin` of type `com.google.devtools.ksp.gradle.KspTaskJvm`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.3/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
