### ISSUE TITLE
Quickstart guide is outdated / misleading

### ISSUE THREAD

**Issue by wowselim** [google/ksp#460]
There are two places where the [`quickstart.md`](https://github.com/google/ksp/blob/main/docs/quickstart.md) is a bit outdated or misleading:

> The processor you're writing needs to implement com.google.devtools.ksp.processing.SymbolProcessorProvider.

This should be SymbolProcessor, not SymbolProcessorProvider.

And another instance:

> After writing your own processor, register your processor to the package by including the fully-qualified name of that processor in resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessor.

In this case it's the other way around. The filename should end with SymbolProcessorProvider, not SymbolProcessor.

**Comment by ting-yuan** [comment]
Fixed. Thanks for reporting the issue!
