### ISSUE TITLE
Generated proguard files in resources are not seen by AGP

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#464]
A developer reported that generated proguard files are not included in the final proguard/R8 configuration, which suggests some missing linkage between KSP outputs and the requisite AGP pipeline.

They've created a sample project and I've added some more details from my findings here: https://github.com/ZacSweers/MoshiX/issues/121#issuecomment-851670813

I'm not sure if this should be filed against AGP or here. AGP works with files generated by javac and kapt so I would assume it it's general use, but I could be wrong and AGP has custom handling for parsing from their outputs. CC @gavra0 for context on the AGP side. This is a mechanism used by Dagger as well.

**Comment by ZacSweers** [comment]
For anyone else that runs into this, I've posted a workaround snippet for our case here: https://github.com/ZacSweers/MoshiX/issues/121#issuecomment-851773800. It's specific to the proguard use-case, but you should be able to adapt it as-needed if you have other use cases.

**Comment by gavra0** [comment]
Generated resources are not registered with AGP, so they will not be packaged in the APK nor AGP will filter keep rules. https://github.com/google/ksp/blob/9f8d05b1af44857bc6de926d9be49e74b2c4a107/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt#L90 need to be updated to add call to `androidVariant.registerPostJavacGeneratedBytecode(FileCollection)` where `FileCollection` points to dir with generated resources.
