### ISSUE TITLE
Shouldn't SymbolProcessorProvider be a fun interface?

### ISSUE THREAD

**Issue by mars885** [google/ksp#466]
Shouldn't [SymbolProcessorProvider](https://github.com/google/ksp/blob/main/api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessorProvider.kt) be a [fun interface](https://kotlinlang.org/docs/fun-interfaces.html)? If so, would love to send a PR.

**Comment by ZacSweers** [comment]
It used to be but was removed in https://github.com/google/ksp/commit/f4e1d9155a01bc5d6e058238bb99f7550493c309, not sure why

**Comment by ting-yuan** [comment]
It's removed accidentally. Please feel free to send a PR.
