### ISSUE TITLE
KspTask does not support gradle remote cache

### ISSUE THREAD

**Issue by BenSchwab** [google/ksp#490]
We are noticing that the KSP task does not result in a remote gradle cache hit. The reported reason is that the input of `processorClasspath` is different on CI vs. local. I believe this is because the `processorClasspath` [input](https://github.com/google/ksp/blob/main/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L348) needs to be marked relative ( `@get:PathSensitive(PathSensitivity.RELATIVE)`)

Example build scan issue:
<img width="1625" alt="Screen Shot 2021-06-24 at 5 20 58 PM" src="https://user-images.githubusercontent.com/1754153/123350929-e13d0e00-d510-11eb-8796-6ac17dfb602f.png">

**Comment by ting-yuan** [comment]
Fixed in #543
