### ISSUE TITLE
`KSValueParameter` has no reference to the `KSDeclaration` where is present

### ISSUE THREAD

**Issue by gmazzo** [google/ksp#503]
A few weeks ago, I've reported this issue https://github.com/google/ksp/issues/351 regarding the lack of `KSValueParameter` on `getSymbolsWithAnnotation`.

Today we just discovered a very strange behavior regarding incremental compilation, where the generated classes were missing after the second run.

After a deep research, we realized the root cause was this peace of logic here (that we have in our code):
```kotlin
 environment.codeGenerator.createNewFile(
            dependencies = Dependencies(
                aggregating = true,
                sources = source
                    .flatMap { it.sources }
                    .mapNotNull { (it as? KSDeclaration)?.containingFile }
                    .distinct()
                    .toTypedArray()
            ),
```
So, as you may note, `KSValueParameter` can never be cast to `KSDeclaration` (which makes sense) but only `KSDeclaration` contains a `KSFile` instance to be used in the `Dependencies`.

We need a way in the API to be able to map `KSValueParameter` to a `KSFile` and right now it doesn't seems to have one right? 

My suggestion will be to add something like:
```kotlin
interface KSValueParameter : KSAnnotated {

     /**
      *  The reference to the function declaring this parameter.
      */
     val function: KSFunctionDeclaration
```

**Comment by neetopia** [comment]
fixed in #573
