### ISSUE TITLE
getJvmCheckedException does not work for already compiled files

### ISSUE THREAD

**Issue by yigit** [google/ksp#507]
Looks like the method body in ResolverImpl returns emptySequence for element that in classpath.

This is critical for Room because we override kotlin methods in Java, hence we would need to get thrown types to produce the right code when the code under question is obtained from classpath (happens when a database refers to a Dao coming from a dependency)

**Comment by yigit** [comment]
Looks like this is still broken for constructors in `java` sources.

You can reproduce the failure but adding `lib` to the list of packages in this test:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler-processing/src/test/java/androidx/room/compiler/processing/XExecutableElementTest.kt;l=773?q=XExecutableElementTest&ss=androidx%2Fplatform%2Fframeworks%2Fsupport

It now works for pre-compiled kotlin files but does not work for pre-compiled java constructor. (works for the java method though)

**Comment by yigit** [comment]
also, it is not working for accessors (same test reproduces the problem)

```
@get:Throws(IllegalArgumentException::class)
                    val getterThrows: Int = 3
                    @set:Throws(IllegalStateException::class)
                    var setterThrows: Int = 3
                    @get:Throws(IOException::class)
                    @set:Throws(IllegalStateException::class, IllegalArgumentException::class)
                    var bothThrows: Int = 3
```

each accessor for these return emtylist.

FYI both these cases work well for source files.

**Comment by yigit** [comment]
oh wait, actually i think i confused with https://github.com/google/ksp/issues/505, let me check again for the accessors.

**Comment by neetopia** [comment]
NVM, forgot it is for constructor.
