### ISSUE TITLE
Execution optimizations have been disabled for task ':foo:kspKotlin' to ensure correctness due to the following reasons:

### ISSUE THREAD

**Issue by ursusursus** [google/ksp#526]
Hi, I'm seeing this warnings, wondering what they are 

```
> Task :user:impl:kspKotlin
Execution optimizations have been disabled for task ':user:impl:kspKotlin' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'C:\Users\ursus\AndroidStudioProjects\mo2-android\user\impl\build\generated\sqldelight\code\AppDatabase'. Reason: Task ':user:impl:kspKotlin' uses this output of task ':user:impl:generateMainAppDatabaseInterface' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.1.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

warning comes from a module whose build file looks like

```
apply plugin: "kotlin"
apply plugin: "com.google.devtools.ksp"
apply plugin: "com.squareup.anvil"
apply plugin: "com.squareup.sqldelight"

anvil {
    generateDaggerFactories = true
}

sqldelight {
    AppDatabase {
        packageName = "sk.o2.user"
    }
}

dependencies {
    implementation deps.moshi.client
    ksp deps.moshi.kspCompiler
    implementation deps.dagger.runtime
}
```

SqlDelight afaik doesn't use ksp so its surprising
(gradle 7.1.1, kotlin 1.5.20, ksp 1.5.21-1.0.0-beta05, sqldelight 1.5.1)

**Comment by ting-yuan** [comment]
Do you know where `:user:impl:generateMainAppDatabaseInterface` comes from and what contents it generate? E.g., the output directory, whether they are classes/jars, Java or Kotlin source files, etc.

It's a bit scary to me that KSP picks up something that appears to be generated. There might be some unexpected interaction with other Gradle plugins.

**Comment by ursusursus** [comment]
it comes from sqldelight if youre familiar https://github.com/cashapp/sqldelight

But I have no idea about their plugin internals, just a quick google gives me this I think is it

https://github.com/cashapp/sqldelight/blob/9f9c3adeb17e4240a686484287cdd52cb0e75b00/sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt#L138``

**Comment by ursusursus** [comment]
@ting-yuan btw this disables config cache for the tasks, yielding config cache still not really working

**Comment by ting-yuan** [comment]
After reviewing relevant implementations, it looks like that the output comes from Kotlin source set dependencies. The output of sqldelight could be added as a dependency to sourceSet either manually or by sqldelight. @gavra0 recommended pulling the source set from `KotlinExtension`, instead of `KotlinCompilation`, from which source sets are modifiable by other plugins. I'm going to prepare a patch base on that idea.

@ursusursus would you mind to provide a test case so that I can verify whether the patch works or not?

**Comment by ursusursus** [comment]
I think sqldelight already fixed it https://github.com/cashapp/sqldelight/pull/2518/files

**Comment by ting-yuan** [comment]
Thank you. I'm closing this for now. Feel free to reopen if any question.

I opened #550 for letting users control whether KSP should pick up source from `build` or not.
