### ISSUE TITLE
Resolving symbols with annotation from another module

### ISSUE THREAD

**Issue by kiryldz** [google/ksp#527]
Imagine we have following Android multi-module structure:

1. KSP `:test-processor` module configured correctly.
2. Base module `:base` that has following `build.gradle.kts`:
```
plugins {
  id("com.android.library")
  kotlin("android")
  id("com.google.devtools.ksp")
  ...
}

dependencies {
  api(project(":test-processor"))
  ksp(project(":test-processor"))
  ...
}
```
3. Another module `:module` that implements `:base` and has following `build.gradle.kts`:
```
plugins {
  id("com.android.library")
  kotlin("android")
  ...
}

dependencies {
  implementation(project(":base"))
}
```

`:test-processor` module contains e.g. following annotation class:
```
@Target(AnnotationTarget.CLASS)
annotation class TestKspAnnotation
```

If I create some class inside `:base` module and annotate it with `@TestKspAnnotation` - code gets generated as expected in `base/build/generated/ksp/debug/kotlin/Generated.kt`.

However if I created some class inside `:module` and annotate it with `@TestKspAnnotation` - code compiles OK but no code gets generated. I assume it happens because parsing happens per-module basis. 

What would be the best solution to make such config work? From user perspective it would be convenient if `resolver.getSymbolsWithAnnotation(...)` could somehow work not per-module basis.

**Comment by ting-yuan** [comment]
Like compilation, exactly one module is passed to a processor in a single invocation. There is no way to process two modules at once by design; Reasons include simplicity and efficiency. On the other hand, if you already know what to look at in another module, e.g., interfaces, you can navigate through sources in current module.

**Comment by kiryldz** [comment]
Thanks for clarification!
