### ISSUE TITLE
API for obtaining default annotation class argument value aka ExecutableElement.getDefaultValue()

### ISSUE THREAD

**Issue by Jeffset** [google/ksp#542]
As I see in the [reference](https://github.com/google/ksp/blob/main/docs/reference.md), this API is not yet implemented. I've written an annotation processor a while back which makes use of `ExecutableElement.getDefaultValue()` and I'm considering supporting KSP.
Let this be a tracking issue for this API status.

**Comment by jameskleeh** [comment]
@Jeffset can you confirm the second PR mentioned here resolves your use case?

**Comment by Jeffset** [comment]
> @Jeffset can you confirm the second PR mentioned here resolves your use case?

Yes, API looks legit, thank you!

**Comment by jameskleeh** [comment]
@Jeffset You can close this its been merged

**Comment by Jeffset** [comment]
We also should document the new API in this [reference](https://kotlinlang.org/docs/ksp-reference.html#executableelement).
