### ISSUE TITLE
Using KSP with Kotlin Multiplatform

### ISSUE THREAD

**Issue by kamilr12** [google/ksp#60]
Hi,

I am not able to use this api with Multiplatform projects. It works with Kotlin/JVM. Can you explain how to use custom processors in multiplatform projects?

**Comment by Virelion** [comment]
Launching KMP JVM ksp is blocked now only by simple NPE.
Here PR with fix: https://github.com/google/ksp/pull/243
Can anyone review it?

**Comment by ting-yuan** [comment]
K/N is now supported by #541

**Comment by PhilipDukhov** [comment]
Should it be ready to test for iOS on `1.5.21-1.0.0-beta07`? 

I've tried following [integration-tests/src/test/resources/kmp](https://github.com/google/ksp/tree/main/integration-tests/src/test/resources/kmp)

And I'm adding it to my module like [this](https://github.com/PhilipDukhov/KMPKSPTest/blob/2345e94f62f9285b3aea4a9f736c06c411e63a63/shared/build.gradle.kts#L31):
```
val commonMain by getting {
    dependencies {
        configurations.get("ksp").dependencies.add(project(":test-processor"))
    }
}
```
On which I'm getting following sync error:
`org.gradle.api.InvalidUserDataException: Cannot change dependencies of dependency configuration ':shared:kotlinCompilerPluginClasspathIosMain' after it has been resolved.`

My [sample project](https://github.com/PhilipDukhov/KMPKSPTest) based on a clean KMP project

**Comment by atsushieno** [comment]
It is because `commonMain` block iterates for every platform, while keeping `ksp` dependencies. My project built with this conditional addition:

```
                if (configurations.get("ksp").dependencies.all { p -> p.name != ":myprocessor" })
                    configurations.get("ksp").dependencies.add(project(":myprocessor"))
```

**Comment by PhilipDukhov** [comment]
@atsushieno Tried pasting into my [sample project](https://github.com/PhilipDukhov/KMPKSPTest), in my case `configurations.get("ksp").dependencies.count()` returns 0, so this solution doesn't work :(

**Comment by ting-yuan** [comment]
A tentative fix is on the way in #568. I haven't been able to reproduce it, though.

**Comment by atsushieno** [comment]
@PhilipDukhov Well, try changing the condition like "! any{...}" ? It's just standard Kotlin programming over collection.

**Comment by PhilipDukhov** [comment]
@atsushieno in my case this code only called once, and dependencies is empty, so `all` or `! any` cannot help much here. Hope #568 will work

**Comment by ting-yuan** [comment]
I can reproduce with @PhilipDukhov's sample project now and verified that #568 fixes it. Thanks to @natario1's investigation, this is reproducible with Android Studio.
