### ISSUE TITLE
Can I get the property default value with KSP?

### ISSUE THREAD

**Issue by tbruceyu** [google/ksp#642]
I hava a class like below:
`
class FooClass(
    val propertyInt: Int = 123,
    val propertyInt: String = "123"
)
`
How can I get the 123 and "123" in KSP？

**Comment by neetopia** [comment]
Evaluating expression in the source code is expensive and is not generally supported by KSP. It is only available for annotation argument values. If your use case requires expression evaluation, consider make the value in annotation value.

**Comment by tbruceyu** [comment]
> Evaluating expression in the source code is expensive and is not generally supported by KSP. It is only available for annotation argument values. If your use case requires expression evaluation, consider make the value in annotation value.

OK, Thank you.
