### ISSUE TITLE
KSP does not generate files on subsequent builds

### ISSUE THREAD

**Issue by Morfly** [google/ksp#654]
I'm facing an issue when I'm trying to build a JVM project with Gradle from the command line.

The issue is the following:
When I'm trying to build a project using `./gradlew my-project:run` command for the first time - the code generation works perfectly fine.
However, when I run the same command for the second time - my symbol processor does not generate any file and therefore, I'm having a compilation error (unresolved references for all the code generated by KSP).
If I run `./gradlew clean` and then use `./gradlew my-project:run` again - it runs successfully but all subsequent builds would be failed again.

In addition, I can successfully build the project with IntelliJ IDEA by marking a `build/generated/ksp` directory as a `sourceSet` in Gradle. However, after the build failure described above - I'm having the same compilation error even when I try to build the project using IDEA. In order to fix this, I need to update the source file that contains the usage of an annotation that is handled by my processor (I can just add a blank space). After that, I can successfully build the project again with the IDE.

The sample project I'm using could be found here: https://github.com/Morfly/ksp-sample/tree/codegen_issue

### Steps to reproduce (in the sample project):
1. `cd completed`
2. `./gradlew clean`
3. `./gradlew main-project:run` - should run successfully.
4. `./gradlew main-project:run` - here is the issue. After the second build, it fails for me and the `main-project/build/generated/ksp` folder is empty.
5. Run the project with IntelliJ IDEA - fails for the same reason.
6. Edit the `main-project/src/main/.../Main.kt` file (can just add a blank space).
7. Run the project again with IntelliJ IDEA - the project builds successfully again.

Note. If using only in the command line (without IDE), step 6 does not work and the error still exists.

**Comment by haizerdev** [comment]
+++, i has the same problem in Android studio

**Comment by ting-yuan** [comment]
Thanks for the sample project! It really helps the investigation.

KSP tracks inputs and outputs and manage outputs accordingly. In the sample project, the output file [isn't associated](https://github.com/Morfly/ksp-sample/blob/codegen_issue/completed/processor/src/main/kotlin/com/morfly/FunctionProcessor.kt#L61) with any of the sources. Therefore it is not kept / maintained across builds.

Adding sources should make the issue away, for example:
```
val file = codeGenerator.createNewFile(
    dependencies = Dependencies(false, *resolver.getAllFiles().toList().toTypedArray()),
    packageName = "com.morfly",
    fileName = "GeneratedFunctions"
)
```

Here are more details of KSP's incremental model:
https://github.com/google/ksp/blob/main/docs/incremental.md
