### ISSUE TITLE
Add ability to retrieve default values from annotation members

### ISSUE THREAD

**Issue by jameskleeh** [google/ksp#674]
I'm in the beginning stages of writing an implementation of Micronaut's compile time features using KSP. Micronaut stores annotation data in classes that get created at compile time through a custom API called AnnotationMetadata. That API allows us to read annotations at runtime without using runtime reflection.

 To reduce memory usage at runtime, default values of annotation members are not stored every time the annotation is used. Instead the default values are stored a single time per annotation. 

To support this use case I would need the following:

- A way to retrieve the default values for a given annotation
- The ability determine if the value coming from `KSValueArgument` is because of the default value or because it is actually set

Please let me know if I can be of any assistance. Thank you!

**Comment by Jeffset** [comment]
Would this be solved by the API requested in #542?

**Comment by jameskleeh** [comment]
@Jeffset Perhaps partially, however that wouldn't cover the case of needing to know if the value in an annotation was set or is the default value.

**Comment by Benjoyo** [comment]
I am looking for the same feature. I need to know whether the annotation property is set or not. Right now I have to compare the value to the default value.
