### ISSUE TITLE
Cherry-pick recent bug fixes for Kotlin 1.5.31

### ISSUE THREAD

**Issue by saket** [google/ksp#704]
Hey folks, would you consider publishing Kotlin 1.5.31 compatible builds with bug fixes cherry-picked from `1.6.0-RC`? Updating Kotlin is really painful in multiplatform projects and it takes weeks/months before all third-party libraries are ready for a new version.

For example, there's one [bug](https://github.com/evant/kotlin-inject-samples/pull/3) in ksp 1.0.0 that's preventing me from using [kotlin-inject](https://github.com/evant/kotlin-inject). It'd be really nice if I can update to ksp 1.0.1 without waiting for kotlin 1.6.0.

**Comment by ting-yuan** [comment]
@neetopia Publishing 1.5.31-1.0.1-RC manually sounds good to me. Some non-trivial git operations are needed though. We should keep KSP next release branch stay with Kotlin stable release in the future (by giving up the Kotlin-RC-KSP-RC combination, which seems less useful compared to Kotlin-stable-KSP-RC and Kotlin-RC-KSP-stable).

**Comment by saket** [comment]
> Updating Kotlin is really painful in multiplatform projects and it takes weeks/months before all third-party libraries are ready for a new version.

I'd like to make a correction: it seems like I'm able to use Kotlin 1.6.0-RC with kotlin/native libraries compiled against 1.5.31. However it's very unstable and issues like ([this](https://youtrack.jetbrains.com/issue/KT-49581)) make it impossible for daily usage right now.

**Comment by saket** [comment]
Thanks team! https://github.com/google/ksp/releases/tag/1.5.31-1.0.1
