### ISSUE TITLE
Whether KSP supports projects built with Gradle scripts instead of KTS?

### ISSUE THREAD

**Issue by wangkunhui** [google/ksp#708]
I have a project that uses Gradle scripts, can I use KSP if I don't migrate to KTS?

**Comment by neetopia** [comment]
By gradle script do you mean `.gradle` build scripts? If so, yes it is supported, you can checkout `Setup using Groovy` section in [quickstart](https://github.com/google/ksp/blob/main/docs/quickstart.md).

**Comment by thegarlynch** [comment]
But does it support making your own KSP processor using groovy ?

**Comment by ting-yuan** [comment]
KSP processors should work as long as they are JVM compatible. Source language doesn't matter.

**Comment by thegarlynch** [comment]
hmm... i think there should be groovy documentation on the [quickstart](https://github.com/google/ksp/blob/main/docs/quickstart.md)
