### ISSUE TITLE
JVM modifiers from externally-compiled classes are not modeled in KSModifierListOwner.modifiers

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#710]
Consider this example

`BaseClass` is compiled in module A

```kotlin
abstract class BaseClass {
  @Transient private var lastSet: Boolean = false
}
```

`SubClass` is compiled in module B. Module B depends on module A

```kotlin
class SubClass : BaseClass() {

}
```

When processing `SubClass`, it's impossible to know that `BaseClass.lastSet`'s `KSPropertyDeclaration` is transient. The `@Transient` annotation is SOURCE only, and its `KSPropertyDeclaration.modifiers` does not contain `Modifier.JAVA_TRANSIENT`.

![image](https://user-images.githubusercontent.com/1361086/140159647-cacebc73-98af-410f-a891-c209e6730bc7.png)

**Comment by ZacSweers** [comment]
Confirmed `volatile` is also not carried over

**Comment by ting-yuan** [comment]
#712 introduced a new API in `Resolver` to solve this
`fun effectiveJavaModifiers(declaration: KSDeclaration): Set<Modifier>`
