### ISSUE TITLE
please add ksp-1.6.0-1.0.1 build 

### ISSUE THREAD

**Issue by slavonnet** [google/ksp#713]
please add ksp-1.6.0-RC2-1.0.1-RC build 
and add auto action

**Comment by slavonnet** [comment]
https://github.com/JetBrains/kotlin/releases/tag/v1.6.0

**Comment by neetopia** [comment]
we have released 1.6.0-1.0.1 [here](https://github.com/google/ksp/releases/tag/1.6.0-1.0.1)
