### ISSUE TITLE
Code generates successfully but disappears on application run

### ISSUE THREAD

**Issue by unredundant** [google/ksp#738]
Hi... Very cool project!  Unfortunately, something is wrong with the Gradle plugin (or my code) that causes ksp files to build successfully, but completely disappear on run 😞 

# Details

I can run `./gradlew kspKotlin` and will see the expected files in my `build` dir.

<img width="398" alt="Screen Shot 2021-11-21 at 9 48 33 AM" src="https://user-images.githubusercontent.com/5607577/142766725-3ad9ce54-ee63-48f1-b3b4-80ea81d42428.png">

Great! Unfortunately, when I try to actually _run_ the application (either through IntelliJ or through the Gradle CLI), these files completely disappear.

When running `./gradlew playground:run` it errors out immediately, and as you can see the files no longer exist. 

<img width="1178" alt="Screen Shot 2021-11-21 at 9 51 18 AM" src="https://user-images.githubusercontent.com/5607577/142766830-8e030a6c-b13a-458f-8315-0ddee3d2ac7d.png">

I have _no_ idea why this is happening, and am not even really sure of a best path to start triaging this.  It seems like all the necessary steps are performed when I run the project, as looking at the Gradle output I see 

```
...
> Task :stoik-playground:kspKotlin

> Task :stoik-playground:compileKotlin FAILED
```

when the run task is performed.

But no files exist 😢 

Any insight / help would be appreciated! 

In case it is helpful, here is the Gradle file where the problem is happening.  If you need more Gradle info let me know, I'm leveraging a couple things like multi module builds along with the `buildSrc` folder for common app conventions, so this file is relatively bare bones. 

```kotlin 
plugins {
  id("kotlin-application-conventions")
  id("com.google.devtools.ksp") version "1.6.0-1.0.1" // todo move to buildSrc... processor plugin?
}

dependencies {
  ksp(projects.stoikExposedProcessor)
  implementation(projects.stoikExposedCore)

  ksp(projects.stoikKtorProcessor)
  implementation(projects.stoikKtorCore)
}

kotlin {
  sourceSets.main {
    kotlin.srcDir("build/generated/ksp/main/kotlin")
  }
  sourceSets.test {
    kotlin.srcDir("build/generated/ksp/test/kotlin")
  }
}

application {
  @Suppress("DEPRECATION")
  mainClassName = "io.bkbn.stoik.playground.MainKt"
}
```

###  Build Info

Kotlin: `1.6`
KSP: `1.6.0-1.0.1`
Java: `1.8`

**Comment by zkw012300** [comment]
Hello @unredundant
I have encountered this problem before and solve it by reading [doc](https://github.com/google/ksp/blob/main/docs/incremental.md#incremental-processing).

According to the doc, it said that **a processor needs to associate an output with the sources of the corresponding KSNode**. So I use `addOriginatingKSFile` to associate an output with the sources like this (I use kotlinpoet to codegen):

```
TypeSpec
    .classBuilder("FooTypeAdapter")
    .addOriginatingKSFile(ksClass.containingFile)
    .build()
```


Hope my experience can help you

**Comment by unredundant** [comment]
Ah, you are an absolute hero 🙏 

I was not able to get the code snippet to work, as the only available function I see on a TypeSpec is `addOriginatingElement` which leads to some rabbit hole with Javax Elements that I don't really want to figure out at the moment :) I'm assuming this is just me being ignorant with that particular interfaces and the KotlinPoet specification.  

However, the docs you pointed me towards had a great temporary solution, which is to simply turn off incremental processing.  

Thanks again!!

**Comment by AntsyLich** [comment]
> Hello @unredundant I have encountered this problem before and solve it by reading [doc](https://github.com/google/ksp/blob/main/docs/incremental.md#incremental-processing).
> 
> According to the doc, it said that **a processor needs to associate an output with the sources of the corresponding KSNode**. So I use `addOriginatingKSFile` to associate an output with the sources like this (I use kotlinpoet to codegen):
> 
> ```
> TypeSpec
>     .classBuilder("FooTypeAdapter")
>     .addOriginatingKSFile(ksClass.containingFile)
>     .build()
> ```
> 
> Hope my experience can help you

@spirytusz take a virtual hug
