### ISSUE TITLE
kspJs failing with "Collection has more than one element." when processing code in commonMain

### ISSUE THREAD

**Issue by janvladimirmostert** [google/ksp#744]
I'm testing out KSP on a multiplatform setup, but it's failing when I add `kspJs`

kspJvm works fine, as soon as I add kspJs, it fails with  "Collection has more than one element."

```
dependencies {
	add("kspJvm", "io.jvaas:jvaas-observe")
	add("kspJs", "io.jvaas:jvaas-observe")
}
``` 

> 
> Execution failed for task ':applications:od-server:compileProductionExecutableKotlinJs'.
> > Failed to calculate the value of task ':applications:od-server:compileProductionExecutableKotlinJs' property 'entryModule$kotlin_gradle_plugin'.
>    > Collection has more than one element.

I've added detailed code-snippets on StackOverflow:
https://stackoverflow.com/questions/70139266/ksp-on-kotlin-multiplatform-fails-on-the-kspjs-with-collection-has-more-than-on

and also a code sample that can reproduce the error:
https://github.com/janvladimirmostert/observable-demo

**Comment by ting-yuan** [comment]
The fix will be available in 1.0.2.

**Comment by ting-yuan** [comment]
Btw, It looks to me that this only happens with `js(IR)`. As a workaround, could you please try to use `js()`/`js(LEGACY)` instead of `js(IR)`?

**Comment by janvladimirmostert** [comment]
looking forward to try out 1.0.2, thanks @ting-yuan !

js legacy doesn't generate the TypeScript headers which means I can't use the generated JavaScript in external TypeScript projects. Since this is for demo-purposes only, it's not mission critical that it works, there are other ways to do what I want to do for my Kotlin talk.

**Comment by mdietrichstein** [comment]
Thanks for fixing the issue @ting-yuan!

Just wanted to chime in and say that the project I'm working on also requires IR due to Typescript, but the feature is not a high priority one right now.
