### ISSUE TITLE
databinding will be support?

### ISSUE THREAD

**Issue by Hynsn** [google/ksp#745]
databinding maybe can support? maybe is not right.

**Comment by neetopia** [comment]
for existing processor adoption, it is better to reach out to the developers of the processor you are looking for.

**Comment by colinrtwhite** [comment]
Yigit has said on Twitter this isn't going to be supported: https://twitter.com/yigitboyar/status/1447408905240264704

**Comment by Hynsn** [comment]
thank you, understand Yigit' s reply.
