### ISSUE TITLE
Null default value for an annotation argument of an inner annotation type

### ISSUE THREAD

**Issue by Udinic** [google/ksp#784]
Example:
// Java
public @interface InterestingAnnotation {
  @interface LevelOfInterest {
    boolean forEveryone() default false;
  }

  LevelOfInterest level() default @LevelOfInterest();
}

// Kotlin
@InterestingAnnotation
class KotlinTestClassKsp {}

When trying to get the argument values of InterestingAnnotation, I'll get a null value for the "level()" argument.

I noticed that if the annotation is declared in a separate module (Origin of its declaration is JAVA_LIB) - this works.

I tested this with 1.0.2.
Looks related to #692, but maybe it's not covering this specific case.

**Comment by neetopia** [comment]
fixed by #836
