### ISSUE TITLE
KSPLogger does not print to console when logging or info are called

### ISSUE THREAD

**Issue by KarimFikani** [google/ksp#805]
As the title says when using KSPLogger to print out some debugging info only "warn" and "error" were printing out to built output but when I used "logging" or "info" nothing was being printed. 

How am I using it?

in the provider class I'm injecting the logger class that I get from SymbolProcessorEnvironment into the SymbolProcessor class.
I just call logger.logging on the first line of the process function.

I'm running on:
- "1.6.10-1.0.2" for "com.google.devtools.ksp"
- "1.6.10" for  "kotlin-gradle-plugin"
- "7.0.4" for "gradle" on Android

**Comment by neetopia** [comment]
You need to adjust your gradle logging level to see the logs with `logging` or `info` logging level, try to run Gradle with `--info` flag to see all logs.

**Comment by KarimFikani** [comment]
yep that fixed it! thank you!
