### ISSUE TITLE
Symbol processors do not visit classes in the test sourceset

### ISSUE THREAD

**Issue by jameskleeh** [google/ksp#806]
I have a symbol processor in `src/main/kotlin` and I would like to have classes in `src/test/kotlin` to be visited by my processor in order to test its functionality

**Comment by ting-yuan** [comment]
Have you tried adding `kspTest(project)` in `build.gradle[.kts]`?

**Comment by trevjonez** [comment]
> Have you tried adding `kspTest(project)`? E.g.,
> ```
> // build.gradle.kts
> 
> plugins {
>     ...
>     id("com.google.devtools.ksp")
> }
> 
> dependencies {
>     ...
>     kspTest(project)
> }
> ```

Can confirm this is the way to do it. 

Mixed with https://github.com/tschuchortdev/kotlin-compile-testing it works great

**Comment by jameskleeh** [comment]
@ting-yuan There are not multiple projects. There is a single project and thus it cannot declare a dependency on itself since the classpath automatically works that way. Note that this is possible with annotation processors and Groovy AST for example. It should also be possible with KSP

**Comment by trevjonez** [comment]
It has worked fine for me since before ksp 1.0 and gradle will inform you if you create a cyclic dependency. 
You are putting a dependency from the ksp test processor classpath onto the default output of the project so it doesn't become a cyclic dependency at the configuration/task level.

Example of a build scan from such a setup:
![image](https://user-images.githubusercontent.com/5386503/151721137-d1e65c29-2330-4e07-a69a-659ed326db98.png)

**Comment by jameskleeh** [comment]
@trevjonez What has worked fine? I'm not concerned about a cyclic dependency. I think that for a given single project, the visitors in the main sourceset should visit classes in the test sourceset.

**Comment by ting-yuan** [comment]
@jameskleeh The sample is intended to be used within the same build.gradle[.kts] / project where the processor sits. The `project` in `kspTest(project)` has no parameter; It references to the current project.

**Comment by jameskleeh** [comment]
@ting-yuan I see - I'll give that a try. Thanks for the clarification!

**Comment by jameskleeh** [comment]
Can confirm this does indeed work. Thanks for the help!
