### ISSUE TITLE
Extended Java interface defines Any as a supertype

### ISSUE THREAD

**Issue by jameskleeh** [google/ksp#815]
Consider the following:

Named.java
```
public interface Named {
    String getName();
}
```

Test.kt
```
interface Test : Named {
    fun setName(name: String)
}
```

In this case getting the class declaration for `Named` then calling superTypes will return a single super type `Any`. This is different from Kotlin classes where super types would be empty. I understand that this is likely because all Java classes extend from Object, but the behavior being different for classes compiled with Java compared to Kotlin makes working with KSP more difficult because you have to exclude Any when working with super types under this condition. You have to exclude Object when looking at super types when working with Java annotation processors, but at least it's consistent.

I think if `Any` is listed as a super type for Java classes it should also be for Kotlin classes as well, or neither of them should report `Any` as a super type

**Comment by glureau** [comment]
Testing the 1.6.20-1.0.5 and a bit surprised to have this new behavior. (from https://github.com/google/ksp/pull/917#issue-1186930785 )

It means that given a Kotlin `interface Foo`, superTypes will return `kotlin.Any`... But an interface cannot inherit from a class so it cannot inherit from `kotlin.Any` right? So now, I've the same issues than @jameskleeh but with Kotlin interfaces too, where I need to ignore those `kotlin.Any` when retrieving superTypes. Did I miss something?

**Comment by glureau** [comment]
As discussed [here](https://kotlinlang.slack.com/archives/C013BA8EQSE/p1650572505047039?thread_ts=1650570717.987699&cid=C013BA8EQSE), it's actually intended.
