### ISSUE TITLE
Multi-modules: superTypes doesn't return the super types

### ISSUE THREAD

**Issue by glureau** [google/ksp#831]
I'm processing an interface (with generics) from another module, this interface extends another interface (also with generics), I can get the properties & functions from the super but superTypes and getAllSuperTypes() returns nothing.

---

SSCCE: https://github.com/glureau/ksp-kmp-issues/tree/ksp_multimodule_supers
Slack: https://kotlinlang.slack.com/archives/C013BA8EQSE/p1641980604009600

(KSP 1.6.0-1.0.2)

### Processing from same module: OK

Given an interface extending another interface in `mymodule` ([Base.kt](mymodule/src/commonMain/kotlin/ksp/example/Base.kt))

```
package ksp.example

@MyAnnotation
interface Base<T> {
    fun provide(): T
}

@MyAnnotation
interface Advanced<T> : Base<T>

```

Using KSP on the `mymodule` will properly resolve `Advanced` super.

```
> Task :mymodule:kspKotlinMetadata
> w: [ksp] Supers of Advanced: 1
```

---

# Processing from another module: KO

If I wrote another module and define an annotation that points to `Advanced` class ([here](anothermodule/src/commonMain/kotlin/ksp/example/FooBar.kt))

```kotlin
@file:MyFileAnnotation(
    klass = Advanced::class
)

package ksp.example

```
And if I define my [processor](compiler/src/main/kotlin/ksp/example/Compiler.kt) this way:

```kotlin
        resolver.getSymbolsWithAnnotation(MyFileAnnotation::class.java.name).forEach {
            it.accept(object : KSVisitorVoid() {
                override fun visitFile(file: KSFile, data: Unit) {
                    file.annotations.forEach { ksAnnotation ->
                        val klass = ksAnnotation.getArg<KSType>(MyFileAnnotation::klass)
                        val classDeclaration = klass.declaration as KSClassDeclaration
                        environment.logger.warn("From another module - Supers of ${classDeclaration.simpleName.asString()}: ${classDeclaration.superTypes.count()}")
                    }
                }
            }, Unit)
        }
```

then it's logging that Advanced have no supers.

>[ksp] From another module - Supers of Advanced: 0

I was expecting to found the Base class here, like for the 1st example.

**Comment by glureau** [comment]
Just confirmed it's still present on 1.6.20-1.0.4.

I also noticed annotations from another module is not reachable. I'm thinking it could be the same issue, but tell me if you want a new issue with a reproducer.

**Comment by glureau** [comment]
Thank you @neetopia !

>I also noticed annotations from another module is not reachable. I'm thinking it could be the same issue, but tell me if you want a new issue with a reproducer.

Do you know if your fix also covers the annotations issue? (I've updated the [reproducer](https://github.com/glureau/ksp-kmp-issues/tree/ksp_multimodule_supers) to showcase that.)

**Comment by neetopia** [comment]
Can you describe this issue in more details? It is unclear to me what's annotations being not reachable.

**Comment by glureau** [comment]
In this [file](https://github.com/glureau/ksp-kmp-issues/blob/ksp_multimodule_supers/mymodule/src/commonMain/kotlin/ksp/example/Base.kt) there is a class `Container` that has a property of type `Base`. `Base` is an interface annotated with `@MyAnnotation`.

```kotlin
@MyAnnotation
fun interface Base<T> {
    fun provide(): T
}

class Container {
    var base: Base<Int> = Base { 42 }
}
```

If my compiler [here](https://github.com/glureau/ksp-kmp-issues/blob/ksp_multimodule_supers/compiler/src/main/kotlin/ksp/example/Compiler.kt#L41) visit `Container` properties from another module, it sees the property but cannot resolve the annotation on it.

    classDeclaration.getAllProperties().firstOrNull()?.type?.resolve()?.annotations?.joinToString { it.shortName.asString() }
    
I feel like it should show `@MyAnnotation`.

**Comment by neetopia** [comment]
Can you check if this issue is still present in 1.6.20-1.0.5? If so, please create a new issue for tracking and I will address it soon.

**Comment by DVDAndroid** [comment]
This release fixes [this issue I reported on Slack](https://kotlinlang.slack.com/archives/C013BA8EQSE/p1640588401271400)

**Comment by glureau** [comment]
I checked with 1.6.20-1.0.5 and finally found a mistake on my code. I was searching for annotation on the KSPropertyDeclaration instead of the `declaration` (KSDeclaration).

Bad (for what I was searching):

    classDeclaration.getAllProperties().forEach { prop -> prop.type.resolve().annotations }

Good:

    classDeclaration.getAllProperties().forEach { prop -> prop.type.resolve().declaration.annotations }

If you've time, I'd be glad to understand what's the first case is actually for. `prop.annotations` means annotations of the properties, but I don't understand what `prop.type.resolve().annotations` is actually targeting... or if it makes sense at all 🤔 

Anyway, 1.6.20-1.0.5 rocks! Thanks guys!!! 🙇🏻‍♂️ 🚀

**Comment by neetopia** [comment]
Glad it worked out for you! 

As for your question, the annotations on a type a part of the type system, usually you don't need them, they can be found if the annotation is applied on the type rather than the property, you only need to check type annotations if you know you are looking for type annotations.
