### ISSUE TITLE
Generated resources are not included in assembled jar by default

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#84]
I have to work around this by making the `processResources` task depend on the `KotlinCompile` task, and think this is something the KSP gradle plugin should probably automatically handle.

Here's how I've implemented a workaround in a plugin for my auto-service-ksp plugin: https://github.com/ZacSweers/auto-service-ksp/blob/a9bbdce6e16e678a187f7ecb49307bffd9f539e0/gradle-plugin/src/main/kotlin/dev/zacsweers/autoservice/gradle/AutoServiceKspGradlePlugin.kt#L16-L26

**Comment by ZacSweers** [comment]
Got burned by this when KSP changed its generated sources location in a recent release, just as added signal for why I think it would be useful :)

**Comment by ting-yuan** [comment]
#215 is landed as a workaround, which will be available in next release. An upstream patch is needed to fix this cleanly and will be addressed later.
