### ISSUE TITLE
Sealed class's KSDeclaration.isOpen returns true

### ISSUE THREAD

**Issue by amandeepg** [google/ksp#858]
### Expected result
`KSDeclaration.isOpen() == true` for sealed classes

### Actual result
`KSDeclaration.isOpen() == false` for sealed classes

### Purpose

In order to determine whether a class can have subclasses (so I know whether to use `<T>` or `<? extends T>`/`<out T>`), I'm using `KSDeclaration.isOpen()` but this doesn't work for sealed classes as this function returns true, but I expect it to return false to indicate it has subclasses.

I can workaround this by checking for the `SEALED` modifier but this seems to break the contract for `isOpen`

**Comment by neetopia** [comment]
How is `isOpen()` related to whether a class has sub classes or not? A class being open does not necessary mean it has subclasses if there is none.

I am also a little bit confused by your ask here, as you are saying "but I expect it to return false to indicate it has subclasses", which does not sound right, as a false for `isOpen()` should mean a class has no sub classes.

**Comment by neetopia** [comment]
But the base class for sealed classes should be open, #910 contains a fix to that issue.

**Comment by amandeepg** [comment]
Sorry that was poorly phrased, whether a class _has_ a subclass or not shouldn't change its `isOpen` result. I meant that if it _could_ it should be open. #910 looks like it would fix the bug I intended to describe.
