### ISSUE TITLE
KSClassDeclaration.isOpen returns `true` for nested data classes

### ISSUE THREAD

**Issue by yigit** [google/ksp#876]
For the given input:

```
interface NestedDataClassSubject {
    data class NestedDataClass(
      val field: String,
     )
  }
```

Calling `NestedDataClass.isOpen` returns `true` instead of `false`.

Looks like it is coming from [this line](https://github.com/google/ksp/blob/main/api/src/main/kotlin/com/google/devtools/ksp/utils.kt#L218) but it is very old code so I couldn't figure out why we check for the parent declaration's `classKind`.

I've not tested but reading the code, this probably affects any other code. 

Related room issue: https://issuetracker.google.com/issues/221280927

**Comment by neetopia** [comment]
the major reason is that the interface members are effectively open for member functions and properties, but it looks like nested class inside interface is an outlier here.

**Comment by yigit** [comment]
oh i just noticed that while trying to write the test in KSP.

I think this is intended for methods and properties in interfaces, you are right.

**Comment by yigit** [comment]
sent a PR: https://github.com/google/ksp/pull/877
