### ISSUE TITLE
Question: How to specify a KSTypeReference from a string

### ISSUE THREAD

**Issue by gpartida** [google/ksp#884]
In my processor I would like to filter all new files that contain a class whose base class is a certain type, but I don't have a reference to this type in my module I just have the fully namespaced type name. I am trying to use code like:

`newFiles.filter { file -> file.declarations.any { it is KSClassDeclaration && it.superTypes.contains() } }`

But I can't find any documentation on how to specify the superType I want to filter on in the .contains call at the end if I just have a class name in a string such as "com.example.BaseClass". Is this possible to do or do I need to have an actual reference to com.example.BaseClass in my processor?

**Comment by ting-yuan** [comment]
KSTypeReference needs to be resolved if the comparison of the underlying declaration is desired. For example, the references to the two `String` are different, even though they reference to the same thing.
```
val s1: String = ...
val s2: String = ...
```

Fully qualified names and classes are 1-to-1 mapping in well formed source / classpath. Therefore I would recommend comparing with fqn:
```
newFiles.filter { file ->
  file.declarations.any {
    it is KSClassDeclaration && it.superTypes.any { it.resolve().declaration.qualifiedName.asString() == "interesting.name" }
  }
}
```

**Comment by gpartida** [comment]
Thank you, worked as expected.
