### ISSUE TITLE
`isAssignableFrom` behaves incorrectly with Java-specific types (from `Resolver.getJavaClassByName`)

### ISSUE THREAD

**Issue by Jeffset** [google/ksp#890]
Suppose we do the following:
```kotlin
val javaCollection = resolver.getJavaClassByName("kotlin.collections.Collection")  // maps to `java.util.Collection`
val javaSet = resolver.getJavaClassByName("kotlin.collections.Set")  // maps to `java.util.Set`
javaCollection.isAssignableFrom(javaSet)  // Expected: true, actual: false
```
As far as my investigations went, Kotlin compiler basically walks type hierarchy. And the superinterface for `java.util.Set` is `kotlin.collections.Collection` for some reason, not `java.util.Collection`. Thus, `java.util.Collection` is never encountered and check ends with negative result.

**Comment by neetopia** [comment]
Actually, how are you calling `isAssignableFrom` on the return result of `resolver.getJavaClassByName`? Do you have any extension function that enables this check for `KSClassDeclaration`, like convert it to a star projected type?

**Comment by neetopia** [comment]
Tried my above mentioned approach, and I can reproduce this bug.

**Comment by neetopia** [comment]
The problem is that `kotlinType.getSuperTypes()` will convert the java types into kotlin types, but won't convert the `kotlinType` being checked itself. Potentially needs a fix in compiler for the subtype checker, workaround-able in KSP though.
