### ISSUE TITLE
Compatibility with Kotlin/Native compiler plugins

### ISSUE THREAD

**Issue by rickclephas** [google/ksp#897]
We are [seeing](https://github.com/rickclephas/KMP-NativeCoroutines/issues/50) a similar error as in #207 where required plugin options aren't provided to the compiler plugin by KSP.
Looking at that issue this should be fixed by #270, though it looks like that fix isn't applied to the [KspTaskNative](https://github.com/ting-yuan/ksp/blob/37fd5af015dd7292fdc12d648ea1b83e627d4b34/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L783) task.

**Comment by ting-yuan** [comment]
Before this is fixed, it can be worked around by blocking other compiler plugins in KSP's task. I.e., settings this in build.gradle[.kts]
```
ksp {
    blockOtherCompilerPlugins = true
}
```

This only affects tasks where processors run, and don't apply to compilation tasks.

**Comment by TadeasKriz** [comment]
Setting the `blockOtherCompilerPlugins = true` results in `Caused by: java.lang.ClassNotFoundException: com.google.devtools.ksp.processing.KSPLogger` exception being thrown. My understanding is, that it removes the `symbol-processing-api` jar from the compiler's classpath as well.
