### ISSUE TITLE
Revert SVG class diagram deletion

### ISSUE THREAD

**Issue by aSemy** [google/ksp#905]
The docs were deleted in https://github.com/google/ksp/pull/882 because they're hosted on kotlinlang.org

This makes sense, however the SVG diagram is now no longer available, only a PNG: https://kotlinlang.org/docs/ksp-additional-details.html

It's much nicer having an SVG because it's easier to update, and I can ctrl+f for elements.

Here's the SVG in git history https://github.com/google/ksp/blob/f7bb2c88c0d86b08fa58c5ca3c87625ef750d119/docs/ClassDiagram.svg

Can the SVG diagram be hosted in the repo, or added https://github.com/google/ksp/wiki ?

**Comment by neetopia** [comment]
SVG is now back at https://kotlinlang.org/docs/images/ksp-class-diagram.svg
