### ISSUE TITLE
what the best way to judge subType 

### ISSUE THREAD

**Issue by Tobi1025** [google/ksp#906]
I tried to get the class's superclass by getAllSuperTypes,but the description of the fuction said that it is expensive and should be avoided if possible. For example,A extends BaseActivity,BaseActivity extends “android.app.Activity”.I also tried to called 
`kSClassDeclaration.superTypes.forEach{
                、、、
}`,but this function can only find BaseActivity,not “android.app.Activity”.

So, If I want to know if A is a subclass of  "android.app.Activity", What's the best way to do that？

**Comment by neetopia** [comment]
the caveat of expensive function call is just to avoid users to abuse this function, in your case this is definitely needed therefore feel free to use it as needed.

Alternatively, you can also use `KSType.isAssignableFrom` for subtype checking, if you convert both class declarations into `KSType`.

**Comment by Tobi1025** [comment]
ok，thanks for your answer
