### ISSUE TITLE
java.io.EOFException after upgrading to 1.6.20-RC2-1.0.4

### ISSUE THREAD

**Issue by SamZXY** [google/ksp#909]
We are seeing a pretty generic `java.io.EOFException` build error after upgrading to 1.6.20-RC2-1.0.4, we did **not** see the same issue in 1.6.20-RC-1.0.4.

Kotlin version: 1.6.20-RC2

```
Failure 1 of 1The foo:kspDebugKotlin task failed.View task in console log Failure analysis is not yet available for this build. java.io.EOFException > (No message provided) Exception org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':foo:kspDebugKotlin'. at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147) ••• Caused by: org.gradle.api.UncheckedIOException: java.io.EOFException at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62) ••• Caused by: java.io.EOFException: (No message provided) at org.jetbrains.kotlin.gradle.internal.kapt.incremental.ClasspathEntryData.readObject(ClasspathAnalyzer.kt:190)
```

**Comment by ting-yuan** [comment]
Have you tried to clean the caches and do a clean build?

Also, can you post the full stacktrace if possible?

**Comment by Tapchicoma** [comment]
@SamZXY hi, is it possible to provide a project reproducing this issue?

**Comment by SamZXY** [comment]
Cleaning the cache and clean build did resolve the issue, thanks all for the timely response!

**Comment by ting-yuan** [comment]
Cool! It could be some leftover cache that wasn't compatible across compiler changes.

I'm closing the issue now. Please feel free to reopen if it comes back again (a full stacktrace or reproducing project would be very helpful for further investigation then).
