### ISSUE TITLE
Any verbosity options available?

### ISSUE THREAD

**Issue by amandeepg** [google/ksp#927]
Is there any equivalent to Java annotation processing's `-XprintRounds` or Kapt's `KaptTask.verbose` to get extra debugging information about KSP's processing or rounds?

**Comment by neetopia** [comment]
We don't have such information yet, it sounds reasonable to add.

**Comment by neetopia** [comment]
while linked PR will fulfill your specific request, I am still open to more verbose mode suggestions :)
