### ISSUE TITLE
Could not extract location from getSealedSubclasses declaration

### ISSUE THREAD

**Issue by midery** [google/ksp#936]
We use KSP to analyze all classes in module and file location for each class is crucial. 
However, if we try to do something like: 
```kotlin
classDeclaration
  .getSealedSubclasses()
  .forEach { sealedClass ->
    sealedClass.location //or sealedClass.parentDeclaration.containingFile
  }
```
We will get `NonExistLocation` or `null`. 
Is it an expected behavior or could it be fixed in the future?

**Comment by neetopia** [comment]
Is your sealed sub classes in source code or from another module/library? Location is only available for symbols on the current compile module.

**Comment by midery** [comment]
In this scenario, sealed sub classes were located in source code from current module
