### ISSUE TITLE
KSP does not handle symlinks for new files in followup rounds

### ISSUE THREAD

**Issue by yigit** [google/ksp#948]
AOSP bug: https://b.corp.google.com/issues/213234559

To reproduce, you can run the `XProcessingStepTest.kspProcessingEnvCaching` in AndroidX on a mac machine (checkout repo, `cd room && ./gradlew studio` to open the project).

From my debugging, it seems to be failing on this line:

https://github.com/google/ksp/blob/main/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt#L164

```
newFiles = ksFiles.filter {
                    when (it) {
                        is KSFileImpl -> it.file
                        is KSFileJavaImpl -> it.psi
                        else -> null
                    }?.virtualFile?.let { virtualFile ->
                        virtualFile.canonicalPath ?: virtualFile.path
                    } in newFileNames
                }
```

The path in `newFileNames` is 

```
/private/var/folders/t8/5nj0qf254j99114y1y5v086w007_hl/T/junit853351931968675205/ksp/generatedJava/foo/bar/Main_Impl.java
```

Whereas, the VirtualFile's `myIoFile` field is: `/var/folders/t8/5nj0qf254j99114y1y5v086w007_hl/T/junit853351931968675205/ksp/generatedJava/foo/bar/Main_Impl.java`

(notice the lack of `/private`. In my system, `/var`  is a symlink to `/private/var`

```
ls  -lah /var
lrwxr-xr-x@ 1 root  wheel    11B Feb 25 23:05 /var -> private/var
```
Unfortunately, I cannot debug what `canonicalPath` returns for that file but if I'm finding the source correctly, it seems to simply return the path:

https://upsource.jetbrains.com/idea-ce/file/idea-ce-6a856f22b82f6478cd6fbdc0f281c28d5c75b712/platform/core-api/src/com/intellij/openapi/vfs/VirtualFile.java?nav=11254:11270:focused&line=478&preview=false

**Comment by jsjeon** [comment]
> if I'm finding the source correctly, it seems to simply return the path

Note that that's the default impl behavior. It's supposed to resolve sym link like this: https://github.com/JetBrains/intellij-community/blob/master/platform/vfs-impl/src/com/intellij/openapi/vfs/newvfs/impl/VirtualFileSystemEntry.java#L542

**Comment by neetopia** [comment]
the files comes from compiler as this is a compiler extension, I guess KSP doesn't have control over what the underlying implementation will be?
