### ISSUE TITLE
Inconsistency in type of `vararg` parameter of overriden method

### ISSUE THREAD

**Issue by efemoney** [google/ksp#958]
Say I have these 2 classes:

```
@ProcessThis
interface Sub : Super

@ProcessThis
interface Super {
  fun foo(vararg values: String)
}
```

When processing any of the KSClassDeclarations with `getAllFunctions().filter { it.isAbstract }.forEach { ... }`, the `values` parameter for `Super` has 
```
  KSValueParameter.isVararg == true
  KSValueParameter.type.resolve() == 'String'
```
but `Sub` has
```
  KSValueParameter.isVararg == true
  KSValueParameter.type.resolve() == 'Array<String>'
```
which is very inconsistent.

They should either both be, `vararg=true type=String` or both be `vararg=true type=Array<String>`

**Comment by bitPogo** [comment]
Hey - as mentioned on KotlinSlack - I run in the same issue and in order not to spam your backlog, I'd like to share my finding here. So please consider the example above:
The value of `KSValueParameter.type.element.typeArguments` the values differs. While Super will have no TypeArguments present, Sub will have at least one - which can be resolved to a covariant type (so in this case `out String`).
Hope that helps.
