### ISSUE TITLE
property annotation are not copied to the KSPropertyGetterSyntheticImpl

### ISSUE THREAD

**Issue by yigit** [google/ksp#97]
Given a test subject like this:

```kotlin
            class Subject {
                @get:SuppressWarnings("onGetter")
                @set:SuppressWarnings("onSetter")
                @field:SuppressWarnings("onField")
                @setparam:SuppressWarnings("onSetParam")
                var prop:Int = TODO()
            }
```

When i get the `prop.getter` as `KSPropertyGetter`, it does not have any annotations.
I can still read the annotations from the property so I'm not sure if it qualifies as a `bug` but it is probably worth documenting in the KSPropertyGetter/Setter classes that annotations will not be copied over automatically and callers should look both places to get annotations.

**Comment by neetopia** [comment]
KSP models such annotation use-site target in its declared site which is the property itself, so it is the intentional behavior. I'll update docs to make it easier to catch.
