### ISSUE TITLE
Exceptions are swallowed when using withCompilation flag

### ISSUE THREAD

**Issue by idanakav** [google/ksp#974]
Hey, per title, when `returnOkOnError=false && withCompilation=true` I would expect to fail with calling 
`AnalysisResult.compilationError` instead of [proceeding](https://github.com/google/ksp/blob/main/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt#L277) with the compilation.

Any reason we would not want to fail fast in that scenario?

Happy to submit a PR in case you agree with this case.

**Comment by neetopia** [comment]
They are not really swallowed, it is intentional. The reason is that we want to provide most details about errors in the code, KSP is not able to provide any diagnostics due to its limitation, therefore when `withCompilation` flag is enabled, we want the users still have a chance to get the diagnostics from the compiler for troubleshooting.

**Comment by Gzernov** [comment]
I agree with @idanakav. When I have `withCompilation` enabled, I would still like my build to fail if there . 
@neetopia 's argument also sounds reasonable. While it's not a good solution in general, maybe it's reasonable to add one more flag that forces build to fail on the error?

**Comment by neetopia** [comment]
Fair enough, let me consider it. Will keep you updated.

**Comment by idanakav** [comment]
@neetopia wondering if you had a chance to give it any thoughts? do you think an extra flag would be the way to go? I'm happy to help with contributing.

**Comment by neetopia** [comment]
Thanks for the remind, added to next milestone for discussion.

**Comment by neetopia** [comment]
This actually looks like a bug to me after taking a deep look, basically the logic here ignores `returnOkOnError` when `withCompilation` is set to true. Current plan is to fix it rather than introducing a new flag.
