### ISSUE TITLE
Annotated symbols not found when running from command line

### ISSUE THREAD

**Issue by Gzernov** [google/ksp#976]
Hi, I'm trying to run KSP from command line following the [docs](https://kotlinlang.org/docs/ksp-command-line.html)
I'm running the script from above on my source files, and the code `resolver.getSymbolsWithAnnotation(MyAnnotation::class.java.canonicalName).filter { !it.validate() }` returns empty list. 
When I compile it using maven everything works as intended.

Any idea why does it happen? 

With this snippet I'm trying to get annotations on classes I'm interested in, and it returns list of correct annotations
Code:
`resolver.getAllFiles().filter { it.fileName.contains("MyFile") }.forEach { debug("$it ${it.declarations.filter { d -> d is KSClassDeclaration }.map { c -> c.annotations.toList() }.toList()}") }`
Output:
`
info: [ksp] File: MyFile.java [[@Component, @Primary, @MyAnnotation]]
`
(To clarify, I have mix of java and kotlin files in the project, but `resolver.getSymbolsWithAnnotation` ignores both of them. Snippet above returns correct list for all files. `isAnnotationPresent` also returns false on command line env and true on mvn env)

**Comment by neetopia** [comment]
To work in command line you need to pass all necessary dependencies in class path, can you check if the jar containing your `MyFile` annotation is on classpath?

**Comment by Gzernov** [comment]
Yeah, I double-checked the class-path. Right now annotation is simply in the annotation processor's module, so it's simply `-cp $AP`

**Comment by Gzernov** [comment]
Sorry, the description was a bit incorrect. `resolver.getSymbolsWithAnnotation` itself returns some elements, but they all don't pass validation check

**Comment by neetopia** [comment]
Validation check is more complicated to investigate without seeing the actual workload.. It might just be some components of the subject being validated is not on classpath again... Can you provider a sample code for your issue?

**Comment by Gzernov** [comment]
I quickly looked over the validation code, so to simplify the process I wrote the following:
Source code maven submodule:
```java
// java file
import com.mycompany.MyAnnotation;

@MyAnnotation
public class Foo {
}
```

Annotation processor submodule:
```kotlin
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.ANNOTATION_CLASS, AnnotationTarget.CLASS)
annotation class MyAnnotation

override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(MyAnnotation::class)
        debug("${symbols.toList()}")
        var ret = symbols.filter { !it.validate() }.toList()

        ret.forEach { logger.warn("Invalid @MyAnnotation", it) }
}
```
(Processor and Provider are standard, so they are omitted) 

Result output
```
warning: [ksp] <source-code-path>/Foo.java:11: Invalid @MyAnnotation
warning: [ksp] Unable to process:com.mycompany.ProcessorProvider:   Foo
```
From my understanding nothing should interfere with processing `Foo` class
(In the project itself there are a lot of extra stuff like Spring, etc. which may not be in CP and I may overlook it. But the `Foo` itself doesn't import anything so should be no problem)

**Comment by neetopia** [comment]
Tried playground locally with cmd mode, still can't seem to reproduce your issue, please check attached playground, to run KSP, download and unzip kotlinc 1.6.21 into root directory of the playground and run `rm -rf out && ./run.sh -cp ./test-processor/build/libs/test-processor-1.0-SNAPSHOT.jar workload/**/*.java`

[playground.zip](https://github.com/google/ksp/files/8627985/playground.zip)

**Comment by neetopia** [comment]
note that `/**/*.java` is a zsh syntax, so if you are not on zsh, you can just manually specify the single Java file in the workload directory, that way should align with your test case. 

output on my console: 
```
warning: [ksp]playground/workload/src/main/java/com/example/Foo.java:6: validity: true
```

**Comment by Gzernov** [comment]
Thank you for looking into it. 
Indeed, with this simple example everything works just fine. I'll close the issue and post the update if I manage to pinpoint the problem in my environment.

**Comment by Gzernov** [comment]
I also created playground project from scratch for maven and it works just fine. I'm probably missing something in my main project.
