### ISSUE TITLE
Synthetic constructors are not created for Java sources

### ISSUE THREAD

**Issue by yigit** [google/ksp#98]
Given the following sources:
```java
public class JavaClass {}
```

Ksp does not return anything for the constructor neither from `findPrimaryConstructor` nor `getAllFunctions`.

On the other hand, java processor (or KAPT) will generate a constructor for it (and java processing API's `ElementFilter.constructorsIn` returns a method for it.

It would be nice if KSP did the same.
The only workaround I found is to check if this KSClassDeclaration is:
* origin == java
* isAbstract == false
synthesize one myself.

**Comment by yigit** [comment]
actually isAbstract is not the right check there, KAPT / java creates it for abstract classes as well hence i need to check `isInterface`

**Comment by neetopia** [comment]
This shouldn't be a primary constructor as Java does not have such concept. I will support the synthetic default constructor instead to support this.
