### ISSUE TITLE
Can't process symbols with external dependencies in CommonMain starting kotlin 1.6.20

### ISSUE THREAD

**Issue by mr0xf00** [google/ksp#980]
Hi,
Ever since Kotlin 1.6.20-RC (with KSP 1.6.20-RC-1.0.4), I've been unable to get any of my KSP processors to work with CommonMain sourcesets. After a bit of testing I managed to narrow down the problem to KSP being unable to resolve any symbol that is foreign to the current module. Strangely enough it still works if the external module happens to be compiled with kotlin 1.6.10 or less. Anything from 1.6.20RC -> 1.7.0-Beta does not (I've tried all of them). 

Any class that is referencing external types cannot be found using `getSymbolsWithAnnotation`, regardless of the processing round. It will however be found manually using `getClassDeclarationByName`, but any attempt to resolve any of its annotations that happens to live outside the module will result in a symbol with `<Error> `as a name.

This is a repo to help you reproduce the problem https://github.com/mr0xf00/kspmpptest. 
After running the `app:build` task you'll notice the following line `[ksp] found 0 valid symbols with annotation.`. And `[ksp] found 1 valid symbols with annotation.` after switching to 1.6.10 in gradle.properties.

I think this might have something to do with the hierarchical sourcesets that were made the default in Kotlin 1.6.20. But disabling them (even using the new params) didn't help. And of course this only affects the metadata target and applying the same processor on the Jvm target works as expected.

**Comment by mr0xf00** [comment]
It seems the problem goes away after adding another KMP target to the external module. For example any types in the `:annotations` module in the project attached will not be resolved while processing the `:app` module starting Kotlin 1.6.20 with the following : 
```kotlin
//annotations/build.gradle.kts
plugins { kotlin("multiplatform") }
koltin { jvm() }
```
But will work after adding something like :
```kotlin
koltin { 
   jvm()
   js { browser() }
}
```
The `:app` module has only the jvm target in both cases, and for some reason it will continue to work after the first successful compilation even after removing the js target, as long as the build folders are not removed.

**Comment by neetopia** [comment]
This might not be a KSP issue. What happens here is the problem with the artifacts from building annotations module. When only `jvm()` target is applied, the generated `annotations-metadata.jar` does not have meaningful content inside it, and when `js()` target is added, then the generated `annotations-metadata.jar` will contain valid metadata information for use for other modules. 

Note that the above is observed by just building `annotations` module, where KSP is not even touched. Therefore, with the missing valid `annotation-metadata.jar`, in the `app` module's KSP task, KSP won't be able to find the annotation class you specified from classpath, which then results in the issue mentioned here

**Comment by neetopia** [comment]
closing as this issue does not seem to be related to KSP but rather with new KMP model.

**Comment by richard-hgs** [comment]
If i try to use an annotation like below:

interface DaoInterface {
    @Query("SELECT * FROM my_table WHERE name = '${BuildConfig.NAME}' ")
    func myFunc()
}

The KSFunctionDeclaration annotation parameters become empty.

So we can't read the annotation string parameter because the annotation parameters become empty in this situation.
