### ISSUE TITLE
Inherited `KSFunctionDeclaration`'s `parentDeclaration` returns child class, not the class it was declared in

### ISSUE THREAD

**Issue by Jeffset** [google/ksp#984]
Assume we have the following:
```kotlin
open class Base {
  fun baseMethod() { /**/ }
}

class Child : Base() {
  fun childMethod() { /**/ }
}
```

Then, when we run KSP on such code and invoke `childClassDeclaration.getAllFunctions()`, every function from the sequence will have the `Child` as a `parentDeclaration` with *no way to determine the actual base class declaration it was declared in*.

I don't know if this is the designed behavior and it has some motivation behind it. On the other hand, javax's `ExecutableElement.enclosingElement` behaves as I expect: it yields the actual class the method is declared in, not the class it was queried from.

If one needs to obtain this info anyway, one can probably walk the type hierarchy manually, invoking `getDeclaredFunctions()` for each class. Though the implementations of `getAllFunctions()` and `getDeclaredFunctions()` are very different and I worry about any side-effects or correctness issues of such manual walk.

So any info on the subject would be welcome.

**Comment by neetopia** [comment]
This is by design, there is a `findOverridee` function which will return the function that current function is overriding, and querying on this API repeatedly will eventually lead to the function you are looking for.

**Comment by Jeffset** [comment]
Oh, okay, thanks for clearing that up. Closing the issue then.
