### ISSUE TITLE
Default annotation argument values missing during non-jvm processing

### ISSUE THREAD

**Issue by mpetuska** [google/ksp#987]
When running a processor on non-jvm targets, annotation argument default values are always null.

The values are present for jvm processors (tested with both, K/JVM and K/MPP plugins)

See the README of the attached reproducer for more details.

[ksp-repro.zip](https://github.com/google/ksp/files/8686155/ksp-repro.zip)

**Comment by neetopia** [comment]
Seems to be the same issue as #885

**Comment by mpetuska** [comment]
Duplicated by #885
