### ISSUE TITLE
edk2 quickstart for virtualization | 🇺🇦 kraxel’s news

### ISSUE THREAD

**Issue by Bert66cool** [google/ksp#996]
"Build/ArmVirtQemu-AARCH64/DEBUG_GCC5/FV"
 https://www.kraxel.org/blog/2022/05/edk2-virt-quickstart/#:~:text=results%20land%20in-,Build/ArmVirtQemu%2DAARCH64/DEBUG_GCC5/FV,-.

**Comment by neetopia** [comment]
This article seems to be about QEMU, can't see anything relates to KSP.
